// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.typedef;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.util.List;

/**
 * FIXME: ...
 */
@JsonSerialize
public class CandidateKeysForSearchStatistic {
    @JsonProperty("FEATURE_TYPES")
    private List<FeatureType> featureTypes;

    @JsonProperty("SUMMARY")
    private CandidateKeysSummary summary;

    public CandidateKeysForSearchStatistic() {
    }

    /**
     * Getter for featureTypes.<p>
     * A list of ...
     */
    public List<FeatureType> getFeatureTypes() {
        return featureTypes;
    }

    /**
     * Setter for featureTypes.<p>
     * A list of ...
     */
    public void setFeatureTypes(List<FeatureType> featureTypes) {
        this.featureTypes = featureTypes;
    }

    /**
     * Getter for summary.<p>
     */
    public CandidateKeysSummary getSummary() {
        return summary;
    }

    /**
     * Setter for summary.<p>
     */
    public void setSummary(CandidateKeysSummary summary) {
        this.summary = summary;
    }
}
