// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.typedef;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

@JsonSerialize
public class CfgCfrtn {
    @JsonProperty("CFRTN_ID")
    private Integer cfrtnId;

    @JsonProperty("CFUNC_ID")
    private Integer cfuncId;

    @JsonProperty("CFUNC_RTNVAL")
    private String cfuncRtnval;

    @JsonProperty("CLOSE_SCORE")
    private Integer closeScore;

    @JsonProperty("EXEC_ORDER")
    private Integer execOrder;

    @JsonProperty("FTYPE_ID")
    private Integer ftypeId;

    @JsonProperty("LIKELY_SCORE")
    private Integer likelyScore;

    @JsonProperty("PLAUSIBLE_SCORE")
    private Integer plausibleScore;

    @JsonProperty("SAME_SCORE")
    private Integer sameScore;

    @JsonProperty("UN_LIKELY_SCORE")
    private Integer unLikelyScore;

    public CfgCfrtn() {
    }

    /**
     * Getter for cfrtnId.<p>
     */
    public Integer getCfrtnId() {
        return cfrtnId;
    }

    /**
     * Setter for cfrtnId.<p>
     */
    public void setCfrtnId(Integer cfrtnId) {
        this.cfrtnId = cfrtnId;
    }

    /**
     * Getter for cfuncId.<p>
     */
    public Integer getCfuncId() {
        return cfuncId;
    }

    /**
     * Setter for cfuncId.<p>
     */
    public void setCfuncId(Integer cfuncId) {
        this.cfuncId = cfuncId;
    }

    /**
     * Getter for cfuncRtnval.<p>
     */
    public String getCfuncRtnval() {
        return cfuncRtnval;
    }

    /**
     * Setter for cfuncRtnval.<p>
     */
    public void setCfuncRtnval(String cfuncRtnval) {
        this.cfuncRtnval = cfuncRtnval;
    }

    /**
     * Getter for closeScore.<p>
     */
    public Integer getCloseScore() {
        return closeScore;
    }

    /**
     * Setter for closeScore.<p>
     */
    public void setCloseScore(Integer closeScore) {
        this.closeScore = closeScore;
    }

    /**
     * Getter for execOrder.<p>
     */
    public Integer getExecOrder() {
        return execOrder;
    }

    /**
     * Setter for execOrder.<p>
     */
    public void setExecOrder(Integer execOrder) {
        this.execOrder = execOrder;
    }

    /**
     * Getter for ftypeId.<p>
     */
    public Integer getFtypeId() {
        return ftypeId;
    }

    /**
     * Setter for ftypeId.<p>
     */
    public void setFtypeId(Integer ftypeId) {
        this.ftypeId = ftypeId;
    }

    /**
     * Getter for likelyScore.<p>
     */
    public Integer getLikelyScore() {
        return likelyScore;
    }

    /**
     * Setter for likelyScore.<p>
     */
    public void setLikelyScore(Integer likelyScore) {
        this.likelyScore = likelyScore;
    }

    /**
     * Getter for plausibleScore.<p>
     */
    public Integer getPlausibleScore() {
        return plausibleScore;
    }

    /**
     * Setter for plausibleScore.<p>
     */
    public void setPlausibleScore(Integer plausibleScore) {
        this.plausibleScore = plausibleScore;
    }

    /**
     * Getter for sameScore.<p>
     */
    public Integer getSameScore() {
        return sameScore;
    }

    /**
     * Setter for sameScore.<p>
     */
    public void setSameScore(Integer sameScore) {
        this.sameScore = sameScore;
    }

    /**
     * Getter for unLikelyScore.<p>
     */
    public Integer getUnLikelyScore() {
        return unLikelyScore;
    }

    /**
     * Setter for unLikelyScore.<p>
     */
    public void setUnLikelyScore(Integer unLikelyScore) {
        this.unLikelyScore = unLikelyScore;
    }
}
