// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.typedef;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

@JsonSerialize
public class CfgGplan {
    @JsonProperty("GPLAN_CODE")
    private String gplanCode;

    @JsonProperty("GPLAN_DESC")
    private String gplanDesc;

    @JsonProperty("GPLAN_ID")
    private Integer gplanId;

    public CfgGplan() {
    }

    /**
     * Getter for gplanCode.<p>
     */
    public String getGplanCode() {
        return gplanCode;
    }

    /**
     * Setter for gplanCode.<p>
     */
    public void setGplanCode(String gplanCode) {
        this.gplanCode = gplanCode;
    }

    /**
     * Getter for gplanDesc.<p>
     */
    public String getGplanDesc() {
        return gplanDesc;
    }

    /**
     * Setter for gplanDesc.<p>
     */
    public void setGplanDesc(String gplanDesc) {
        this.gplanDesc = gplanDesc;
    }

    /**
     * Getter for gplanId.<p>
     */
    public Integer getGplanId() {
        return gplanId;
    }

    /**
     * Setter for gplanId.<p>
     */
    public void setGplanId(Integer gplanId) {
        this.gplanId = gplanId;
    }
}
