// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.typedef;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.util.Map;

/**
 * FIXME: FeatureScoreInfo
 */
@JsonSerialize
public class FeatureScoreInfo {
    @JsonProperty("ADDITIONAL_SCORES")
    private Map<String, Integer> additionalScores;

    @JsonProperty("CANDIDATE_FEAT_DESC")
    private String candidateFeatDesc;

    @JsonProperty("CANDIDATE_FEAT_ID")
    private Integer candidateFeatId;

    @JsonProperty("CANDIDATE_FEAT_USAGE_TYPE")
    private String candidateFeatUsageType;

    @JsonProperty("FTYPE_CODE")
    private String ftypeCode;

    @JsonProperty("INBOUND_FEAT_DESC")
    private String inboundFeatDesc;

    @JsonProperty("INBOUND_FEAT_ID")
    private Integer inboundFeatId;

    @JsonProperty("INBOUND_FEAT_USAGE_TYPE")
    private String inboundFeatUsageType;

    @JsonProperty("SCORE")
    private Integer score;

    @JsonProperty("SCORE_BEHAVIOR")
    private String scoreBehavior;

    @JsonProperty("SCORE_BUCKET")
    private String scoreBucket;

    @JsonProperty("SOURCE")
    private String source;

    @JsonProperty("TOKEN")
    private String token;

    public FeatureScoreInfo() {
    }

    /**
     * Getter for additionalScores.<p>
     * A map from score types to score values.
     */
    public Map<String, Integer> getAdditionalScores() {
        return additionalScores;
    }

    /**
     * Setter for additionalScores.<p>
     * A map from score types to score values.
     */
    public void setAdditionalScores(Map<String, Integer> additionalScores) {
        this.additionalScores = additionalScores;
    }

    /**
     * Getter for candidateFeatDesc.<p>
     * The contents of the candidate feature.
     */
    public String getCandidateFeatDesc() {
        return candidateFeatDesc;
    }

    /**
     * Setter for candidateFeatDesc.<p>
     * The contents of the candidate feature.
     */
    public void setCandidateFeatDesc(String candidateFeatDesc) {
        this.candidateFeatDesc = candidateFeatDesc;
    }

    /**
     * Getter for candidateFeatId.<p>
     * The identifier of the candidate feature.
     */
    public Integer getCandidateFeatId() {
        return candidateFeatId;
    }

    /**
     * Setter for candidateFeatId.<p>
     * The identifier of the candidate feature.
     */
    public void setCandidateFeatId(Integer candidateFeatId) {
        this.candidateFeatId = candidateFeatId;
    }

    /**
     * Getter for candidateFeatUsageType.<p>
     * The usage type of the candidate feature.
     */
    public String getCandidateFeatUsageType() {
        return candidateFeatUsageType;
    }

    /**
     * Setter for candidateFeatUsageType.<p>
     * The usage type of the candidate feature.
     */
    public void setCandidateFeatUsageType(String candidateFeatUsageType) {
        this.candidateFeatUsageType = candidateFeatUsageType;
    }

    /**
     * Getter for ftypeCode.<p>
     * The unique text identifier of the feature type.
     */
    public String getFtypeCode() {
        return ftypeCode;
    }

    /**
     * Setter for ftypeCode.<p>
     * The unique text identifier of the feature type.
     */
    public void setFtypeCode(String ftypeCode) {
        this.ftypeCode = ftypeCode;
    }

    /**
     * Getter for inboundFeatDesc.<p>
     * The contents of the inbound feature.
     */
    public String getInboundFeatDesc() {
        return inboundFeatDesc;
    }

    /**
     * Setter for inboundFeatDesc.<p>
     * The contents of the inbound feature.
     */
    public void setInboundFeatDesc(String inboundFeatDesc) {
        this.inboundFeatDesc = inboundFeatDesc;
    }

    /**
     * Getter for inboundFeatId.<p>
     * The identifier of the inbound feature.
     */
    public Integer getInboundFeatId() {
        return inboundFeatId;
    }

    /**
     * Setter for inboundFeatId.<p>
     * The identifier of the inbound feature.
     */
    public void setInboundFeatId(Integer inboundFeatId) {
        this.inboundFeatId = inboundFeatId;
    }

    /**
     * Getter for inboundFeatUsageType.<p>
     * The usage type of the inbound feature.
     */
    public String getInboundFeatUsageType() {
        return inboundFeatUsageType;
    }

    /**
     * Setter for inboundFeatUsageType.<p>
     * The usage type of the inbound feature.
     */
    public void setInboundFeatUsageType(String inboundFeatUsageType) {
        this.inboundFeatUsageType = inboundFeatUsageType;
    }

    /**
     * Getter for score.<p>
     * Numeric score from the comparison function.
     */
    public Integer getScore() {
        return score;
    }

    /**
     * Setter for score.<p>
     * Numeric score from the comparison function.
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * Getter for scoreBehavior.<p>
     * The behavior used to score the feature.
     */
    public String getScoreBehavior() {
        return scoreBehavior;
    }

    /**
     * Setter for scoreBehavior.<p>
     * The behavior used to score the feature.
     */
    public void setScoreBehavior(String scoreBehavior) {
        this.scoreBehavior = scoreBehavior;
    }

    /**
     * Getter for scoreBucket.<p>
     * Category of score strength.
     */
    public String getScoreBucket() {
        return scoreBucket;
    }

    /**
     * Setter for scoreBucket.<p>
     * Category of score strength.
     */
    public void setScoreBucket(String scoreBucket) {
        this.scoreBucket = scoreBucket;
    }

    /**
     * Getter for source.<p>
     * Resolution data used in producing the score.
     */
    public String getSource() {
        return source;
    }

    /**
     * Setter for source.<p>
     * Resolution data used in producing the score.
     */
    public void setSource(String source) {
        this.source = source;
    }

    /**
     * Getter for token.<p>
     * Artifact label used in match comparison.
     */
    public String getToken() {
        return token;
    }

    /**
     * Setter for token.<p>
     * Artifact label used in match comparison.
     */
    public void setToken(String token) {
        this.token = token;
    }
}
