// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.typedef;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * FIXME: ...
 */
@JsonSerialize
public class FeatureType {
    @JsonProperty("FOUND")
    private Integer found;

    @JsonProperty("FTYPE_CODE")
    private String ftypeCode;

    @JsonProperty("GENERIC")
    private Integer generic;

    @JsonProperty("NOT_FOUND")
    private Integer notFound;

    public FeatureType() {
    }

    /**
     * Getter for found.<p>
     */
    public Integer getFound() {
        return found;
    }

    /**
     * Setter for found.<p>
     */
    public void setFound(Integer found) {
        this.found = found;
    }

    /**
     * Getter for ftypeCode.<p>
     * Internal use.
     */
    public String getFtypeCode() {
        return ftypeCode;
    }

    /**
     * Setter for ftypeCode.<p>
     * Internal use.
     */
    public void setFtypeCode(String ftypeCode) {
        this.ftypeCode = ftypeCode;
    }

    /**
     * Getter for generic.<p>
     */
    public Integer getGeneric() {
        return generic;
    }

    /**
     * Setter for generic.<p>
     */
    public void setGeneric(Integer generic) {
        this.generic = generic;
    }

    /**
     * Getter for notFound.<p>
     */
    public Integer getNotFound() {
        return notFound;
    }

    /**
     * Setter for notFound.<p>
     */
    public void setNotFound(Integer notFound) {
        this.notFound = notFound;
    }
}
