// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.typedef;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.util.List;

@JsonSerialize
public class MatchKeyDetails {
    @JsonProperty("CONFIRMATIONS")
    private List<Confirmation> confirmations;

    @JsonProperty("DENIALS")
    private List<Confirmation> denials;

    @JsonProperty("XXX_ERRULE_CODE")
    private String xxxErruleCode;

    public MatchKeyDetails() {
    }

    /**
     * Getter for confirmations.<p>
     */
    public List<Confirmation> getConfirmations() {
        return confirmations;
    }

    /**
     * Setter for confirmations.<p>
     */
    public void setConfirmations(List<Confirmation> confirmations) {
        this.confirmations = confirmations;
    }

    /**
     * Getter for denials.<p>
     */
    public List<Confirmation> getDenials() {
        return denials;
    }

    /**
     * Setter for denials.<p>
     */
    public void setDenials(List<Confirmation> denials) {
        this.denials = denials;
    }

    /**
     * Getter for xxxErruleCode.<p>
     * Identifier of the entity resolution rule that was triggered.
     */
    public String getXxxErruleCode() {
        return xxxErruleCode;
    }

    /**
     * Setter for xxxErruleCode.<p>
     * Identifier of the entity resolution rule that was triggered.
     */
    public void setXxxErruleCode(String xxxErruleCode) {
        this.xxxErruleCode = xxxErruleCode;
    }
}
