// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.typedef;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

@JsonSerialize
public class ResolvedEntityAndMatchInfo {
    @JsonProperty("ENTITY")
    private EntityForResolvedEntity entity;

    @JsonProperty("FEATURES_MJD")
    private EntityForResolvedEntity featuresMjd;

    @JsonProperty("MATCH_INFO")
    private MatchInfo matchInfo;

    public ResolvedEntityAndMatchInfo() {
    }

    /**
     * Getter for entity.<p>
     */
    public EntityForResolvedEntity getEntity() {
        return entity;
    }

    /**
     * Setter for entity.<p>
     */
    public void setEntity(EntityForResolvedEntity entity) {
        this.entity = entity;
    }

    /**
     * Getter for featuresMjd.<p>
     */
    public EntityForResolvedEntity getFeaturesMjd() {
        return featuresMjd;
    }

    /**
     * Setter for featuresMjd.<p>
     */
    public void setFeaturesMjd(EntityForResolvedEntity featuresMjd) {
        this.featuresMjd = featuresMjd;
    }

    /**
     * Getter for matchInfo.<p>
     */
    public MatchInfo getMatchInfo() {
        return matchInfo;
    }

    /**
     * Setter for matchInfo.<p>
     */
    public void setMatchInfo(MatchInfo matchInfo) {
        this.matchInfo = matchInfo;
    }
}
