// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.typedef;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

@JsonSerialize
public class SenzingEntitySpecification {
    @JsonProperty("ACCOUNT_DOMAIN")
    private String accountDomain;

    @JsonProperty("ACCOUNT_NUMBER")
    private String accountNumber;

    @JsonProperty("ADDR_CITY")
    private String addrCity;

    @JsonProperty("ADDR_COUNTRY")
    private String addrCountry;

    @JsonProperty("ADDR_FULL")
    private String addrFull;

    @JsonProperty("ADDR_LINE1")
    private String addrLine1;

    @JsonProperty("ADDR_LINE2")
    private String addrLine2;

    @JsonProperty("ADDR_LINE3")
    private String addrLine3;

    @JsonProperty("ADDR_LINE4")
    private String addrLine4;

    @JsonProperty("ADDR_LINE5")
    private String addrLine5;

    @JsonProperty("ADDR_LINE6")
    private String addrLine6;

    @JsonProperty("ADDR_POSTAL_CODE")
    private String addrPostalCode;

    @JsonProperty("ADDR_STATE")
    private String addrState;

    @JsonProperty("ADDR_TYPE")
    private String addrType;

    @JsonProperty("CITIZENSHIP")
    private String citizenship;

    @JsonProperty("DATE_OF_BIRTH")
    private String dateOfBirth;

    @JsonProperty("DATE_OF_DEATH")
    private String dateOfDeath;

    @JsonProperty("DRIVERS_LICENSE_NUMBER")
    private String driversLicenseNumber;

    @JsonProperty("DRIVERS_LICENSE_STATE")
    private String driversLicenseState;

    @JsonProperty("DUNS_NUMBER")
    private String dunsNumber;

    @JsonProperty("EMAIL_ADDRESS")
    private String emailAddress;

    @JsonProperty("EMPLOYER")
    private String employer;

    @JsonProperty("EMPLOYER_NAME")
    private String employerName;

    @JsonProperty("FACEBOOK")
    private String facebook;

    @JsonProperty("GENDER")
    private String gender;

    @JsonProperty("GROUP_ASSN_ID_NUMBER")
    private String groupAssnIdNumber;

    @JsonProperty("GROUP_ASSN_ID_TYPE")
    private String groupAssnIdType;

    @JsonProperty("GROUP_ASSOCIATION_ORG_NAME")
    private String groupAssociationOrgName;

    @JsonProperty("GROUP_ASSOCIATION_TYPE")
    private String groupAssociationType;

    @JsonProperty("INSTAGRAM")
    private String instagram;

    @JsonProperty("LEI_NUMBER")
    private String leiNumber;

    @JsonProperty("LINKEDIN")
    private String linkedin;

    @JsonProperty("NAME_FIRST")
    private String nameFirst;

    @JsonProperty("NAME_FULL")
    private String nameFull;

    @JsonProperty("NAME_LAST")
    private String nameLast;

    @JsonProperty("NAME_MIDDLE")
    private String nameMiddle;

    @JsonProperty("NAME_ORG")
    private String nameOrg;

    @JsonProperty("NAME_PREFIX")
    private String namePrefix;

    @JsonProperty("NAME_SUFFIX")
    private String nameSuffix;

    @JsonProperty("NAME_TYPE")
    private String nameType;

    @JsonProperty("NATIONALITY")
    private String nationality;

    @JsonProperty("NATIONAL_ID_COUNTRY")
    private String nationalIdCountry;

    @JsonProperty("NATIONAL_ID_NUMBER")
    private String nationalIdNumber;

    @JsonProperty("NATIONAL_ID_TYPE")
    private String nationalIdType;

    @JsonProperty("NATIVE_NAME_FULL")
    private String nativeNameFull;

    @JsonProperty("NPI_NUMBER")
    private String npiNumber;

    @JsonProperty("OTHER_ID_COUNTRY")
    private String otherIdCountry;

    @JsonProperty("OTHER_ID_NUMBER")
    private String otherIdNumber;

    @JsonProperty("OTHER_ID_TYPE")
    private String otherIdType;

    @JsonProperty("PASSPORT_COUNTRY")
    private String passportCountry;

    @JsonProperty("PASSPORT_NUMBER")
    private String passportNumber;

    @JsonProperty("PHONE_NUMBER")
    private String phoneNumber;

    @JsonProperty("PHONE_TYPE")
    private String phoneType;

    @JsonProperty("PLACE_OF_BIRTH")
    private String placeOfBirth;

    @JsonProperty("PRIMARY_NAME_FIRST")
    private String primaryNameFirst;

    @JsonProperty("PRIMARY_NAME_FULL")
    private String primaryNameFull;

    @JsonProperty("PRIMARY_NAME_LAST")
    private String primaryNameLast;

    @JsonProperty("PRIMARY_NAME_MIDDLE")
    private String primaryNameMiddle;

    @JsonProperty("PRIMARY_NAME_ORG")
    private String primaryNameOrg;

    @JsonProperty("RECORD_TYPE")
    private String recordType;

    @JsonProperty("REGISTRATION_COUNTRY")
    private String registrationCountry;

    @JsonProperty("REGISTRATION_DATE")
    private String registrationDate;

    @JsonProperty("REL_ANCHOR_DOMAIN")
    private String relAnchorDomain;

    @JsonProperty("REL_ANCHOR_KEY")
    private String relAnchorKey;

    @JsonProperty("REL_POINTER_DOMAIN")
    private String relPointerDomain;

    @JsonProperty("REL_POINTER_KEY")
    private String relPointerKey;

    @JsonProperty("REL_POINTER_ROLE")
    private String relPointerRole;

    @JsonProperty("SECONDARY_NAME_ORG")
    private String secondaryNameOrg;

    @JsonProperty("SIGNAL")
    private String signal;

    @JsonProperty("SKYPE")
    private String skype;

    @JsonProperty("SSN_NUMBER")
    private String ssnNumber;

    @JsonProperty("TANGO")
    private String tango;

    @JsonProperty("TAX_ID_COUNTRY")
    private String taxIdCountry;

    @JsonProperty("TAX_ID_NUMBER")
    private String taxIdNumber;

    @JsonProperty("TAX_ID_TYPE")
    private String taxIdType;

    @JsonProperty("TELEGRAM")
    private String telegram;

    @JsonProperty("TRUSTED_ID_NUMBER")
    private String trustedIdNumber;

    @JsonProperty("TRUSTED_ID_TYPE")
    private String trustedIdType;

    @JsonProperty("TWITTER")
    private String twitter;

    @JsonProperty("VIBER")
    private String viber;

    @JsonProperty("WEBSITE_ADDRESS")
    private String websiteAddress;

    @JsonProperty("WECHAT")
    private String wechat;

    @JsonProperty("WHATSAPP")
    private String whatsapp;

    @JsonProperty("XXX_ADDR_FROM_DATE")
    private String xxxAddrFromDate;

    @JsonProperty("XXX_ADDR_THRU_DATE")
    private String xxxAddrThruDate;

    @JsonProperty("XXX_PHONE_FROM_DATE")
    private String xxxPhoneFromDate;

    @JsonProperty("XXX_PHONE_THRU_DATE")
    private String xxxPhoneThruDate;

    @JsonProperty("ZOOMROOM")
    private String zoomroom;

    public SenzingEntitySpecification() {
    }

    /**
     * Getter for accountDomain.<p>
     * Domain/system for the account number. An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public String getAccountDomain() {
        return accountDomain;
    }

    /**
     * Setter for accountDomain.<p>
     * Domain/system for the account number. An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public void setAccountDomain(String accountDomain) {
        this.accountDomain = accountDomain;
    }

    /**
     * Getter for accountNumber.<p>
     * Account number (e.g., bank, card). An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * Setter for accountNumber.<p>
     * Account number (e.g., bank, card). An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    /**
     * Getter for addrCity.<p>
     * City/locality. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public String getAddrCity() {
        return addrCity;
    }

    /**
     * Setter for addrCity.<p>
     * City/locality. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public void setAddrCity(String addrCity) {
        this.addrCity = addrCity;
    }

    /**
     * Getter for addrCountry.<p>
     * Country code. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public String getAddrCountry() {
        return addrCountry;
    }

    /**
     * Setter for addrCountry.<p>
     * Country code. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public void setAddrCountry(String addrCountry) {
        this.addrCountry = addrCountry;
    }

    /**
     * Getter for addrFull.<p>
     * Single-field address when parsed components are unavailable.
     * An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public String getAddrFull() {
        return addrFull;
    }

    /**
     * Setter for addrFull.<p>
     * Single-field address when parsed components are unavailable.
     * An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public void setAddrFull(String addrFull) {
        this.addrFull = addrFull;
    }

    /**
     * Getter for addrLine1.<p>
     * First address line (street, number). An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public String getAddrLine1() {
        return addrLine1;
    }

    /**
     * Setter for addrLine1.<p>
     * First address line (street, number). An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public void setAddrLine1(String addrLine1) {
        this.addrLine1 = addrLine1;
    }

    /**
     * Getter for addrLine2.<p>
     * Second address line (apt/suite). An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public String getAddrLine2() {
        return addrLine2;
    }

    /**
     * Setter for addrLine2.<p>
     * Second address line (apt/suite). An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public void setAddrLine2(String addrLine2) {
        this.addrLine2 = addrLine2;
    }

    /**
     * Getter for addrLine3.<p>
     * Third address line (optional). An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public String getAddrLine3() {
        return addrLine3;
    }

    /**
     * Setter for addrLine3.<p>
     * Third address line (optional). An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public void setAddrLine3(String addrLine3) {
        this.addrLine3 = addrLine3;
    }

    /**
     * Getter for addrLine4.<p>
     * Fourth address line (optional). An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public String getAddrLine4() {
        return addrLine4;
    }

    /**
     * Setter for addrLine4.<p>
     * Fourth address line (optional). An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public void setAddrLine4(String addrLine4) {
        this.addrLine4 = addrLine4;
    }

    /**
     * Getter for addrLine5.<p>
     * Fifth address line (optional). An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public String getAddrLine5() {
        return addrLine5;
    }

    /**
     * Setter for addrLine5.<p>
     * Fifth address line (optional). An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public void setAddrLine5(String addrLine5) {
        this.addrLine5 = addrLine5;
    }

    /**
     * Getter for addrLine6.<p>
     * Sixth address line (optional). An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public String getAddrLine6() {
        return addrLine6;
    }

    /**
     * Setter for addrLine6.<p>
     * Sixth address line (optional). An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public void setAddrLine6(String addrLine6) {
        this.addrLine6 = addrLine6;
    }

    /**
     * Getter for addrPostalCode.<p>
     * Postal/ZIP code. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public String getAddrPostalCode() {
        return addrPostalCode;
    }

    /**
     * Setter for addrPostalCode.<p>
     * Postal/ZIP code. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public void setAddrPostalCode(String addrPostalCode) {
        this.addrPostalCode = addrPostalCode;
    }

    /**
     * Getter for addrState.<p>
     * State/province/region code. An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public String getAddrState() {
        return addrState;
    }

    /**
     * Setter for addrState.<p>
     * State/province/region code. An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public void setAddrState(String addrState) {
        this.addrState = addrState;
    }

    /**
     * Getter for addrType.<p>
     * Optional; include when provided by the source. Common
     * values: HOME, MAILING (persons); BUSINESS (organizations).
     * An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public String getAddrType() {
        return addrType;
    }

    /**
     * Setter for addrType.<p>
     * Optional; include when provided by the source. Common
     * values: HOME, MAILING (persons); BUSINESS (organizations).
     * An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public void setAddrType(String addrType) {
        this.addrType = addrType;
    }

    /**
     * Getter for citizenship.<p>
     * Country of citizenship (code or label) as provided by the
     * source. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public String getCitizenship() {
        return citizenship;
    }

    /**
     * Setter for citizenship.<p>
     * Country of citizenship (code or label) as provided by the
     * source. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public void setCitizenship(String citizenship) {
        this.citizenship = citizenship;
    }

    /**
     * Getter for dateOfBirth.<p>
     * An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public String getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * Setter for dateOfBirth.<p>
     * An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public void setDateOfBirth(String dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    /**
     * Getter for dateOfDeath.<p>
     * An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public String getDateOfDeath() {
        return dateOfDeath;
    }

    /**
     * Setter for dateOfDeath.<p>
     * An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public void setDateOfDeath(String dateOfDeath) {
        this.dateOfDeath = dateOfDeath;
    }

    /**
     * Getter for driversLicenseNumber.<p>
     * Driver's license number. An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public String getDriversLicenseNumber() {
        return driversLicenseNumber;
    }

    /**
     * Setter for driversLicenseNumber.<p>
     * Driver's license number. An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public void setDriversLicenseNumber(String driversLicenseNumber) {
        this.driversLicenseNumber = driversLicenseNumber;
    }

    /**
     * Getter for driversLicenseState.<p>
     * Issuing state/province/country. An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public String getDriversLicenseState() {
        return driversLicenseState;
    }

    /**
     * Setter for driversLicenseState.<p>
     * Issuing state/province/country. An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public void setDriversLicenseState(String driversLicenseState) {
        this.driversLicenseState = driversLicenseState;
    }

    /**
     * Getter for dunsNumber.<p>
     * Dun and Bradstreet company identifier. An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public String getDunsNumber() {
        return dunsNumber;
    }

    /**
     * Setter for dunsNumber.<p>
     * Dun and Bradstreet company identifier. An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public void setDunsNumber(String dunsNumber) {
        this.dunsNumber = dunsNumber;
    }

    /**
     * Getter for emailAddress.<p>
     * Email address. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * Setter for emailAddress.<p>
     * Email address. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    /**
     * Getter for employer.<p>
     * This is the name of the organization the person is employed
     * by. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public String getEmployer() {
        return employer;
    }

    /**
     * Setter for employer.<p>
     * This is the name of the organization the person is employed
     * by. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public void setEmployer(String employer) {
        this.employer = employer;
    }

    /**
     * Getter for employerName.<p>
     */
    public String getEmployerName() {
        return employerName;
    }

    /**
     * Setter for employerName.<p>
     */
    public void setEmployerName(String employerName) {
        this.employerName = employerName;
    }

    /**
     * Getter for facebook.<p>
     * Social medial user name. An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public String getFacebook() {
        return facebook;
    }

    /**
     * Setter for facebook.<p>
     * Social medial user name. An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public void setFacebook(String facebook) {
        this.facebook = facebook;
    }

    /**
     * Getter for gender.<p>
     * An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public String getGender() {
        return gender;
    }

    /**
     * Setter for gender.<p>
     * An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * Getter for groupAssnIdNumber.<p>
     * The identifier the entity is associated with. An
     * attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public String getGroupAssnIdNumber() {
        return groupAssnIdNumber;
    }

    /**
     * Setter for groupAssnIdNumber.<p>
     * The identifier the entity is associated with. An
     * attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public void setGroupAssnIdNumber(String groupAssnIdNumber) {
        this.groupAssnIdNumber = groupAssnIdNumber;
    }

    /**
     * Getter for groupAssnIdType.<p>
     * The type of group identifier an entity is associated with.
     * An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public String getGroupAssnIdType() {
        return groupAssnIdType;
    }

    /**
     * Setter for groupAssnIdType.<p>
     * The type of group identifier an entity is associated with.
     * An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public void setGroupAssnIdType(String groupAssnIdType) {
        this.groupAssnIdType = groupAssnIdType;
    }

    /**
     * Getter for groupAssociationOrgName.<p>
     * Name of the associated organization; use the official or standardized
     * name. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public String getGroupAssociationOrgName() {
        return groupAssociationOrgName;
    }

    /**
     * Setter for groupAssociationOrgName.<p>
     * Name of the associated organization; use the official or standardized
     * name. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public void setGroupAssociationOrgName(String groupAssociationOrgName) {
        this.groupAssociationOrgName = groupAssociationOrgName;
    }

    /**
     * Getter for groupAssociationType.<p>
     * Specific group/role within the organization; use precise
     * categories (e.g., OWNER_EXEC, BOARD_MEMBER) to improve
     * resolution. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public String getGroupAssociationType() {
        return groupAssociationType;
    }

    /**
     * Setter for groupAssociationType.<p>
     * Specific group/role within the organization; use precise
     * categories (e.g., OWNER_EXEC, BOARD_MEMBER) to improve
     * resolution. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public void setGroupAssociationType(String groupAssociationType) {
        this.groupAssociationType = groupAssociationType;
    }

    /**
     * Getter for instagram.<p>
     * Social medial user name. An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public String getInstagram() {
        return instagram;
    }

    /**
     * Setter for instagram.<p>
     * Social medial user name. An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public void setInstagram(String instagram) {
        this.instagram = instagram;
    }

    /**
     * Getter for leiNumber.<p>
     * Legal Entity Identifier. An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public String getLeiNumber() {
        return leiNumber;
    }

    /**
     * Setter for leiNumber.<p>
     * Legal Entity Identifier. An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public void setLeiNumber(String leiNumber) {
        this.leiNumber = leiNumber;
    }

    /**
     * Getter for linkedin.<p>
     * Social medial user name. An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public String getLinkedin() {
        return linkedin;
    }

    /**
     * Setter for linkedin.<p>
     * Social medial user name. An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public void setLinkedin(String linkedin) {
        this.linkedin = linkedin;
    }

    /**
     * Getter for nameFirst.<p>
     * Person given name. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public String getNameFirst() {
        return nameFirst;
    }

    /**
     * Setter for nameFirst.<p>
     * Person given name. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public void setNameFirst(String nameFirst) {
        this.nameFirst = nameFirst;
    }

    /**
     * Getter for nameFull.<p>
     * Single-field name when type (person vs org) is unknown or only a full
     * name is provided. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public String getNameFull() {
        return nameFull;
    }

    /**
     * Setter for nameFull.<p>
     * Single-field name when type (person vs org) is unknown or only a full
     * name is provided. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public void setNameFull(String nameFull) {
        this.nameFull = nameFull;
    }

    /**
     * Getter for nameLast.<p>
     * Person surname. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public String getNameLast() {
        return nameLast;
    }

    /**
     * Setter for nameLast.<p>
     * Person surname. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public void setNameLast(String nameLast) {
        this.nameLast = nameLast;
    }

    /**
     * Getter for nameMiddle.<p>
     * Person middle name/initial. An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public String getNameMiddle() {
        return nameMiddle;
    }

    /**
     * Setter for nameMiddle.<p>
     * Person middle name/initial. An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public void setNameMiddle(String nameMiddle) {
        this.nameMiddle = nameMiddle;
    }

    /**
     * Getter for nameOrg.<p>
     * Organization name. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public String getNameOrg() {
        return nameOrg;
    }

    /**
     * Setter for nameOrg.<p>
     * Organization name. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public void setNameOrg(String nameOrg) {
        this.nameOrg = nameOrg;
    }

    /**
     * Getter for namePrefix.<p>
     * Person title. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public String getNamePrefix() {
        return namePrefix;
    }

    /**
     * Setter for namePrefix.<p>
     * Person title. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public void setNamePrefix(String namePrefix) {
        this.namePrefix = namePrefix;
    }

    /**
     * Getter for nameSuffix.<p>
     * Person suffix. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public String getNameSuffix() {
        return nameSuffix;
    }

    /**
     * Setter for nameSuffix.<p>
     * Person suffix. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public void setNameSuffix(String nameSuffix) {
        this.nameSuffix = nameSuffix;
    }

    /**
     * Getter for nameType.<p>
     * Optional include when the source provides it. Common values: PRIMARY,
     * AKA (persons), DBA (organizations). An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public String getNameType() {
        return nameType;
    }

    /**
     * Setter for nameType.<p>
     * Optional include when the source provides it. Common values: PRIMARY,
     * AKA (persons), DBA (organizations). An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public void setNameType(String nameType) {
        this.nameType = nameType;
    }

    /**
     * Getter for nationality.<p>
     * Country of nationality (code or label) as provided by the
     * source. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * Setter for nationality.<p>
     * Country of nationality (code or label) as provided by the
     * source. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    /**
     * Getter for nationalIdCountry.<p>
     * Issuing country. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public String getNationalIdCountry() {
        return nationalIdCountry;
    }

    /**
     * Setter for nationalIdCountry.<p>
     * Issuing country. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public void setNationalIdCountry(String nationalIdCountry) {
        this.nationalIdCountry = nationalIdCountry;
    }

    /**
     * Getter for nationalIdNumber.<p>
     * National identifier value. An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public String getNationalIdNumber() {
        return nationalIdNumber;
    }

    /**
     * Setter for nationalIdNumber.<p>
     * National identifier value. An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public void setNationalIdNumber(String nationalIdNumber) {
        this.nationalIdNumber = nationalIdNumber;
    }

    /**
     * Getter for nationalIdType.<p>
     * Use the type label from the source; standardize across
     * sources. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public String getNationalIdType() {
        return nationalIdType;
    }

    /**
     * Setter for nationalIdType.<p>
     * Use the type label from the source; standardize across
     * sources. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public void setNationalIdType(String nationalIdType) {
        this.nationalIdType = nationalIdType;
    }

    /**
     * Getter for nativeNameFull.<p>
     */
    public String getNativeNameFull() {
        return nativeNameFull;
    }

    /**
     * Setter for nativeNameFull.<p>
     */
    public void setNativeNameFull(String nativeNameFull) {
        this.nativeNameFull = nativeNameFull;
    }

    /**
     * Getter for npiNumber.<p>
     * US healthcare provider identifier. An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public String getNpiNumber() {
        return npiNumber;
    }

    /**
     * Setter for npiNumber.<p>
     * US healthcare provider identifier. An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public void setNpiNumber(String npiNumber) {
        this.npiNumber = npiNumber;
    }

    /**
     * Getter for otherIdCountry.<p>
     * Optional as country often not known or issued by an organization.
     * An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public String getOtherIdCountry() {
        return otherIdCountry;
    }

    /**
     * Setter for otherIdCountry.<p>
     * Optional as country often not known or issued by an organization.
     * An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public void setOtherIdCountry(String otherIdCountry) {
        this.otherIdCountry = otherIdCountry;
    }

    /**
     * Getter for otherIdNumber.<p>
     * Identification number. An attribute in the Senzing Entity Specification.
     * See https://www.senzing.com/docs/entity_specification
     */
    public String getOtherIdNumber() {
        return otherIdNumber;
    }

    /**
     * Setter for otherIdNumber.<p>
     * Identification number. An attribute in the Senzing Entity Specification.
     * See https://www.senzing.com/docs/entity_specification
     */
    public void setOtherIdNumber(String otherIdNumber) {
        this.otherIdNumber = otherIdNumber;
    }

    /**
     * Getter for otherIdType.<p>
     * Standardized source type. An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public String getOtherIdType() {
        return otherIdType;
    }

    /**
     * Setter for otherIdType.<p>
     * Standardized source type. An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public void setOtherIdType(String otherIdType) {
        this.otherIdType = otherIdType;
    }

    /**
     * Getter for passportCountry.<p>
     * Issuing country. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public String getPassportCountry() {
        return passportCountry;
    }

    /**
     * Setter for passportCountry.<p>
     * Issuing country. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public void setPassportCountry(String passportCountry) {
        this.passportCountry = passportCountry;
    }

    /**
     * Getter for passportNumber.<p>
     * Passport number. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public String getPassportNumber() {
        return passportNumber;
    }

    /**
     * Setter for passportNumber.<p>
     * Passport number. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public void setPassportNumber(String passportNumber) {
        this.passportNumber = passportNumber;
    }

    /**
     * Getter for phoneNumber.<p>
     * Telephone number. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * Setter for phoneNumber.<p>
     * Telephone number. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * Getter for phoneType.<p>
     * Optional; include when provided by the source. Common
     * values: MOBILE, HOME, WORK, FAX. MOBILE carries extra
     * weight. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public String getPhoneType() {
        return phoneType;
    }

    /**
     * Setter for phoneType.<p>
     * Optional; include when provided by the source. Common
     * values: MOBILE, HOME, WORK, FAX. MOBILE carries extra
     * weight. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public void setPhoneType(String phoneType) {
        this.phoneType = phoneType;
    }

    /**
     * Getter for placeOfBirth.<p>
     * Place of birth; may be a city/region or a country code/label as provided
     * by the source. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public String getPlaceOfBirth() {
        return placeOfBirth;
    }

    /**
     * Setter for placeOfBirth.<p>
     * Place of birth; may be a city/region or a country code/label as provided
     * by the source. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public void setPlaceOfBirth(String placeOfBirth) {
        this.placeOfBirth = placeOfBirth;
    }

    /**
     * Getter for primaryNameFirst.<p>
     */
    public String getPrimaryNameFirst() {
        return primaryNameFirst;
    }

    /**
     * Setter for primaryNameFirst.<p>
     */
    public void setPrimaryNameFirst(String primaryNameFirst) {
        this.primaryNameFirst = primaryNameFirst;
    }

    /**
     * Getter for primaryNameFull.<p>
     */
    public String getPrimaryNameFull() {
        return primaryNameFull;
    }

    /**
     * Setter for primaryNameFull.<p>
     */
    public void setPrimaryNameFull(String primaryNameFull) {
        this.primaryNameFull = primaryNameFull;
    }

    /**
     * Getter for primaryNameLast.<p>
     */
    public String getPrimaryNameLast() {
        return primaryNameLast;
    }

    /**
     * Setter for primaryNameLast.<p>
     */
    public void setPrimaryNameLast(String primaryNameLast) {
        this.primaryNameLast = primaryNameLast;
    }

    /**
     * Getter for primaryNameMiddle.<p>
     */
    public String getPrimaryNameMiddle() {
        return primaryNameMiddle;
    }

    /**
     * Setter for primaryNameMiddle.<p>
     */
    public void setPrimaryNameMiddle(String primaryNameMiddle) {
        this.primaryNameMiddle = primaryNameMiddle;
    }

    /**
     * Getter for primaryNameOrg.<p>
     */
    public String getPrimaryNameOrg() {
        return primaryNameOrg;
    }

    /**
     * Setter for primaryNameOrg.<p>
     */
    public void setPrimaryNameOrg(String primaryNameOrg) {
        this.primaryNameOrg = primaryNameOrg;
    }

    /**
     * Getter for recordType.<p>
     * Include when known to prevent cross-type resolution; omit if unknown.
     * Use standardized kinds (PERSON, ORGANIZATION). Often used to determine
     * icon/shape in graphs. An attribute in the Senzing Entity Specification.
     * See https://www.senzing.com/docs/entity_specification
     */
    public String getRecordType() {
        return recordType;
    }

    /**
     * Setter for recordType.<p>
     * Include when known to prevent cross-type resolution; omit if unknown.
     * Use standardized kinds (PERSON, ORGANIZATION). Often used to determine
     * icon/shape in graphs. An attribute in the Senzing Entity Specification.
     * See https://www.senzing.com/docs/entity_specification
     */
    public void setRecordType(String recordType) {
        this.recordType = recordType;
    }

    /**
     * Getter for registrationCountry.<p>
     * Country of registration (code or label) as provided by the
     * source. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public String getRegistrationCountry() {
        return registrationCountry;
    }

    /**
     * Setter for registrationCountry.<p>
     * Country of registration (code or label) as provided by the
     * source. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public void setRegistrationCountry(String registrationCountry) {
        this.registrationCountry = registrationCountry;
    }

    /**
     * Getter for registrationDate.<p>
     * Organization registration/incorporation date. An
     * attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public String getRegistrationDate() {
        return registrationDate;
    }

    /**
     * Setter for registrationDate.<p>
     * Organization registration/incorporation date. An
     * attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public void setRegistrationDate(String registrationDate) {
        this.registrationDate = registrationDate;
    }

    /**
     * Getter for relAnchorDomain.<p>
     * This code helps keep the REL_ANCHOR_KEY unique. This is a code (without
     * dashes) for the data source or source field that is contributing the
     * relationship. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public String getRelAnchorDomain() {
        return relAnchorDomain;
    }

    /**
     * Setter for relAnchorDomain.<p>
     * This code helps keep the REL_ANCHOR_KEY unique. This is a code (without
     * dashes) for the data source or source field that is contributing the
     * relationship. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public void setRelAnchorDomain(String relAnchorDomain) {
        this.relAnchorDomain = relAnchorDomain;
    }

    /**
     * Getter for relAnchorKey.<p>
     * This key should be a unique value for the record within the
     * REL_ANCHOR_DOMAIN. You can just use the current record's RECORD_ID
     * here. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public String getRelAnchorKey() {
        return relAnchorKey;
    }

    /**
     * Setter for relAnchorKey.<p>
     * This key should be a unique value for the record within the
     * REL_ANCHOR_DOMAIN. You can just use the current record's RECORD_ID
     * here. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public void setRelAnchorKey(String relAnchorKey) {
        this.relAnchorKey = relAnchorKey;
    }

    /**
     * Getter for relPointerDomain.<p>
     * An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public String getRelPointerDomain() {
        return relPointerDomain;
    }

    /**
     * Setter for relPointerDomain.<p>
     * An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public void setRelPointerDomain(String relPointerDomain) {
        this.relPointerDomain = relPointerDomain;
    }

    /**
     * Getter for relPointerKey.<p>
     * An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public String getRelPointerKey() {
        return relPointerKey;
    }

    /**
     * Setter for relPointerKey.<p>
     * An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public void setRelPointerKey(String relPointerKey) {
        this.relPointerKey = relPointerKey;
    }

    /**
     * Getter for relPointerRole.<p>
     * This is the role the pointer record has to the anchor record. Such
     * as SPOUSE_OF, SON_OF, FATHER_OF, EMPLOYED_BY, PRINCIPAL_OF, OWNER_OF,
     * BRANCH_OF, DIRECT_PARENT, ULTIMATE_PARENT. Standardize these role
     * codes for display and filtering. An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public String getRelPointerRole() {
        return relPointerRole;
    }

    /**
     * Setter for relPointerRole.<p>
     * This is the role the pointer record has to the anchor record. Such
     * as SPOUSE_OF, SON_OF, FATHER_OF, EMPLOYED_BY, PRINCIPAL_OF, OWNER_OF,
     * BRANCH_OF, DIRECT_PARENT, ULTIMATE_PARENT. Standardize these role
     * codes for display and filtering. An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public void setRelPointerRole(String relPointerRole) {
        this.relPointerRole = relPointerRole;
    }

    /**
     * Getter for secondaryNameOrg.<p>
     */
    public String getSecondaryNameOrg() {
        return secondaryNameOrg;
    }

    /**
     * Setter for secondaryNameOrg.<p>
     */
    public void setSecondaryNameOrg(String secondaryNameOrg) {
        this.secondaryNameOrg = secondaryNameOrg;
    }

    /**
     * Getter for signal.<p>
     * Social medial user name. An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public String getSignal() {
        return signal;
    }

    /**
     * Setter for signal.<p>
     * Social medial user name. An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public void setSignal(String signal) {
        this.signal = signal;
    }

    /**
     * Getter for skype.<p>
     * Social medial user name. An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public String getSkype() {
        return skype;
    }

    /**
     * Setter for skype.<p>
     * Social medial user name. An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public void setSkype(String skype) {
        this.skype = skype;
    }

    /**
     * Getter for ssnNumber.<p>
     * US Social Security Number; partial accepted. An
     * attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public String getSsnNumber() {
        return ssnNumber;
    }

    /**
     * Setter for ssnNumber.<p>
     * US Social Security Number; partial accepted. An
     * attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public void setSsnNumber(String ssnNumber) {
        this.ssnNumber = ssnNumber;
    }

    /**
     * Getter for tango.<p>
     * Social medial user name. An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public String getTango() {
        return tango;
    }

    /**
     * Setter for tango.<p>
     * Social medial user name. An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public void setTango(String tango) {
        this.tango = tango;
    }

    /**
     * Getter for taxIdCountry.<p>
     * Issuing country. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public String getTaxIdCountry() {
        return taxIdCountry;
    }

    /**
     * Setter for taxIdCountry.<p>
     * Issuing country. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public void setTaxIdCountry(String taxIdCountry) {
        this.taxIdCountry = taxIdCountry;
    }

    /**
     * Getter for taxIdNumber.<p>
     * Tax identification number. An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public String getTaxIdNumber() {
        return taxIdNumber;
    }

    /**
     * Setter for taxIdNumber.<p>
     * Tax identification number. An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public void setTaxIdNumber(String taxIdNumber) {
        this.taxIdNumber = taxIdNumber;
    }

    /**
     * Getter for taxIdType.<p>
     * Use the type label from the source; standardize across
     * sources. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public String getTaxIdType() {
        return taxIdType;
    }

    /**
     * Setter for taxIdType.<p>
     * Use the type label from the source; standardize across
     * sources. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public void setTaxIdType(String taxIdType) {
        this.taxIdType = taxIdType;
    }

    /**
     * Getter for telegram.<p>
     * Social medial user name. An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public String getTelegram() {
        return telegram;
    }

    /**
     * Setter for telegram.<p>
     * Social medial user name. An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public void setTelegram(String telegram) {
        this.telegram = telegram;
    }

    /**
     * Getter for trustedIdNumber.<p>
     * The identifier value shared by records that must resolve
     * together. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public String getTrustedIdNumber() {
        return trustedIdNumber;
    }

    /**
     * Setter for trustedIdNumber.<p>
     * The identifier value shared by records that must resolve
     * together. An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public void setTrustedIdNumber(String trustedIdNumber) {
        this.trustedIdNumber = trustedIdNumber;
    }

    /**
     * Getter for trustedIdType.<p>
     * Short code for the identifier domain/system (e.g., STEWARD,
     * MASTER_ID). An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public String getTrustedIdType() {
        return trustedIdType;
    }

    /**
     * Setter for trustedIdType.<p>
     * Short code for the identifier domain/system (e.g., STEWARD,
     * MASTER_ID). An attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public void setTrustedIdType(String trustedIdType) {
        this.trustedIdType = trustedIdType;
    }

    /**
     * Getter for twitter.<p>
     * Social medial user name. An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public String getTwitter() {
        return twitter;
    }

    /**
     * Setter for twitter.<p>
     * Social medial user name. An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public void setTwitter(String twitter) {
        this.twitter = twitter;
    }

    /**
     * Getter for viber.<p>
     * Social medial user name. An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public String getViber() {
        return viber;
    }

    /**
     * Setter for viber.<p>
     * Social medial user name. An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public void setViber(String viber) {
        this.viber = viber;
    }

    /**
     * Getter for websiteAddress.<p>
     * Website or domain; typically for organizations. An
     * attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public String getWebsiteAddress() {
        return websiteAddress;
    }

    /**
     * Setter for websiteAddress.<p>
     * Website or domain; typically for organizations. An
     * attribute in the Senzing Entity Specification. See
     * https://www.senzing.com/docs/entity_specification
     */
    public void setWebsiteAddress(String websiteAddress) {
        this.websiteAddress = websiteAddress;
    }

    /**
     * Getter for wechat.<p>
     * Social medial user name. An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * Setter for wechat.<p>
     * Social medial user name. An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public void setWechat(String wechat) {
        this.wechat = wechat;
    }

    /**
     * Getter for whatsapp.<p>
     * Social medial user name. An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public String getWhatsapp() {
        return whatsapp;
    }

    /**
     * Setter for whatsapp.<p>
     * Social medial user name. An attribute in the Senzing Entity
     * Specification. See https://www.senzing.com/docs/entity_specification
     */
    public void setWhatsapp(String whatsapp) {
        this.whatsapp = whatsapp;
    }

    /**
     * Getter for xxxAddrFromDate.<p>
     */
    public String getXxxAddrFromDate() {
        return xxxAddrFromDate;
    }

    /**
     * Setter for xxxAddrFromDate.<p>
     */
    public void setXxxAddrFromDate(String xxxAddrFromDate) {
        this.xxxAddrFromDate = xxxAddrFromDate;
    }

    /**
     * Getter for xxxAddrThruDate.<p>
     */
    public String getXxxAddrThruDate() {
        return xxxAddrThruDate;
    }

    /**
     * Setter for xxxAddrThruDate.<p>
     */
    public void setXxxAddrThruDate(String xxxAddrThruDate) {
        this.xxxAddrThruDate = xxxAddrThruDate;
    }

    /**
     * Getter for xxxPhoneFromDate.<p>
     */
    public String getXxxPhoneFromDate() {
        return xxxPhoneFromDate;
    }

    /**
     * Setter for xxxPhoneFromDate.<p>
     */
    public void setXxxPhoneFromDate(String xxxPhoneFromDate) {
        this.xxxPhoneFromDate = xxxPhoneFromDate;
    }

    /**
     * Getter for xxxPhoneThruDate.<p>
     */
    public String getXxxPhoneThruDate() {
        return xxxPhoneThruDate;
    }

    /**
     * Setter for xxxPhoneThruDate.<p>
     */
    public void setXxxPhoneThruDate(String xxxPhoneThruDate) {
        this.xxxPhoneThruDate = xxxPhoneThruDate;
    }

    /**
     * Getter for zoomroom.<p>
     */
    public String getZoomroom() {
        return zoomroom;
    }

    /**
     * Setter for zoomroom.<p>
     */
    public void setZoomroom(String zoomroom) {
        this.zoomroom = zoomroom;
    }
}
