// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.typedef;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.util.List;

@JsonSerialize
public class SzEngineReevaluateEntityResponse {
    @JsonProperty("AFFECTED_ENTITIES")
    private List<AffectedEntity> affectedEntities;

    @JsonProperty("XXX_DATA_SOURCE")
    private String xxxDataSource;

    @JsonProperty("XXX_INTERESTING_ENTITIES")
    private InterestingEntities xxxInterestingEntities;

    @JsonProperty("XXX_RECORD_ID")
    private String xxxRecordId;

    public SzEngineReevaluateEntityResponse() {
    }

    /**
     * Getter for affectedEntities.<p>
     */
    public List<AffectedEntity> getAffectedEntities() {
        return affectedEntities;
    }

    /**
     * Setter for affectedEntities.<p>
     */
    public void setAffectedEntities(List<AffectedEntity> affectedEntities) {
        this.affectedEntities = affectedEntities;
    }

    /**
     * Getter for xxxDataSource.<p>
     * A label identifying the provenance of the record.
     */
    public String getXxxDataSource() {
        return xxxDataSource;
    }

    /**
     * Setter for xxxDataSource.<p>
     * A label identifying the provenance of the record.
     */
    public void setXxxDataSource(String xxxDataSource) {
        this.xxxDataSource = xxxDataSource;
    }

    /**
     * Getter for xxxInterestingEntities.<p>
     */
    public InterestingEntities getXxxInterestingEntities() {
        return xxxInterestingEntities;
    }

    /**
     * Setter for xxxInterestingEntities.<p>
     */
    public void setXxxInterestingEntities(InterestingEntities xxxInterestingEntities) {
        this.xxxInterestingEntities = xxxInterestingEntities;
    }

    /**
     * Getter for xxxRecordId.<p>
     * The unique identifier within the set of records in the DATA_SOURCE.
     */
    public String getXxxRecordId() {
        return xxxRecordId;
    }

    /**
     * Setter for xxxRecordId.<p>
     * The unique identifier within the set of records in the DATA_SOURCE.
     */
    public void setXxxRecordId(String xxxRecordId) {
        this.xxxRecordId = xxxRecordId;
    }
}
