// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.typedef;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * Internal use.
 */
@JsonSerialize
public class SzEngineFindInterestingEntitiesByEntityIdResponse {
    @JsonProperty("INTERESTING_ENTITIES")
    private InterestingEntities interestingEntities;

    public SzEngineFindInterestingEntitiesByEntityIdResponse() {
    }

    /**
     * Getter for interestingEntities.<p>
     * Internal use.
     */
    public InterestingEntities getInterestingEntities() {
        return interestingEntities;
    }

    /**
     * Setter for interestingEntities.<p>
     * Internal use.
     */
    public void setInterestingEntities(InterestingEntities interestingEntities) {
        this.interestingEntities = interestingEntities;
    }
}
