// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.typedef;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.util.List;

@JsonSerialize
public class SzEngineWhyEntitiesResponse {
    @JsonProperty("ENTITIES")
    private List<Entity> entities;

    @JsonProperty("WHY_RESULTS")
    private List<WhyResult> whyResults;

    public SzEngineWhyEntitiesResponse() {
    }

    /**
     * Getter for entities.<p>
     * A list of entity information.
     */
    public List<Entity> getEntities() {
        return entities;
    }

    /**
     * Setter for entities.<p>
     * A list of entity information.
     */
    public void setEntities(List<Entity> entities) {
        this.entities = entities;
    }

    /**
     * Getter for whyResults.<p>
     * A list of ...
     */
    public List<WhyResult> getWhyResults() {
        return whyResults;
    }

    /**
     * Setter for whyResults.<p>
     * A list of ...
     */
    public void setWhyResults(List<WhyResult> whyResults) {
        this.whyResults = whyResults;
    }
}
