// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.typedef;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.util.List;

@JsonSerialize
public class SzEngineGetEntityByEntityIdResponse {
    @JsonProperty("RELATED_ENTITIES")
    private List<RelatedEntity> relatedEntities;

    @JsonProperty("RESOLVED_ENTITY")
    private ResolvedEntityForGetEntity resolvedEntity;

    public SzEngineGetEntityByEntityIdResponse() {
    }

    /**
     * Getter for relatedEntities.<p>
     */
    public List<RelatedEntity> getRelatedEntities() {
        return relatedEntities;
    }

    /**
     * Setter for relatedEntities.<p>
     */
    public void setRelatedEntities(List<RelatedEntity> relatedEntities) {
        this.relatedEntities = relatedEntities;
    }

    /**
     * Getter for resolvedEntity.<p>
     */
    public ResolvedEntityForGetEntity getResolvedEntity() {
        return resolvedEntity;
    }

    /**
     * Setter for resolvedEntity.<p>
     */
    public void setResolvedEntity(ResolvedEntityForGetEntity resolvedEntity) {
        this.resolvedEntity = resolvedEntity;
    }
}
