// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.typedef;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

@JsonSerialize
public class WorkloadSystemResources {
    @JsonProperty("currResources")
    private WorkloadCurrResources currResources;

    @JsonProperty("initResources")
    private WorkloadInitResources initResources;

    @JsonProperty("systemLoad")
    private WorkloadSystemLoad systemLoad;

    public WorkloadSystemResources() {
    }

    /**
     * Getter for currResources.<p>
     */
    public WorkloadCurrResources getCurrResources() {
        return currResources;
    }

    /**
     * Setter for currResources.<p>
     */
    public void setCurrResources(WorkloadCurrResources currResources) {
        this.currResources = currResources;
    }

    /**
     * Getter for initResources.<p>
     */
    public WorkloadInitResources getInitResources() {
        return initResources;
    }

    /**
     * Setter for initResources.<p>
     */
    public void setInitResources(WorkloadInitResources initResources) {
        this.initResources = initResources;
    }

    /**
     * Getter for systemLoad.<p>
     */
    public WorkloadSystemLoad getSystemLoad() {
        return systemLoad;
    }

    /**
     * Setter for systemLoad.<p>
     */
    public void setSystemLoad(WorkloadSystemLoad systemLoad) {
        this.systemLoad = systemLoad;
    }
}
