// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.typedef;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.util.Map;

@JsonSerialize
public class WorkloadReresolve {
    @JsonProperty("newFeatureFTypes")
    private Map<String, Integer> newFeatureFtypes;

    @JsonProperty("suppressedCandidateBuildersForReresolve")
    private Fixme suppressedCandidateBuildersForReresolve;

    @JsonProperty("suppressedScoredFeatureTypeForReresolve")
    private Fixme suppressedScoredFeatureTypeForReresolve;

    @JsonProperty("triggers")
    private WorkloadReresolveTriggers triggers;

    public WorkloadReresolve() {
    }

    /**
     * Getter for newFeatureFtypes.<p>
     * A dictionary of ...
     */
    public Map<String, Integer> getNewFeatureFtypes() {
        return newFeatureFtypes;
    }

    /**
     * Setter for newFeatureFtypes.<p>
     * A dictionary of ...
     */
    public void setNewFeatureFtypes(Map<String, Integer> newFeatureFtypes) {
        this.newFeatureFtypes = newFeatureFtypes;
    }

    /**
     * Getter for suppressedCandidateBuildersForReresolve.<p>
     */
    public Fixme getSuppressedCandidateBuildersForReresolve() {
        return suppressedCandidateBuildersForReresolve;
    }

    /**
     * Setter for suppressedCandidateBuildersForReresolve.<p>
     */
    public void setSuppressedCandidateBuildersForReresolve(Fixme suppressedCandidateBuildersForReresolve) {
        this.suppressedCandidateBuildersForReresolve = suppressedCandidateBuildersForReresolve;
    }

    /**
     * Getter for suppressedScoredFeatureTypeForReresolve.<p>
     */
    public Fixme getSuppressedScoredFeatureTypeForReresolve() {
        return suppressedScoredFeatureTypeForReresolve;
    }

    /**
     * Setter for suppressedScoredFeatureTypeForReresolve.<p>
     */
    public void setSuppressedScoredFeatureTypeForReresolve(Fixme suppressedScoredFeatureTypeForReresolve) {
        this.suppressedScoredFeatureTypeForReresolve = suppressedScoredFeatureTypeForReresolve;
    }

    /**
     * Getter for triggers.<p>
     */
    public WorkloadReresolveTriggers getTriggers() {
        return triggers;
    }

    /**
     * Setter for triggers.<p>
     */
    public void setTriggers(WorkloadReresolveTriggers triggers) {
        this.triggers = triggers;
    }
}
