// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.typedef;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public class XRecordSummary {
    @JsonValue
    private RecordSummary value;

    public XRecordSummary() {
    }

    @JsonCreator
    public XRecordSummary(RecordSummary value) {
        this.value = value;
    }

    public RecordSummary getValue() {
        return value;
    }

    public void setValue(RecordSummary value) {
        this.value = value;
    }
}
