// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Text.Json.Serialization;

namespace Senzing
{
    /// <summary>
    /// No description.
    /// </summary>
    public class CfgFbom
    {
        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("DERIVED")]
        public string Derived { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("DISPLAY_DELIM")]
        public string DisplayDelim { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("DISPLAY_LEVEL")]
        public int DisplayLevel { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("EXEC_ORDER")]
        public int ExecOrder { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("FELEM_ID")]
        public int FelemId { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("FTYPE_ID")]
        public int FtypeId { get; set; }
    }
}
