// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Senzing
{
    /// <summary>
    /// No description.
    /// </summary>
    [JsonConverter(typeof(DiagnosticFindEntitiesByFeatureIdsResponseJsonConverter))]
    public class DiagnosticFindEntitiesByFeatureIdsResponse
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public IList<DiagnosticFindEntitiesByFeatureIdsResponse0> Value { get; set; }
    }

    public class DiagnosticFindEntitiesByFeatureIdsResponseJsonConverter : JsonConverter<DiagnosticFindEntitiesByFeatureIdsResponse>
    {
        public override DiagnosticFindEntitiesByFeatureIdsResponse Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new DiagnosticFindEntitiesByFeatureIdsResponse { Value = JsonSerializer.Deserialize<IList<DiagnosticFindEntitiesByFeatureIdsResponse0>>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, DiagnosticFindEntitiesByFeatureIdsResponse value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<IList<DiagnosticFindEntitiesByFeatureIdsResponse0>>(writer, value.Value, options);
        }
    }
}
