// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Senzing
{
    /// <summary>
    /// No description.
    /// </summary>
    [JsonConverter(typeof(DiagnosticGetEntitySizeBreakdownResponseJsonConverter))]
    public class DiagnosticGetEntitySizeBreakdownResponse
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public AttributeCounters Value { get; set; }
    }

    public class DiagnosticGetEntitySizeBreakdownResponseJsonConverter : JsonConverter<DiagnosticGetEntitySizeBreakdownResponse>
    {
        public override DiagnosticGetEntitySizeBreakdownResponse Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new DiagnosticGetEntitySizeBreakdownResponse { Value = JsonSerializer.Deserialize<AttributeCounters>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, DiagnosticGetEntitySizeBreakdownResponse value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<AttributeCounters>(writer, value.Value, options);
        }
    }
}
