// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Text.Json.Serialization;

namespace Senzing
{
    /// <summary>
    /// No description.
    /// </summary>
    public class DiagnosticCheckDbperfResponse
    {
        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("insertTime")]
        public int InsertTime { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("numRecordsInserted")]
        public int NumRecordsInserted { get; set; }
    }
}
