// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Senzing
{
    /// <summary>
    /// No description.
    /// </summary>
    [JsonConverter(typeof(EngineFindNetworkByEntityIdresponseJsonConverter))]
    public class EngineFindNetworkByEntityIdresponse
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public Network Value { get; set; }
    }

    public class EngineFindNetworkByEntityIdresponseJsonConverter : JsonConverter<EngineFindNetworkByEntityIdresponse>
    {
        public override EngineFindNetworkByEntityIdresponse Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new EngineFindNetworkByEntityIdresponse { Value = JsonSerializer.Deserialize<Network>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, EngineFindNetworkByEntityIdresponse value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<Network>(writer, value.Value, options);
        }
    }
}
