// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Senzing
{
    /// <summary>
    /// No description.
    /// </summary>
    [JsonConverter(typeof(EngineGetVirtualEntityByRecordIdv2responseJsonConverter))]
    public class EngineGetVirtualEntityByRecordIdv2response
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public VirtualEntity Value { get; set; }
    }

    public class EngineGetVirtualEntityByRecordIdv2responseJsonConverter : JsonConverter<EngineGetVirtualEntityByRecordIdv2response>
    {
        public override EngineGetVirtualEntityByRecordIdv2response Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new EngineGetVirtualEntityByRecordIdv2response { Value = JsonSerializer.Deserialize<VirtualEntity>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, EngineGetVirtualEntityByRecordIdv2response value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<VirtualEntity>(writer, value.Value, options);
        }
    }
}
