// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Text.Json.Serialization;

namespace Senzing
{
    /// <summary>
    /// No description.
    /// </summary>
    public class EngineStatsResponseUnresolveTriggers
    {
        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("extensiveResolve")]
        public int ExtensiveResolve { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("normalResolve")]
        public int NormalResolve { get; set; }
    }
}
