// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Senzing
{
    /// <summary>
    /// No description.
    /// </summary>
    [JsonConverter(typeof(EngineFindInterestingEntitiesByRecordIdresponseJsonConverter))]
    public class EngineFindInterestingEntitiesByRecordIdresponse
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public Interesting Value { get; set; }
    }

    public class EngineFindInterestingEntitiesByRecordIdresponseJsonConverter : JsonConverter<EngineFindInterestingEntitiesByRecordIdresponse>
    {
        public override EngineFindInterestingEntitiesByRecordIdresponse Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new EngineFindInterestingEntitiesByRecordIdresponse { Value = JsonSerializer.Deserialize<Interesting>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, EngineFindInterestingEntitiesByRecordIdresponse value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<Interesting>(writer, value.Value, options);
        }
    }
}
