// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Senzing
{
    public class EngineStatsResponseWorkloadSystemResourcesCurrResource
    {
        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("activeThreads")]
        public int ActiveThreads { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("availableMemory")]
        public string AvailableMemory { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("systemLoad")]
        public IList<EngineStatsResponseWorkloadSystemResourcesCurrResourceSystemLoad> SystemLoad { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("workerThreads")]
        public int WorkerThreads { get; set; }
    }
}
