// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Text.Json.Serialization;

namespace Senzing
{
    public class FeaturesXxx
    {
        [JsonPropertyName("ACCOUNT_DOMAIN")]
        public FeaturesForAttribute AccountDomain { get; set; }

        [JsonPropertyName("ACCOUNT_NUMBER")]
        public FeaturesForAttribute AccountNumber { get; set; }

        [JsonPropertyName("ACCT_NUM")]
        public FeaturesForAttribute AcctNum { get; set; }

        [JsonPropertyName("ADDRESS")]
        public FeaturesForAttribute Address { get; set; }

        [JsonPropertyName("ADDRESS_LIST")]
        public FeaturesForAttribute AddressList { get; set; }

        [JsonPropertyName("ADDR_FULL")]
        public FeaturesForAttribute AddrFull { get; set; }

        [JsonPropertyName("ADDR_KEY")]
        public FeaturesForAttribute AddrKey { get; set; }

        [JsonPropertyName("CELL_PHONE_NUMBER")]
        public FeaturesForAttribute CellPhoneNumber { get; set; }

        [JsonPropertyName("CITIZENSHIP")]
        public FeaturesForAttribute Citizenship { get; set; }

        [JsonPropertyName("COUNTRY_OF_ASSOCIATION")]
        public FeaturesForAttribute CountryOfAssociation { get; set; }

        [JsonPropertyName("DATA_SOURCE")]
        public FeaturesForAttribute DataSource { get; set; }

        [JsonPropertyName("DATE_OF_BIRTH")]
        public FeaturesForAttribute DateOfBirth { get; set; }

        [JsonPropertyName("DATE_OF_DEATH")]
        public FeaturesForAttribute DateOfDeath { get; set; }

        [JsonPropertyName("DOB")]
        public FeaturesForAttribute Dob { get; set; }

        [JsonPropertyName("DOD")]
        public FeaturesForAttribute Dod { get; set; }

        [JsonPropertyName("DRIVERS_LICENSE_NUMBER")]
        public FeaturesForAttribute DriversLicenseNumber { get; set; }

        [JsonPropertyName("DRIVERS_LICENSE_STATE")]
        public FeaturesForAttribute DriversLicenseState { get; set; }

        [JsonPropertyName("DRLIC")]
        public FeaturesForAttribute Drlic { get; set; }

        [JsonPropertyName("DUNS_NUMBER")]
        public FeaturesForAttribute DunsNumber { get; set; }

        [JsonPropertyName("EMAIL")]
        public FeaturesForAttribute Email { get; set; }

        [JsonPropertyName("EMAIL_ADDRESS")]
        public FeaturesForAttribute EmailAddress { get; set; }

        [JsonPropertyName("EMAIL_KEY")]
        public FeaturesForAttribute EmailKey { get; set; }

        [JsonPropertyName("EMPLOYER_NAME")]
        public FeaturesForAttribute EmployerName { get; set; }

        [JsonPropertyName("ENTITY_TYPE")]
        public FeaturesForAttribute EntityType { get; set; }

        [JsonPropertyName("FACEBOOK")]
        public FeaturesForAttribute Facebook { get; set; }

        [JsonPropertyName("GENDER")]
        public FeaturesForAttribute Gender { get; set; }

        [JsonPropertyName("GROUP_ASSN_ID_NUMBER")]
        public FeaturesForAttribute GroupAssnIdNumber { get; set; }

        [JsonPropertyName("GROUP_ASSN_ID_TYPE")]
        public FeaturesForAttribute GroupAssnIdType { get; set; }

        [JsonPropertyName("GROUP_ASSOCIATION_ORG_NAME")]
        public FeaturesForAttribute GroupAssociationOrgName { get; set; }

        [JsonPropertyName("GROUP_ASSOCIATION_TYPE")]
        public FeaturesForAttribute GroupAssociationType { get; set; }

        [JsonPropertyName("ID_KEY")]
        public FeaturesForAttribute IdKey { get; set; }

        [JsonPropertyName("INSTAGRAM")]
        public FeaturesForAttribute Instagram { get; set; }

        [JsonPropertyName("LEI_NUMBER")]
        public FeaturesForAttribute LeiNumber { get; set; }

        [JsonPropertyName("LINKEDIN")]
        public FeaturesForAttribute Linkedin { get; set; }

        [JsonPropertyName("LOAD_ID")]
        public FeaturesForAttribute LoadId { get; set; }

        [JsonPropertyName("LOGIN_ID")]
        public FeaturesForAttribute LoginId { get; set; }

        [JsonPropertyName("NAME")]
        public FeaturesForAttribute Name { get; set; }

        [JsonPropertyName("NAME_FULL")]
        public FeaturesForAttribute NameFull { get; set; }

        [JsonPropertyName("NAME_KEY")]
        public FeaturesForAttribute NameKey { get; set; }

        [JsonPropertyName("NAME_LIST")]
        public FeaturesForAttribute NameList { get; set; }

        [JsonPropertyName("NATIONALITY")]
        public FeaturesForAttribute Nationality { get; set; }

        [JsonPropertyName("NATIONAL_ID")]
        public FeaturesForAttribute NationalId { get; set; }

        [JsonPropertyName("NATIONAL_ID_COUNTRY")]
        public FeaturesForAttribute NationalIdCountry { get; set; }

        [JsonPropertyName("NATIONAL_ID_NUMBER")]
        public FeaturesForAttribute NationalIdNumber { get; set; }

        [JsonPropertyName("NIN_COUNTRY")]
        public FeaturesForAttribute NinCountry { get; set; }

        [JsonPropertyName("NIN_NUMBER")]
        public FeaturesForAttribute NinNumber { get; set; }

        [JsonPropertyName("NPI_NUMBER")]
        public FeaturesForAttribute NpiNumber { get; set; }

        [JsonPropertyName("OTHER_ID_COUNTRY")]
        public FeaturesForAttribute OtherIdCountry { get; set; }

        [JsonPropertyName("OTHER_ID_NUMBER")]
        public FeaturesForAttribute OtherIdNumber { get; set; }

        [JsonPropertyName("OTHER_ID_TYPE")]
        public FeaturesForAttribute OtherIdType { get; set; }

        [JsonPropertyName("PASSPORT")]
        public FeaturesForAttribute Passport { get; set; }

        [JsonPropertyName("PASSPORTS")]
        public FeaturesForAttribute Passports { get; set; }

        [JsonPropertyName("PASSPORT_COUNTRY")]
        public FeaturesForAttribute PassportCountry { get; set; }

        [JsonPropertyName("PASSPORT_NUMBER")]
        public FeaturesForAttribute PassportNumber { get; set; }

        [JsonPropertyName("PHONE")]
        public FeaturesForAttribute Phone { get; set; }

        [JsonPropertyName("PHONES")]
        public FeaturesForAttribute Phones { get; set; }

        [JsonPropertyName("PHONE_KEY")]
        public FeaturesForAttribute PhoneKey { get; set; }

        [JsonPropertyName("PLACE_OF_BIRTH")]
        public FeaturesForAttribute PlaceOfBirth { get; set; }

        [JsonPropertyName("PRIMARY_NAME_FIRST")]
        public FeaturesForAttribute PrimaryNameFirst { get; set; }

        [JsonPropertyName("PRIMARY_NAME_LAST")]
        public FeaturesForAttribute PrimaryNameLast { get; set; }

        [JsonPropertyName("PRIMARY_NAME_MIDDLE")]
        public FeaturesForAttribute PrimaryNameMiddle { get; set; }

        [JsonPropertyName("PRIMARY_NAME_ORG")]
        public FeaturesForAttribute PrimaryNameOrg { get; set; }

        [JsonPropertyName("PRIMARY_NAME_PREFIX")]
        public FeaturesForAttribute PrimaryNamePrefix { get; set; }

        [JsonPropertyName("PRIMARY_NAME_SUFFIX")]
        public FeaturesForAttribute PrimaryNameSuffix { get; set; }

        [JsonPropertyName("PRIMARY_PHONE_NUMBER")]
        public FeaturesForAttribute PrimaryPhoneNumber { get; set; }

        [JsonPropertyName("RECORD_TYPE")]
        public FeaturesForAttribute RecordType { get; set; }

        [JsonPropertyName("REGISTRATION_COUNTRY")]
        public FeaturesForAttribute RegistrationCountry { get; set; }

        [JsonPropertyName("REGISTRATION_DATE")]
        public FeaturesForAttribute RegistrationDate { get; set; }

        [JsonPropertyName("REL_ANCHOR")]
        public FeaturesForAttribute RelAnchor { get; set; }

        [JsonPropertyName("REL_ANCHOR_DOMAIN")]
        public FeaturesForAttribute RelAnchorDomain { get; set; }

        [JsonPropertyName("REL_ANCHOR_KEY")]
        public FeaturesForAttribute RelAnchorKey { get; set; }

        [JsonPropertyName("REL_LINK")]
        public FeaturesForAttribute RelLink { get; set; }

        [JsonPropertyName("REL_POINTER")]
        public FeaturesForAttribute RelPointer { get; set; }

        [JsonPropertyName("REL_POINTER_DOMAIN")]
        public FeaturesForAttribute RelPointerDomain { get; set; }

        [JsonPropertyName("REL_POINTER_KEY")]
        public FeaturesForAttribute RelPointerKey { get; set; }

        [JsonPropertyName("REL_POINTER_ROLE")]
        public FeaturesForAttribute RelPointerRole { get; set; }

        [JsonPropertyName("SIGNAL")]
        public FeaturesForAttribute Signal { get; set; }

        [JsonPropertyName("SKYPE")]
        public FeaturesForAttribute Skype { get; set; }

        [JsonPropertyName("SOCIAL_HANDLE")]
        public FeaturesForAttribute SocialHandle { get; set; }

        [JsonPropertyName("SOCIAL_NETWORK")]
        public FeaturesForAttribute SocialNetwork { get; set; }

        [JsonPropertyName("SOURCE_ID")]
        public FeaturesForAttribute SourceId { get; set; }

        [JsonPropertyName("SSN")]
        public FeaturesForAttribute Ssn { get; set; }

        [JsonPropertyName("SSN_LAST4")]
        public FeaturesForAttribute SsnLast4 { get; set; }

        [JsonPropertyName("SSN_NUMBER")]
        public FeaturesForAttribute SsnNumber { get; set; }

        [JsonPropertyName("TANGO")]
        public FeaturesForAttribute Tango { get; set; }

        [JsonPropertyName("TAX_ID_COUNTRY")]
        public FeaturesForAttribute TaxIdCountry { get; set; }

        [JsonPropertyName("TAX_ID_NUMBER")]
        public FeaturesForAttribute TaxIdNumber { get; set; }

        [JsonPropertyName("TAX_ID_TYPE")]
        public FeaturesForAttribute TaxIdType { get; set; }

        [JsonPropertyName("TELEGRAM")]
        public FeaturesForAttribute Telegram { get; set; }

        [JsonPropertyName("TRUSTED_ID_NUMBER")]
        public FeaturesForAttribute TrustedIdNumber { get; set; }

        [JsonPropertyName("TRUSTED_ID_TYPE")]
        public FeaturesForAttribute TrustedIdType { get; set; }

        [JsonPropertyName("TWITTER")]
        public FeaturesForAttribute Twitter { get; set; }

        [JsonPropertyName("VIBER")]
        public FeaturesForAttribute Viber { get; set; }

        [JsonPropertyName("WEBSITE_ADDRESS")]
        public FeaturesForAttribute WebsiteAddress { get; set; }

        [JsonPropertyName("WECHAT")]
        public FeaturesForAttribute Wechat { get; set; }

        [JsonPropertyName("WHATSAPP")]
        public FeaturesForAttribute Whatsapp { get; set; }

        [JsonPropertyName("WORK_PHONE_NUMBER")]
        public FeaturesForAttribute WorkPhoneNumber { get; set; }

        [JsonPropertyName("ZOOMROOM")]
        public FeaturesForAttribute Zoomroom { get; set; }
    }
}
