// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Text.Json.Serialization;

namespace Senzing
{
    public class G2configmgrGetConfigListResponse
    {
        [JsonPropertyName("CONFIGS")]
        public Configs Configs { get; set; }
    }
}
