// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Text.Json.Serialization;

namespace Senzing
{
    public class G2engineExportConfigAndConfigIdResponse
    {
        [JsonPropertyName("G2_CONFIG")]
        public G2config G2Config { get; set; }
    }
}
