// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Text.Json.Serialization;

namespace Senzing
{
    public class G2engineStatsResponseDuration
    {
        [JsonPropertyName("PATTERN")]
        public string Pattern { get; set; }

        [JsonPropertyName("TYPE")]
        public string Type_ { get; set; }
    }
}
