// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Senzing
{
    [JsonConverter(typeof(G2engineWhyEntitiesResponseJsonConverter))]
    public class G2engineWhyEntitiesResponse
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public WhyEntities Value { get; set; }
    }

    public class G2engineWhyEntitiesResponseJsonConverter : JsonConverter<G2engineWhyEntitiesResponse>
    {
        public override G2engineWhyEntitiesResponse Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new G2engineWhyEntitiesResponse { Value = JsonSerializer.Deserialize<WhyEntities>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, G2engineWhyEntitiesResponse value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<WhyEntities>(writer, value.Value, options);
        }
    }
}
