// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Senzing
{
    [JsonConverter(typeof(G2productVersionResponseJsonConverter))]
    public class G2productVersionResponse
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public ProductVersion Value { get; set; }
    }

    public class G2productVersionResponseJsonConverter : JsonConverter<G2productVersionResponse>
    {
        public override G2productVersionResponse Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new G2productVersionResponse { Value = JsonSerializer.Deserialize<ProductVersion>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, G2productVersionResponse value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<ProductVersion>(writer, value.Value, options);
        }
    }
}
