// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Senzing
{
    /// <summary>
    /// No description.
    /// </summary>
    public class JsonData
    {
        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("ACCOUNT_DOMAIN")]
        public string AccountDomain { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("ACCOUNT_NUMBER")]
        public string AccountNumber { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("ACCT_NUM")]
        public IList<JsonDataAcctNum> AcctNum { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("ADDRESS")]
        public string Address { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("ADDRESS_LIST")]
        public Addresses AddressList { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("ADDR_FULL")]
        public string AddrFull { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("ADDR_KEY")]
        public string AddrKey { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("CELL_PHONE_NUMBER")]
        public string CellPhoneNumber { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("CITIZENSHIP")]
        public string Citizenship { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("COUNTRY_OF_ASSOCIATION")]
        public string CountryOfAssociation { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("DATA_SOURCE")]
        public string DataSource { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("DATE_OF_BIRTH")]
        public string DateOfBirth { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("DATE_OF_DEATH")]
        public string DateOfDeath { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("DOB")]
        public string Dob { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("DOD")]
        public string Dod { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("DRIVERS_LICENSE_NUMBER")]
        public string DriversLicenseNumber { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("DRIVERS_LICENSE_STATE")]
        public string DriversLicenseState { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("DRLIC")]
        public string Drlic { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("DSRC_ACTION")]
        public string DsrcAction { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("DSRC_CODE")]
        public string DsrcCode { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("DUNS_NUMBER")]
        public string DunsNumber { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("EMAIL")]
        public string Email { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("EMAIL_ADDRESS")]
        public string EmailAddress { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("EMAIL_KEY")]
        public string EmailKey { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("EMPLOYER_NAME")]
        public string EmployerName { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("ENTITY_TYPE")]
        public string EntityType { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("ENT_SRC_DESC")]
        public string EntSrcDesc { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("ENT_SRC_KEY")]
        public string EntSrcKey { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("ETYPE_CODE")]
        public string EtypeCode { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("FACEBOOK")]
        public string Facebook { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("GENDER")]
        public string Gender { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("GROUP_ASSN_ID_NUMBER")]
        public string GroupAssnIdNumber { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("GROUP_ASSN_ID_TYPE")]
        public string GroupAssnIdType { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("GROUP_ASSOCIATION_ORG_NAME")]
        public string GroupAssociationOrgName { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("GROUP_ASSOCIATION_TYPE")]
        public string GroupAssociationType { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("ID_KEY")]
        public string IdKey { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("INSTAGRAM")]
        public string Instagram { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("LEI_NUMBER")]
        public string LeiNumber { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("LINKEDIN")]
        public string Linkedin { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("LOAD_ID")]
        public string LoadId { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("LOGIN_ID")]
        public string LoginId { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("NAME")]
        public Names Name { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("NAME_FULL")]
        public string NameFull { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("NAME_KEY")]
        public string NameKey { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("NAME_LIST")]
        public Names NameList { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("NATIONALITY")]
        public string Nationality { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("NATIONAL_ID")]
        public string NationalId { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("NATIONAL_ID_COUNTRY")]
        public string NationalIdCountry { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("NATIONAL_ID_NUMBER")]
        public string NationalIdNumber { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("NIN_COUNTRY")]
        public string NinCountry { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("NIN_NUMBER")]
        public string NinNumber { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("NPI_NUMBER")]
        public string NpiNumber { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("OBS_SRC_KEY")]
        public string ObsSrcKey { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("OTHER_ID_COUNTRY")]
        public string OtherIdCountry { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("OTHER_ID_NUMBER")]
        public string OtherIdNumber { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("OTHER_ID_TYPE")]
        public string OtherIdType { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("PASSPORT")]
        public string Passport { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("PASSPORTS")]
        public Passports Passports { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("PASSPORT_COUNTRY")]
        public string PassportCountry { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("PASSPORT_NUMBER")]
        public string PassportNumber { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("PHONE")]
        public string Phone { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("PHONES")]
        public Phones Phones { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("PHONE_KEY")]
        public string PhoneKey { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("PLACE_OF_BIRTH")]
        public string PlaceOfBirth { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("PRIMARY_NAME_FIRST")]
        public string PrimaryNameFirst { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("PRIMARY_NAME_LAST")]
        public string PrimaryNameLast { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("PRIMARY_NAME_MIDDLE")]
        public string PrimaryNameMiddle { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("PRIMARY_NAME_ORG")]
        public string PrimaryNameOrg { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("PRIMARY_NAME_PREFIX")]
        public string PrimaryNamePrefix { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("PRIMARY_NAME_SUFFIX")]
        public string PrimaryNameSuffix { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("PRIMARY_PHONE_NUMBER")]
        public string PrimaryPhoneNumber { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("RECORD_ID")]
        public string RecordId { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("RECORD_TYPE")]
        public string RecordType { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("REGISTRATION_COUNTRY")]
        public string RegistrationCountry { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("REGISTRATION_DATE")]
        public string RegistrationDate { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("RELATIONSHIPS")]
        public Relationships Relationships { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("REL_ANCHOR")]
        public string RelAnchor { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("REL_ANCHOR_DOMAIN")]
        public string RelAnchorDomain { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("REL_ANCHOR_KEY")]
        public string RelAnchorKey { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("REL_LINK")]
        public string RelLink { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("REL_POINTER")]
        public string RelPointer { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("REL_POINTER_DOMAIN")]
        public string RelPointerDomain { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("REL_POINTER_KEY")]
        public string RelPointerKey { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("REL_POINTER_ROLE")]
        public string RelPointerRole { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("SIGNAL")]
        public string Signal { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("SKYPE")]
        public string Skype { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("SOCIAL_HANDLE")]
        public string SocialHandle { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("SOCIAL_NETWORK")]
        public string SocialNetwork { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("SOURCE_ID")]
        public string SourceId { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("SSN")]
        public IList<JsonDataSsn> Ssn { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("SSN_LAST4")]
        public IList<JsonDataSsnLast4> SsnLast4 { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("SSN_NUMBER")]
        public string SsnNumber { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("TANGO")]
        public string Tango { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("TAX_ID_COUNTRY")]
        public string TaxIdCountry { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("TAX_ID_NUMBER")]
        public string TaxIdNumber { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("TAX_ID_TYPE")]
        public string TaxIdType { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("TELEGRAM")]
        public string Telegram { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("TRUSTED_ID_NUMBER")]
        public string TrustedIdNumber { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("TRUSTED_ID_TYPE")]
        public string TrustedIdType { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("TWITTER")]
        public string Twitter { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("VIBER")]
        public string Viber { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("WEBSITE_ADDRESS")]
        public string WebsiteAddress { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("WECHAT")]
        public string Wechat { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("WHATSAPP")]
        public string Whatsapp { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("WORK_PHONE_NUMBER")]
        public string WorkPhoneNumber { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("ZOOMROOM")]
        public string Zoomroom { get; set; }

        /// <summary>
        /// No description.
        /// </summary>
        [JsonPropertyName("name")]
        public Names Name0 { get; set; }
    }
}
