// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Senzing
{
    [JsonConverter(typeof(PhonesJsonConverter))]
    public class Phones
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public IList<Phone> Value { get; set; }
    }

    public class PhonesJsonConverter : JsonConverter<Phones>
    {
        public override Phones Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new Phones { Value = JsonSerializer.Deserialize<IList<Phone>>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, Phones value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<IList<Phone>>(writer, value.Value, options);
        }
    }
}
