// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Text.Json.Serialization;

namespace Senzing
{
    public class RecordFeatures
    {
        [JsonPropertyName("LIB_FEAT_ID")]
        public int LibFeatId { get; set; }

        [JsonPropertyName("USAGE_TYPE")]
        public string UsageType { get; set; }
    }
}
