// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Senzing
{
    [JsonConverter(typeof(SzConfigExportConfigResponseJsonConverter))]
    public class SzConfigExportConfigResponse
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public ExportConfig Value { get; set; }
    }

    public class SzConfigExportConfigResponseJsonConverter : JsonConverter<SzConfigExportConfigResponse>
    {
        public override SzConfigExportConfigResponse Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new SzConfigExportConfigResponse { Value = JsonSerializer.Deserialize<ExportConfig>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, SzConfigExportConfigResponse value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<ExportConfig>(writer, value.Value, options);
        }
    }
}
