// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Senzing
{
    [JsonConverter(typeof(SzEngineFindPathByRecordIdAvoidRecordKeysJsonConverter))]
    public class SzEngineFindPathByRecordIdAvoidRecordKeys
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public Fixme Value { get; set; }
    }

    public class SzEngineFindPathByRecordIdAvoidRecordKeysJsonConverter : JsonConverter<SzEngineFindPathByRecordIdAvoidRecordKeys>
    {
        public override SzEngineFindPathByRecordIdAvoidRecordKeys Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new SzEngineFindPathByRecordIdAvoidRecordKeys { Value = JsonSerializer.Deserialize<Fixme>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, SzEngineFindPathByRecordIdAvoidRecordKeys value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<Fixme>(writer, value.Value, options);
        }
    }
}
