// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.schema;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * No description.
 */
@JsonSerialize
public class CfgAttr {
    @JsonProperty("ADVANCED")
    private String advanced;

    @JsonProperty("ATTR_CLASS")
    private String attrClass;

    @JsonProperty("ATTR_CODE")
    private String attrCode;

    @JsonProperty("ATTR_ID")
    private Integer attrId;

    @JsonProperty("DEFAULT_VALUE")
    private String defaultValue;

    @JsonProperty("FELEM_CODE")
    private String felemCode;

    @JsonProperty("FELEM_REQ")
    private String felemReq;

    @JsonProperty("FTYPE_CODE")
    private String ftypeCode;

    @JsonProperty("INTERNAL")
    private String internal;

    public CfgAttr() {
    }

    /**
     * Getter for advanced.<p>
     * No description.
     */
    public String getAdvanced() {
        return advanced;
    }

    /**
     * Setter for advanced.<p>
     * No description.
     */
    public void setAdvanced(String advanced) {
        this.advanced = advanced;
    }

    /**
     * Getter for attrClass.<p>
     * No description.
     */
    public String getAttrClass() {
        return attrClass;
    }

    /**
     * Setter for attrClass.<p>
     * No description.
     */
    public void setAttrClass(String attrClass) {
        this.attrClass = attrClass;
    }

    /**
     * Getter for attrCode.<p>
     * No description.
     */
    public String getAttrCode() {
        return attrCode;
    }

    /**
     * Setter for attrCode.<p>
     * No description.
     */
    public void setAttrCode(String attrCode) {
        this.attrCode = attrCode;
    }

    /**
     * Getter for attrId.<p>
     * No description.
     */
    public Integer getAttrId() {
        return attrId;
    }

    /**
     * Setter for attrId.<p>
     * No description.
     */
    public void setAttrId(Integer attrId) {
        this.attrId = attrId;
    }

    /**
     * Getter for defaultValue.<p>
     * No description.
     */
    public String getDefaultValue() {
        return defaultValue;
    }

    /**
     * Setter for defaultValue.<p>
     * No description.
     */
    public void setDefaultValue(String defaultValue) {
        this.defaultValue = defaultValue;
    }

    /**
     * Getter for felemCode.<p>
     * No description.
     */
    public String getFelemCode() {
        return felemCode;
    }

    /**
     * Setter for felemCode.<p>
     * No description.
     */
    public void setFelemCode(String felemCode) {
        this.felemCode = felemCode;
    }

    /**
     * Getter for felemReq.<p>
     * No description.
     */
    public String getFelemReq() {
        return felemReq;
    }

    /**
     * Setter for felemReq.<p>
     * No description.
     */
    public void setFelemReq(String felemReq) {
        this.felemReq = felemReq;
    }

    /**
     * Getter for ftypeCode.<p>
     * No description.
     */
    public String getFtypeCode() {
        return ftypeCode;
    }

    /**
     * Setter for ftypeCode.<p>
     * No description.
     */
    public void setFtypeCode(String ftypeCode) {
        this.ftypeCode = ftypeCode;
    }

    /**
     * Getter for internal.<p>
     * No description.
     */
    public String getInternal() {
        return internal;
    }

    /**
     * Setter for internal.<p>
     * No description.
     */
    public void setInternal(String internal) {
        this.internal = internal;
    }
}
