// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.schema;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

@JsonSerialize
public class CfgDsrcInterest {
    @JsonProperty("DSRC_ID")
    private Integer dsrcId;

    @JsonProperty("INTEREST_FLAG")
    private String interestFlag;

    @JsonProperty("MAX_DEGREE")
    private Integer maxDegree;

    public CfgDsrcInterest() {
    }

    /**
     * Getter for dsrcId.<p>
     */
    public Integer getDsrcId() {
        return dsrcId;
    }

    /**
     * Setter for dsrcId.<p>
     */
    public void setDsrcId(Integer dsrcId) {
        this.dsrcId = dsrcId;
    }

    /**
     * Getter for interestFlag.<p>
     */
    public String getInterestFlag() {
        return interestFlag;
    }

    /**
     * Setter for interestFlag.<p>
     */
    public void setInterestFlag(String interestFlag) {
        this.interestFlag = interestFlag;
    }

    /**
     * Getter for maxDegree.<p>
     */
    public Integer getMaxDegree() {
        return maxDegree;
    }

    /**
     * Setter for maxDegree.<p>
     */
    public void setMaxDegree(Integer maxDegree) {
        this.maxDegree = maxDegree;
    }
}
