// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.schema;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.util.List;

@JsonSerialize
public class Configs {
    @JsonProperty("CONFIGS")
    private List<Config> configs;

    public Configs() {
    }

    /**
     * Getter for configs.<p>
     */
    public List<Config> getConfigRepository() {
        return configs;
    }

    /**
     * Setter for configs.<p>
     */
    public void setConfigs(List<Config> configs) {
        this.configs = configs;
    }
}
