// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.schema;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * No description.
 */
@JsonSerialize
public class ConfigmgrGetConfigListResponse {
    @JsonProperty("CONFIGS")
    private Configs configs;

    public ConfigmgrGetConfigListResponse() {
    }

    /**
     * Getter for configs.<p>
     * No description.
     */
    public Configs getConfigs() {
        return configs;
    }

    /**
     * Setter for configs.<p>
     * No description.
     */
    public void setConfigs(Configs configs) {
        this.configs = configs;
    }
}
