// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.schema;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

@JsonSerialize
public class Datastore {
    @JsonProperty("id")
    private String id;

    @JsonProperty("location")
    private String location;

    @JsonProperty("type")
    private String type;

    public Datastore() {
    }

    /**
     * Getter for id.<p>
     */
    public String getId() {
        return id;
    }

    /**
     * Setter for id.<p>
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for location.<p>
     */
    public String getLocation() {
        return location;
    }

    /**
     * Setter for location.<p>
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * Getter for type.<p>
     */
    public String getType() {
        return type;
    }

    /**
     * Setter for type.<p>
     */
    public void setType(String type) {
        this.type = type;
    }
}
