// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.schema;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public class EngineWhyRecordsResponse {
    @JsonValue
    private WhyRecords value;

    public EngineWhyRecordsResponse() {
    }

    @JsonCreator
    public EngineWhyRecordsResponse(WhyRecords value) {
        this.value = value;
    }

    public WhyRecords getValue() {
        return value;
    }

    public void setValue(WhyRecords value) {
        this.value = value;
    }
}
