// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.schema;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * No description.
 */
@JsonSerialize
public class EngineStatsResponseReresolveTriggers {
    @JsonProperty("abortRetry")
    private Integer abortRetry;

    @JsonProperty("multipleResolvableCandidates")
    private Integer multipleResolvableCandidates;

    @JsonProperty("resolveNewFeatures")
    private Integer resolveNewFeatures;

    @JsonProperty("unresolveMovement")
    private Integer unresolveMovement;

    public EngineStatsResponseReresolveTriggers() {
    }

    /**
     * Getter for abortRetry.<p>
     * No description.
     */
    public Integer getAbortRetry() {
        return abortRetry;
    }

    /**
     * Setter for abortRetry.<p>
     * No description.
     */
    public void setAbortRetry(Integer abortRetry) {
        this.abortRetry = abortRetry;
    }

    /**
     * Getter for multipleResolvableCandidates.<p>
     * No description.
     */
    public Integer getMultipleResolvableCandidates() {
        return multipleResolvableCandidates;
    }

    /**
     * Setter for multipleResolvableCandidates.<p>
     * No description.
     */
    public void setMultipleResolvableCandidates(Integer multipleResolvableCandidates) {
        this.multipleResolvableCandidates = multipleResolvableCandidates;
    }

    /**
     * Getter for resolveNewFeatures.<p>
     * No description.
     */
    public Integer getResolveNewFeatures() {
        return resolveNewFeatures;
    }

    /**
     * Setter for resolveNewFeatures.<p>
     * No description.
     */
    public void setResolveNewFeatures(Integer resolveNewFeatures) {
        this.resolveNewFeatures = resolveNewFeatures;
    }

    /**
     * Getter for unresolveMovement.<p>
     * No description.
     */
    public Integer getUnresolveMovement() {
        return unresolveMovement;
    }

    /**
     * Setter for unresolveMovement.<p>
     * No description.
     */
    public void setUnresolveMovement(Integer unresolveMovement) {
        this.unresolveMovement = unresolveMovement;
    }
}
