// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.schema;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

@JsonSerialize
public class EngineCheckRecordResponseCheckRecordResponse {
    @JsonProperty("CANDIDATE_MATCH")
    private String candidateMatch;

    @JsonProperty("DSRC_CODE")
    private String dsrcCode;

    @JsonProperty("ERRULE_CODE")
    private String erruleCode;

    @JsonProperty("ERRULE_ID")
    private Integer erruleId;

    @JsonProperty("MATCH_KEY")
    private String matchKey;

    @JsonProperty("MATCH_LEVEL")
    private Integer matchLevel;

    @JsonProperty("MATCH_LEVEL_CODE")
    private String matchLevelCode;

    @JsonProperty("NON_GENERIC_CANDIDATE_MATCH")
    private String nonGenericCandidateMatch;

    @JsonProperty("RECORD_ID")
    private String recordId;

    public EngineCheckRecordResponseCheckRecordResponse() {
    }

    /**
     * Getter for candidateMatch.<p>
     */
    public String getCandidateMatch() {
        return candidateMatch;
    }

    /**
     * Setter for candidateMatch.<p>
     */
    public void setCandidateMatch(String candidateMatch) {
        this.candidateMatch = candidateMatch;
    }

    /**
     * Getter for dsrcCode.<p>
     */
    public String getDsrcCode() {
        return dsrcCode;
    }

    /**
     * Setter for dsrcCode.<p>
     */
    public void setDsrcCode(String dsrcCode) {
        this.dsrcCode = dsrcCode;
    }

    /**
     * Getter for erruleCode.<p>
     */
    public String getErruleCode() {
        return erruleCode;
    }

    /**
     * Setter for erruleCode.<p>
     */
    public void setErruleCode(String erruleCode) {
        this.erruleCode = erruleCode;
    }

    /**
     * Getter for erruleId.<p>
     */
    public Integer getErruleId() {
        return erruleId;
    }

    /**
     * Setter for erruleId.<p>
     */
    public void setErruleId(Integer erruleId) {
        this.erruleId = erruleId;
    }

    /**
     * Getter for matchKey.<p>
     */
    public String getMatchKey() {
        return matchKey;
    }

    /**
     * Setter for matchKey.<p>
     */
    public void setMatchKey(String matchKey) {
        this.matchKey = matchKey;
    }

    /**
     * Getter for matchLevel.<p>
     */
    public Integer getMatchLevel() {
        return matchLevel;
    }

    /**
     * Setter for matchLevel.<p>
     */
    public void setMatchLevel(Integer matchLevel) {
        this.matchLevel = matchLevel;
    }

    /**
     * Getter for matchLevelCode.<p>
     */
    public String getMatchLevelCode() {
        return matchLevelCode;
    }

    /**
     * Setter for matchLevelCode.<p>
     */
    public void setMatchLevelCode(String matchLevelCode) {
        this.matchLevelCode = matchLevelCode;
    }

    /**
     * Getter for nonGenericCandidateMatch.<p>
     */
    public String getNonGenericCandidateMatch() {
        return nonGenericCandidateMatch;
    }

    /**
     * Setter for nonGenericCandidateMatch.<p>
     */
    public void setNonGenericCandidateMatch(String nonGenericCandidateMatch) {
        this.nonGenericCandidateMatch = nonGenericCandidateMatch;
    }

    /**
     * Getter for recordId.<p>
     */
    public String getRecordId() {
        return recordId;
    }

    /**
     * Setter for recordId.<p>
     */
    public void setRecordId(String recordId) {
        this.recordId = recordId;
    }
}
