// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.schema;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * No description.
 */
public class EngineWhyEntitiesV2response {
    @JsonValue
    private WhyEntities value;

    public EngineWhyEntitiesV2response() {
    }

    @JsonCreator
    public EngineWhyEntitiesV2response(WhyEntities value) {
        this.value = value;
    }

    public WhyEntities getValue() {
        return value;
    }

    public void setValue(WhyEntities value) {
        this.value = value;
    }
}
