// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.schema;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.List;

public class Entities {
    @JsonValue
    private List<Entity> value;

    public Entities() {
    }

    @JsonCreator
    public Entities(List<Entity> value) {
        this.value = value;
    }

    public List<Entity> getValue() {
        return value;
    }

    public void setValue(List<Entity> value) {
        this.value = value;
    }
}
