// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.schema;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

@JsonSerialize
public class FeatureScoreForAttribute {
    @JsonProperty("CANDIDATE_FEAT")
    private String candidateFeat;

    @JsonProperty("CANDIDATE_FEAT_ID")
    private Integer candidateFeatId;

    @JsonProperty("CANDIDATE_FEAT_USAGE_TYPE")
    private String candidateFeatUsageType;

    @JsonProperty("FULL_SCORE")
    private Integer fullScore;

    @JsonProperty("GENERATION_MATCH")
    private Integer generationMatch;

    @JsonProperty("GNR_FN")
    private Integer gnrFn;

    @JsonProperty("GNR_GN")
    private Integer gnrGn;

    @JsonProperty("GNR_ON")
    private Integer gnrOn;

    @JsonProperty("GNR_SN")
    private Integer gnrSn;

    @JsonProperty("INBOUND_FEAT")
    private String inboundFeat;

    @JsonProperty("INBOUND_FEAT_ID")
    private Integer inboundFeatId;

    @JsonProperty("INBOUND_FEAT_USAGE_TYPE")
    private String inboundFeatUsageType;

    @JsonProperty("SCORE_BEHAVIOR")
    private String scoreBehavior;

    @JsonProperty("SCORE_BUCKET")
    private String scoreBucket;

    public FeatureScoreForAttribute() {
    }

    /**
     * Getter for candidateFeat.<p>
     */
    public String getCandidateFeat() {
        return candidateFeat;
    }

    /**
     * Setter for candidateFeat.<p>
     */
    public void setCandidateFeat(String candidateFeat) {
        this.candidateFeat = candidateFeat;
    }

    /**
     * Getter for candidateFeatId.<p>
     */
    public Integer getCandidateFeatId() {
        return candidateFeatId;
    }

    /**
     * Setter for candidateFeatId.<p>
     */
    public void setCandidateFeatId(Integer candidateFeatId) {
        this.candidateFeatId = candidateFeatId;
    }

    /**
     * Getter for candidateFeatUsageType.<p>
     */
    public String getCandidateFeatUsageType() {
        return candidateFeatUsageType;
    }

    /**
     * Setter for candidateFeatUsageType.<p>
     */
    public void setCandidateFeatUsageType(String candidateFeatUsageType) {
        this.candidateFeatUsageType = candidateFeatUsageType;
    }

    /**
     * Getter for fullScore.<p>
     */
    public Integer getFullScore() {
        return fullScore;
    }

    /**
     * Setter for fullScore.<p>
     */
    public void setFullScore(Integer fullScore) {
        this.fullScore = fullScore;
    }

    /**
     * Getter for generationMatch.<p>
     */
    public Integer getGenerationMatch() {
        return generationMatch;
    }

    /**
     * Setter for generationMatch.<p>
     */
    public void setGenerationMatch(Integer generationMatch) {
        this.generationMatch = generationMatch;
    }

    /**
     * Getter for gnrFn.<p>
     */
    public Integer getGnrFn() {
        return gnrFn;
    }

    /**
     * Setter for gnrFn.<p>
     */
    public void setGnrFn(Integer gnrFn) {
        this.gnrFn = gnrFn;
    }

    /**
     * Getter for gnrGn.<p>
     */
    public Integer getGnrGn() {
        return gnrGn;
    }

    /**
     * Setter for gnrGn.<p>
     */
    public void setGnrGn(Integer gnrGn) {
        this.gnrGn = gnrGn;
    }

    /**
     * Getter for gnrOn.<p>
     */
    public Integer getGnrOn() {
        return gnrOn;
    }

    /**
     * Setter for gnrOn.<p>
     */
    public void setGnrOn(Integer gnrOn) {
        this.gnrOn = gnrOn;
    }

    /**
     * Getter for gnrSn.<p>
     */
    public Integer getGnrSn() {
        return gnrSn;
    }

    /**
     * Setter for gnrSn.<p>
     */
    public void setGnrSn(Integer gnrSn) {
        this.gnrSn = gnrSn;
    }

    /**
     * Getter for inboundFeat.<p>
     */
    public String getInboundFeat() {
        return inboundFeat;
    }

    /**
     * Setter for inboundFeat.<p>
     */
    public void setInboundFeat(String inboundFeat) {
        this.inboundFeat = inboundFeat;
    }

    /**
     * Getter for inboundFeatId.<p>
     */
    public Integer getInboundFeatId() {
        return inboundFeatId;
    }

    /**
     * Setter for inboundFeatId.<p>
     */
    public void setInboundFeatId(Integer inboundFeatId) {
        this.inboundFeatId = inboundFeatId;
    }

    /**
     * Getter for inboundFeatUsageType.<p>
     */
    public String getInboundFeatUsageType() {
        return inboundFeatUsageType;
    }

    /**
     * Setter for inboundFeatUsageType.<p>
     */
    public void setInboundFeatUsageType(String inboundFeatUsageType) {
        this.inboundFeatUsageType = inboundFeatUsageType;
    }

    /**
     * Getter for scoreBehavior.<p>
     */
    public String getScoreBehavior() {
        return scoreBehavior;
    }

    /**
     * Setter for scoreBehavior.<p>
     */
    public void setScoreBehavior(String scoreBehavior) {
        this.scoreBehavior = scoreBehavior;
    }

    /**
     * Getter for scoreBucket.<p>
     */
    public String getScoreBucket() {
        return scoreBucket;
    }

    /**
     * Setter for scoreBucket.<p>
     */
    public void setScoreBucket(String scoreBucket) {
        this.scoreBucket = scoreBucket;
    }
}
