// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.schema;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * No description.
 */
@JsonSerialize
public class FocusRecord {
    @JsonProperty("DATA_SOURCE")
    private String dataSource;

    @JsonProperty("RECORD_ID")
    private String recordId;

    public FocusRecord() {
    }

    /**
     * Getter for dataSource.<p>
     * No description.
     */
    public String getDataSource() {
        return dataSource;
    }

    /**
     * Setter for dataSource.<p>
     * No description.
     */
    public void setDataSource(String dataSource) {
        this.dataSource = dataSource;
    }

    /**
     * Getter for recordId.<p>
     * No description.
     */
    public String getRecordId() {
        return recordId;
    }

    /**
     * Setter for recordId.<p>
     * No description.
     */
    public void setRecordId(String recordId) {
        this.recordId = recordId;
    }
}
