// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.schema;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.List;

public class G2diagnosticGetGenericFeaturesResponse {
    @JsonValue
    private List<G2diagnosticGetGenericFeaturesResponse0> value;

    public G2diagnosticGetGenericFeaturesResponse() {
    }

    @JsonCreator
    public G2diagnosticGetGenericFeaturesResponse(List<G2diagnosticGetGenericFeaturesResponse0> value) {
        this.value = value;
    }

    public List<G2diagnosticGetGenericFeaturesResponse0> getValue() {
        return value;
    }

    public void setValue(List<G2diagnosticGetGenericFeaturesResponse0> value) {
        this.value = value;
    }
}
