// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.schema;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

@JsonSerialize
public class G2diagnosticFindEntitiesByFeatureIdsResponseXxx0 {
    @JsonProperty("LIB_FEAT_ID")
    private Integer libFeatId;

    @JsonProperty("RES_ENT_ID")
    private Integer resEntId;

    @JsonProperty("USAGE_TYPE")
    private String usageType;

    public G2diagnosticFindEntitiesByFeatureIdsResponseXxx0() {
    }

    /**
     * Getter for libFeatId.<p>
     */
    public Integer getLibFeatId() {
        return libFeatId;
    }

    /**
     * Setter for libFeatId.<p>
     */
    public void setLibFeatId(Integer libFeatId) {
        this.libFeatId = libFeatId;
    }

    /**
     * Getter for resEntId.<p>
     */
    public Integer getResEntId() {
        return resEntId;
    }

    /**
     * Setter for resEntId.<p>
     */
    public void setResEntId(Integer resEntId) {
        this.resEntId = resEntId;
    }

    /**
     * Getter for usageType.<p>
     */
    public String getUsageType() {
        return usageType;
    }

    /**
     * Setter for usageType.<p>
     */
    public void setUsageType(String usageType) {
        this.usageType = usageType;
    }
}
