// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.schema;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public class G2engineFetchNextResponse {
    @JsonValue
    private FixmeUnknown value;

    public G2engineFetchNextResponse() {
    }

    @JsonCreator
    public G2engineFetchNextResponse(FixmeUnknown value) {
        this.value = value;
    }

    public FixmeUnknown getValue() {
        return value;
    }

    public void setValue(FixmeUnknown value) {
        this.value = value;
    }
}
