// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.schema;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public class G2engineExportConfigAndConfigIdResponse {
    @JsonValue
    private ExportConfig value;

    public G2engineExportConfigAndConfigIdResponse() {
    }

    @JsonCreator
    public G2engineExportConfigAndConfigIdResponse(ExportConfig value) {
        this.value = value;
    }

    public ExportConfig getValue() {
        return value;
    }

    public void setValue(ExportConfig value) {
        this.value = value;
    }
}
