// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.schema;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public class G2engineWhyEntityByEntityIdv2response {
    @JsonValue
    private WhyEntity value;

    public G2engineWhyEntityByEntityIdv2response() {
    }

    @JsonCreator
    public G2engineWhyEntityByEntityIdv2response(WhyEntity value) {
        this.value = value;
    }

    public WhyEntity getValue() {
        return value;
    }

    public void setValue(WhyEntity value) {
        this.value = value;
    }
}
