// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.schema;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * No description.
 */
@JsonSerialize
public class Path {
    @JsonProperty("ENTITIES")
    private Entities entities;

    @JsonProperty("ENTITY_PATHS")
    private EntityPaths entityPaths;

    public Path() {
    }

    /**
     * Getter for entities.<p>
     * No description.
     */
    public Entities getEntities() {
        return entities;
    }

    /**
     * Setter for entities.<p>
     * No description.
     */
    public void setEntities(Entities entities) {
        this.entities = entities;
    }

    /**
     * Getter for entityPaths.<p>
     * No description.
     */
    public EntityPaths getEntityPaths() {
        return entityPaths;
    }

    /**
     * Setter for entityPaths.<p>
     * No description.
     */
    public void setEntityPaths(EntityPaths entityPaths) {
        this.entityPaths = entityPaths;
    }
}
