// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.schema;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.List;

public class RecordSummary {
    @JsonValue
    private List<RecordSummaryElement> value;

    public RecordSummary() {
    }

    @JsonCreator
    public RecordSummary(List<RecordSummaryElement> value) {
        this.value = value;
    }

    public List<RecordSummaryElement> getValue() {
        return value;
    }

    public void setValue(List<RecordSummaryElement> value) {
        this.value = value;
    }
}
