// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.schema;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.List;

public class Relationships {
    @JsonValue
    private List<Relationship> value;

    public Relationships() {
    }

    @JsonCreator
    public Relationships(List<Relationship> value) {
        this.value = value;
    }

    public List<Relationship> getValue() {
        return value;
    }

    public void setValue(List<Relationship> value) {
        this.value = value;
    }
}
