// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.schema;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.util.List;

@JsonSerialize
public class RepositoryInfo {
    @JsonProperty("repositories")
    private List<Repository> repositories;

    public RepositoryInfo() {
    }

    /**
     * Getter for repositories.<p>
     */
    public List<Repository> getRepositories() {
        return repositories;
    }

    /**
     * Setter for repositories.<p>
     */
    public void setRepositories(List<Repository> repositories) {
        this.repositories = repositories;
    }
}
