// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.schema;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public class SzConfigGetJsonStringResponse {
    @JsonValue
    private GetJsonString value;

    public SzConfigGetJsonStringResponse() {
    }

    @JsonCreator
    public SzConfigGetJsonStringResponse(GetJsonString value) {
        this.value = value;
    }

    public GetJsonString getValue() {
        return value;
    }

    public void setValue(GetJsonString value) {
        this.value = value;
    }
}
