// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.schema;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public class SzDiagnosticGetRepositoryInfoResponse {
    @JsonValue
    private DatastoreInfo value;

    public SzDiagnosticGetRepositoryInfoResponse() {
    }

    @JsonCreator
    public SzDiagnosticGetRepositoryInfoResponse(DatastoreInfo value) {
        this.value = value;
    }

    public DatastoreInfo getValue() {
        return value;
    }

    public void setValue(DatastoreInfo value) {
        this.value = value;
    }
}
