// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.schema;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public class SzEngineStreamExportJsonEntityReportResponse {
    @JsonValue
    private StreamExportJsonEntity value;

    public SzEngineStreamExportJsonEntityReportResponse() {
    }

    @JsonCreator
    public SzEngineStreamExportJsonEntityReportResponse(StreamExportJsonEntity value) {
        this.value = value;
    }

    public StreamExportJsonEntity getValue() {
        return value;
    }

    public void setValue(StreamExportJsonEntity value) {
        this.value = value;
    }
}
