// Code generated by jtd-codegen for Go v0.2.1. DO NOT EDIT.

package typedef

type Senzingapi = interface{}

type Address struct {
	AddrCity string `json:"ADDR_CITY"`

	AddrCountry string `json:"ADDR_COUNTRY"`

	AddrFromDate string `json:"ADDR_FROM_DATE"`

	AddrFull string `json:"ADDR_FULL"`

	AddrLine1 string `json:"ADDR_LINE1"`

	AddrLine2 string `json:"ADDR_LINE2"`

	AddrLine3 string `json:"ADDR_LINE3"`

	AddrLine4 string `json:"ADDR_LINE4"`

	AddrLine5 string `json:"ADDR_LINE5"`

	AddrLine6 string `json:"ADDR_LINE6"`

	AddrPostalCode string `json:"ADDR_POSTAL_CODE"`

	AddrState string `json:"ADDR_STATE"`

	AddrThruDate string `json:"ADDR_THRU_DATE"`

	AddrType string `json:"ADDR_TYPE"`
}

type Addresses = []Address

type AffectedEntities = []AffectedEntity

type AffectedEntity struct {
	EntityID int64 `json:"ENTITY_ID"`
}

type AttributeCounter struct {
	Address float64 `json:"ADDRESS"`

	AddrKey float64 `json:"ADDR_KEY"`

	CallSign int64 `json:"CALL_SIGN"`

	Citizenship int64 `json:"CITIZENSHIP"`

	CountryOfAssociation int64 `json:"COUNTRY_OF_ASSOCIATION"`

	Dob float64 `json:"DOB"`

	Drlic float64 `json:"DRLIC"`

	DunsNumber int64 `json:"DUNS_NUMBER"`

	Email float64 `json:"EMAIL"`

	EmailKey float64 `json:"EMAIL_KEY"`

	EntityCount int64 `json:"ENTITY_COUNT"`

	EntitySize int64 `json:"ENTITY_SIZE"`

	Gender float64 `json:"GENDER"`

	IDKey float64 `json:"ID_KEY"`

	ImoNumber int64 `json:"IMO_NUMBER"`

	LeiNumber int64 `json:"LEI_NUMBER"`

	LoginID float64 `json:"LOGIN_ID"`

	MaxResEntID int64 `json:"MAX_RES_ENT_ID"`

	MinResEntID int64 `json:"MIN_RES_ENT_ID"`

	Name float64 `json:"NAME"`

	NameKey float64 `json:"NAME_KEY"`

	Nationality int64 `json:"NATIONALITY"`

	NationalID int64 `json:"NATIONAL_ID"`

	OfacID int64 `json:"OFAC_ID"`

	OtherID float64 `json:"OTHER_ID"`

	Passport float64 `json:"PASSPORT"`

	Phone float64 `json:"PHONE"`

	PhoneKey float64 `json:"PHONE_KEY"`

	RecordType float64 `json:"RECORD_TYPE"`

	RegistrationCountry int64 `json:"REGISTRATION_COUNTRY"`

	RegistrationDate int64 `json:"REGISTRATION_DATE"`

	RelAnchor int64 `json:"REL_ANCHOR"`

	RelPointer int64 `json:"REL_POINTER"`

	SearchKey float64 `json:"SEARCH_KEY"`

	Ssn float64 `json:"SSN"`

	TaxID float64 `json:"TAX_ID"`

	Website float64 `json:"WEBSITE"`
}

type AttributeCounters = []AttributeCounter

type CfgAttr struct {
	Advanced string `json:"ADVANCED"`

	AttrClass string `json:"ATTR_CLASS"`

	AttrCode string `json:"ATTR_CODE"`

	AttrID int64 `json:"ATTR_ID"`

	DefaultValue string `json:"DEFAULT_VALUE"`

	FelemCode string `json:"FELEM_CODE"`

	FelemReq string `json:"FELEM_REQ"`

	FtypeCode string `json:"FTYPE_CODE"`

	Internal string `json:"INTERNAL"`
}

type CfgCfbom struct {
	CfcallID int64 `json:"CFCALL_ID"`

	ExecOrder int64 `json:"EXEC_ORDER"`

	FelemID int64 `json:"FELEM_ID"`

	FtypeID int64 `json:"FTYPE_ID"`
}

type CfgCfcall struct {
	CfcallID int64 `json:"CFCALL_ID"`

	CfuncID int64 `json:"CFUNC_ID"`

	ExecOrder int64 `json:"EXEC_ORDER"`

	FtypeID int64 `json:"FTYPE_ID"`
}

type CfgCfrtn struct {
	CfrtnID int64 `json:"CFRTN_ID"`

	CfuncID int64 `json:"CFUNC_ID"`

	CfuncRtnval string `json:"CFUNC_RTNVAL"`

	CloseScore int64 `json:"CLOSE_SCORE"`

	ExecOrder int64 `json:"EXEC_ORDER"`

	FtypeID int64 `json:"FTYPE_ID"`

	LikelyScore int64 `json:"LIKELY_SCORE"`

	PlausibleScore int64 `json:"PLAUSIBLE_SCORE"`

	SameScore int64 `json:"SAME_SCORE"`

	UnLikelyScore int64 `json:"UN_LIKELY_SCORE"`
}

type CfgCfunc struct {
	AnonSupport string `json:"ANON_SUPPORT"`

	CfuncCode string `json:"CFUNC_CODE"`

	CfuncDesc string `json:"CFUNC_DESC"`

	CfuncID int64 `json:"CFUNC_ID"`

	ConnectStr string `json:"CONNECT_STR"`

	FuncLib string `json:"FUNC_LIB"`

	FuncVer string `json:"FUNC_VER"`

	JavaClassName string `json:"JAVA_CLASS_NAME"`

	Language string `json:"LANGUAGE"`
}

type CfgDfbom struct {
	DfcallID int64 `json:"DFCALL_ID"`

	ExecOrder int64 `json:"EXEC_ORDER"`

	FelemID int64 `json:"FELEM_ID"`

	FtypeID int64 `json:"FTYPE_ID"`
}

type CfgDfcall struct {
	DfcallID int64 `json:"DFCALL_ID"`

	DfuncID int64 `json:"DFUNC_ID"`

	ExecOrder int64 `json:"EXEC_ORDER"`

	FtypeID int64 `json:"FTYPE_ID"`
}

type CfgDfunc struct {
	AnonSupport string `json:"ANON_SUPPORT"`

	ConnectStr string `json:"CONNECT_STR"`

	DfuncCode string `json:"DFUNC_CODE"`

	DfuncDesc string `json:"DFUNC_DESC"`

	DfuncID int64 `json:"DFUNC_ID"`

	FuncLib string `json:"FUNC_LIB"`

	FuncVer string `json:"FUNC_VER"`

	JavaClassName string `json:"JAVA_CLASS_NAME"`

	Language string `json:"LANGUAGE"`
}

type CfgDsrc struct {
	Conversational string `json:"CONVERSATIONAL"`

	DsrcCode string `json:"DSRC_CODE"`

	DsrcDesc string `json:"DSRC_DESC"`

	DsrcID int64 `json:"DSRC_ID"`

	DsrcRely int64 `json:"DSRC_RELY"`

	RetentionLevel string `json:"RETENTION_LEVEL"`
}

type CfgDsrcInterest struct {
	DsrcID int64 `json:"DSRC_ID"`

	InterestFlag string `json:"INTEREST_FLAG"`

	MaxDegree int64 `json:"MAX_DEGREE"`
}

type CfgEbom struct {
	EtypeID int64 `json:"ETYPE_ID"`

	ExecOrder int64 `json:"EXEC_ORDER"`

	FtypeID int64 `json:"FTYPE_ID"`

	UtypeCode string `json:"UTYPE_CODE"`
}

type CfgEclass struct {
	EclassCode string `json:"ECLASS_CODE"`

	EclassDesc string `json:"ECLASS_DESC"`

	EclassID int64 `json:"ECLASS_ID"`

	Resolve string `json:"RESOLVE"`
}

type CfgEfbom struct {
	EfcallID int64 `json:"EFCALL_ID"`

	ExecOrder int64 `json:"EXEC_ORDER"`

	FelemID int64 `json:"FELEM_ID"`

	FelemReq string `json:"FELEM_REQ"`

	FtypeID int64 `json:"FTYPE_ID"`
}

type CfgEfcall struct {
	EfcallID int64 `json:"EFCALL_ID"`

	EfeatFtypeID int64 `json:"EFEAT_FTYPE_ID"`

	EfuncID int64 `json:"EFUNC_ID"`

	ExecOrder int64 `json:"EXEC_ORDER"`

	FelemID int64 `json:"FELEM_ID"`

	FtypeID int64 `json:"FTYPE_ID"`

	IsVirtual string `json:"IS_VIRTUAL"`
}

type CfgEfunc struct {
	ConnectStr string `json:"CONNECT_STR"`

	EfuncCode string `json:"EFUNC_CODE"`

	EfuncDesc string `json:"EFUNC_DESC"`

	EfuncID int64 `json:"EFUNC_ID"`

	FuncLib string `json:"FUNC_LIB"`

	FuncVer string `json:"FUNC_VER"`

	JavaClassName string `json:"JAVA_CLASS_NAME"`

	Language string `json:"LANGUAGE"`
}

type CfgErfrag struct {
	ErfragCode string `json:"ERFRAG_CODE"`

	ErfragDepends string `json:"ERFRAG_DEPENDS"`

	ErfragDesc string `json:"ERFRAG_DESC"`

	ErfragID int64 `json:"ERFRAG_ID"`

	ErfragSource string `json:"ERFRAG_SOURCE"`
}

type CfgErrule struct {
	DisqErfragCode string `json:"DISQ_ERFRAG_CODE"`

	ErruleCode string `json:"ERRULE_CODE"`

	ErruleDesc string `json:"ERRULE_DESC"`

	ErruleID int64 `json:"ERRULE_ID"`

	ErruleTier int64 `json:"ERRULE_TIER"`

	QualErfragCode string `json:"QUAL_ERFRAG_CODE"`

	RefScore int64 `json:"REF_SCORE"`

	Relate string `json:"RELATE"`

	Resolve string `json:"RESOLVE"`

	RtypeID int64 `json:"RTYPE_ID"`
}

type CfgEtype struct {
	EclassID int64 `json:"ECLASS_ID"`

	EtypeCode string `json:"ETYPE_CODE"`

	EtypeDesc string `json:"ETYPE_DESC"`

	EtypeID int64 `json:"ETYPE_ID"`
}

type CfgFbom struct {
	Derived string `json:"DERIVED"`

	DisplayDelim string `json:"DISPLAY_DELIM"`

	DisplayLevel int64 `json:"DISPLAY_LEVEL"`

	ExecOrder int64 `json:"EXEC_ORDER"`

	FelemID int64 `json:"FELEM_ID"`

	FtypeID int64 `json:"FTYPE_ID"`
}

type CfgFbovr struct {
	EclassID int64 `json:"ECLASS_ID"`

	FtypeExcl string `json:"FTYPE_EXCL"`

	FtypeFreq string `json:"FTYPE_FREQ"`

	FtypeID int64 `json:"FTYPE_ID"`

	FtypeStab string `json:"FTYPE_STAB"`

	UtypeCode string `json:"UTYPE_CODE"`
}

type CfgFclass struct {
	FclassCode string `json:"FCLASS_CODE"`

	FclassDesc string `json:"FCLASS_DESC"`

	FclassID int64 `json:"FCLASS_ID"`
}

type CfgFelem struct {
	DataType string `json:"DATA_TYPE"`

	FelemCode string `json:"FELEM_CODE"`

	FelemDesc string `json:"FELEM_DESC"`

	FelemID int64 `json:"FELEM_ID"`

	Tokenize string `json:"TOKENIZE"`
}

type CfgFtype struct {
	Anonymize string `json:"ANONYMIZE"`

	Derivation string `json:"DERIVATION"`

	Derived string `json:"DERIVED"`

	FclassID int64 `json:"FCLASS_ID"`

	FtypeCode string `json:"FTYPE_CODE"`

	FtypeDesc string `json:"FTYPE_DESC"`

	FtypeExcl string `json:"FTYPE_EXCL"`

	FtypeFreq string `json:"FTYPE_FREQ"`

	FtypeID int64 `json:"FTYPE_ID"`

	FtypeStab string `json:"FTYPE_STAB"`

	PersistHistory string `json:"PERSIST_HISTORY"`

	RtypeID int64 `json:"RTYPE_ID"`

	ShowInMatchKey string `json:"SHOW_IN_MATCH_KEY"`

	UsedForCand string `json:"USED_FOR_CAND"`

	Version int64 `json:"VERSION"`
}

type CfgGenericThreshold struct {
	Behavior string `json:"BEHAVIOR"`

	CandidateCap int64 `json:"CANDIDATE_CAP"`

	FtypeID int64 `json:"FTYPE_ID"`

	GplanID int64 `json:"GPLAN_ID"`

	ScoringCap int64 `json:"SCORING_CAP"`

	SendToRedo string `json:"SEND_TO_REDO"`
}

type CfgGplan struct {
	GplanCode string `json:"GPLAN_CODE"`

	GplanDesc string `json:"GPLAN_DESC"`

	GplanID int64 `json:"GPLAN_ID"`
}

type CfgLens struct {
	LensCode string `json:"LENS_CODE"`

	LensDesc string `json:"LENS_DESC"`

	LensID int64 `json:"LENS_ID"`
}

type CfgLensrl = []interface{}

type CfgRclass struct {
	IsDisclosed string `json:"IS_DISCLOSED"`

	RclassCode string `json:"RCLASS_CODE"`

	RclassDesc string `json:"RCLASS_DESC"`

	RclassID int64 `json:"RCLASS_ID"`
}

type CfgRtype struct {
	BreakRes string `json:"BREAK_RES"`

	RclassID int64 `json:"RCLASS_ID"`

	RelStrength int64 `json:"REL_STRENGTH"`

	RtypeCode string `json:"RTYPE_CODE"`

	RtypeDesc string `json:"RTYPE_DESC"`

	RtypeID int64 `json:"RTYPE_ID"`
}

type CfgSfcall struct {
	ExecOrder int64 `json:"EXEC_ORDER"`

	FelemID int64 `json:"FELEM_ID"`

	FtypeID int64 `json:"FTYPE_ID"`

	SfcallID int64 `json:"SFCALL_ID"`

	SfuncID int64 `json:"SFUNC_ID"`
}

type CfgSfunc struct {
	ConnectStr string `json:"CONNECT_STR"`

	FuncLib string `json:"FUNC_LIB"`

	FuncVer string `json:"FUNC_VER"`

	JavaClassName string `json:"JAVA_CLASS_NAME"`

	Language string `json:"LANGUAGE"`

	SfuncCode string `json:"SFUNC_CODE"`

	SfuncDesc string `json:"SFUNC_DESC"`

	SfuncID int64 `json:"SFUNC_ID"`
}

type ConfigBaseVersion struct {
	BuildDate string `json:"BUILD_DATE"`

	BuildNumber string `json:"BUILD_NUMBER"`

	BuildVersion string `json:"BUILD_VERSION"`

	CompatibilityVersion CompatibilityVersion `json:"COMPATIBILITY_VERSION"`

	ProductName string `json:"PRODUCT_NAME"`

	Version string `json:"VERSION"`
}

type CompatibilityVersion struct {
	ConfigVersion string `json:"CONFIG_VERSION"`
}

type Config struct {
	ConfigComments string `json:"CONFIG_COMMENTS"`

	ConfigID int64 `json:"CONFIG_ID"`

	SysCreateDt string `json:"SYS_CREATE_DT"`
}

type ConfigAddDataSourceResponse struct {
	DsrcID int64 `json:"DSRC_ID"`
}

type ConfigListDataSourcesResponse struct {
	DataSources DataSources `json:"DATA_SOURCES"`
}

type ConfigSaveResponse struct {
	G2Config G2config `json:"G2_CONFIG"`
}

type ConfigmgrGetConfigListResponse struct {
	Configs Configs `json:"CONFIGS"`
}

type ConfigmgrGetConfigResponse struct {
	G2Config G2config `json:"G2_CONFIG"`
}

type Configs = []Config

type DataSource struct {
	// The text representation of the datasource.
	DsrcCode string `json:"DSRC_CODE"`

	// The unique identifier of the datasource.
	DsrcID int64 `json:"DSRC_ID"`
}

// A list of datasources.
type DataSources = []DataSource

type DiagnosticCheckDbperfResponse struct {
	InsertTime int64 `json:"insertTime"`

	NumRecordsInserted int64 `json:"numRecordsInserted"`
}

type DiagnosticFetchNextEntityBySizeResponse0 struct {
	DsrcCode string `json:"DSRC_CODE"`

	EntSrcDesc string `json:"ENT_SRC_DESC"`

	EntSrcKey string `json:"ENT_SRC_KEY"`

	ErruleCode string `json:"ERRULE_CODE"`

	ErID int64 `json:"ER_ID"`

	EtypeCode string `json:"ETYPE_CODE"`

	JSONData JSONData `json:"JSON_DATA"`

	MatchKey string `json:"MATCH_KEY"`

	ObsEntID int64 `json:"OBS_ENT_ID"`

	RecordID string `json:"RECORD_ID"`

	ResEntID int64 `json:"RES_ENT_ID"`
}

type DiagnosticFetchNextEntityBySizeResponse = []DiagnosticFetchNextEntityBySizeResponse0

type DiagnosticFindEntitiesByFeatureIdsResponse0 struct {
	LibFeatID int64 `json:"LIB_FEAT_ID"`

	ResEntID int64 `json:"RES_ENT_ID"`

	UsageType string `json:"USAGE_TYPE"`
}

type DiagnosticFindEntitiesByFeatureIdsResponse = []DiagnosticFindEntitiesByFeatureIdsResponse0

type DiagnosticGetDbinfoResponseDetail struct {
	Name string `json:"Name"`

	Type string `json:"Type"`
}

type DiagnosticGetDbinfoResponse struct {
	DatabaseDetails []DiagnosticGetDbinfoResponseDetail `json:"Database Details"`

	HybridMode bool `json:"Hybrid Mode"`
}

type DiagnosticGetDataSourceCountsResponse0 struct {
	DsrcCode string `json:"DSRC_CODE"`

	DsrcID int64 `json:"DSRC_ID"`

	DsrcRecordCount int64 `json:"DSRC_RECORD_COUNT"`

	EtypeCode string `json:"ETYPE_CODE"`

	EtypeID int64 `json:"ETYPE_ID"`

	ObsEntCount int64 `json:"OBS_ENT_COUNT"`
}

type DiagnosticGetDataSourceCountsResponse = []DiagnosticGetDataSourceCountsResponse0

type DiagnosticGetEntityDetailsResponse0 struct {
	Derived string `json:"DERIVED"`

	DsrcCode string `json:"DSRC_CODE"`

	ErruleCode string `json:"ERRULE_CODE"`

	EtypeCode string `json:"ETYPE_CODE"`

	FeatDesc string `json:"FEAT_DESC"`

	FtypeCode string `json:"FTYPE_CODE"`

	MatchKey string `json:"MATCH_KEY"`

	ObsEntID int64 `json:"OBS_ENT_ID"`

	RecordID int64 `json:"RECORD_ID"`

	ResEntID int64 `json:"RES_ENT_ID"`

	UsageType string `json:"USAGE_TYPE"`
}

type DiagnosticGetEntityDetailsResponse = []DiagnosticGetEntityDetailsResponse0

type DiagnosticGetEntityResumeResponse0 struct {
	DsrcCode string `json:"DSRC_CODE"`

	EntSrcDesc string `json:"ENT_SRC_DESC"`

	ErruleCode string `json:"ERRULE_CODE"`

	EtypeCode string `json:"ETYPE_CODE"`

	JSONData JSONData `json:"JSON_DATA"`

	MatchKey string `json:"MATCH_KEY"`

	RecordID string `json:"RECORD_ID"`

	RelEntID int64 `json:"REL_ENT_ID"`

	ResEntID int64 `json:"RES_ENT_ID"`
}

type DiagnosticGetEntityResumeResponse = []DiagnosticGetEntityResumeResponse0

type DiagnosticGetEntitySizeBreakdownResponse = AttributeCounters

type DiagnosticGetFeatureResponseElements struct {
	FelemCode string `json:"FELEM_CODE"`

	FelemValue string `json:"FELEM_VALUE"`
}

type DiagnosticGetFeatureResponse struct {
	Elements []DiagnosticGetFeatureResponseElements `json:"ELEMENTS"`

	FtypeCode string `json:"FTYPE_CODE"`

	LibFeatID int64 `json:"LIB_FEAT_ID"`
}

type DiagnosticGetGenericFeaturesResponse0 struct {
	CandidateCapReached string `json:"CANDIDATE_CAP_REACHED"`

	EstimatedCount int64 `json:"ESTIMATED_COUNT"`

	FeatDesc string `json:"FEAT_DESC"`

	FtypeCode string `json:"FTYPE_CODE"`

	LibFeatID int64 `json:"LIB_FEAT_ID"`

	ScoringCapReached string `json:"SCORING_CAP_REACHED"`
}

type DiagnosticGetGenericFeaturesResponse = []DiagnosticGetGenericFeaturesResponse0

type DiagnosticGetMappingStatisticsResponse0 struct {
	Derived string `json:"DERIVED"`

	DsrcCode string `json:"DSRC_CODE"`

	EtypeCode string `json:"ETYPE_CODE"`

	FtypeCode string `json:"FTYPE_CODE"`

	MaxFeatDesc string `json:"MAX_FEAT_DESC"`

	MinFeatDesc string `json:"MIN_FEAT_DESC"`

	RecCount int64 `json:"REC_COUNT"`

	RecPct float64 `json:"REC_PCT"`

	UniqCount int64 `json:"UNIQ_COUNT"`

	UniqPct float64 `json:"UNIQ_PCT"`

	UsageType string `json:"USAGE_TYPE"`
}

type DiagnosticGetMappingStatisticsResponse = []DiagnosticGetMappingStatisticsResponse0

type DiagnosticGetRelationshipDetailsResponse0 struct {
	ErruleCode string `json:"ERRULE_CODE"`

	FeatDesc string `json:"FEAT_DESC"`

	FtypeCode string `json:"FTYPE_CODE"`

	MatchKey string `json:"MATCH_KEY"`

	ResEntID int64 `json:"RES_ENT_ID"`
}

type DiagnosticGetRelationshipDetailsResponse = []DiagnosticGetRelationshipDetailsResponse0

type DiagnosticGetResolutionStatisticsResponseRawMatchKeys struct {
	MatchKey string `json:"MATCH_KEY"`
}

type DiagnosticGetResolutionStatisticsResponse0 struct {
	ErruleCode string `json:"ERRULE_CODE"`

	ErruleID int64 `json:"ERRULE_ID"`

	IsAmbiguous string `json:"IS_AMBIGUOUS"`

	MatchKey string `json:"MATCH_KEY"`

	MatchLevel int64 `json:"MATCH_LEVEL"`

	MaxResEntID int64 `json:"MAX_RES_ENT_ID"`

	MaxResRelID int64 `json:"MAX_RES_REL_ID"`

	MinResEntID int64 `json:"MIN_RES_ENT_ID"`

	MinResRelID int64 `json:"MIN_RES_REL_ID"`

	RawMatchKeys []DiagnosticGetResolutionStatisticsResponseRawMatchKeys `json:"RAW_MATCH_KEYS"`

	RecordCount int64 `json:"RECORD_COUNT"`
}

type DiagnosticGetResolutionStatisticsResponse = []DiagnosticGetResolutionStatisticsResponse0

type DiagnosticStreamEntityListBySizeResponse = interface{}

type EngineAddRecordWithInfoResponse = WithInfo

type EngineAddRecordWithInfoWithReturnedRecordIdresponse = WithInfo

type EngineCheckRecordResponseCheckRecordResponse struct {
	CandidateMatch string `json:"CANDIDATE_MATCH"`

	DsrcCode string `json:"DSRC_CODE"`

	ErruleCode string `json:"ERRULE_CODE"`

	ErruleID int64 `json:"ERRULE_ID"`

	MatchKey string `json:"MATCH_KEY"`

	MatchLevel int64 `json:"MATCH_LEVEL"`

	MatchLevelCode string `json:"MATCH_LEVEL_CODE"`

	NonGenericCandidateMatch string `json:"NON_GENERIC_CANDIDATE_MATCH"`

	RecordID string `json:"RECORD_ID"`
}

type EngineCheckRecordResponse struct {
	CheckRecordResponse []EngineCheckRecordResponseCheckRecordResponse `json:"CHECK_RECORD_RESPONSE"`
}

type EngineDeleteRecordWithInfoResponse = WithInfo

type EngineExportConfigAndConfigIdresponse struct {
	G2Config G2config `json:"G2_CONFIG"`
}

type EngineExportConfigResponse struct {
	G2Config G2config `json:"G2_CONFIG"`
}

type EngineFetchNextResponse = interface{}

type EngineFindInterestingEntitiesByEntityIdresponse = Interesting

type EngineFindInterestingEntitiesByRecordIdresponse = Interesting

type EngineFindNetworkByEntityIdresponse = Network

type EngineFindNetworkByEntityIdv2response = Network

type EngineFindNetworkByRecordIdresponse = Network

type EngineFindNetworkByRecordIdv2response = Network

type EngineFindPathByEntityIdresponse = Path

type EngineFindPathByEntityIdv2response = Path

type EngineFindPathByRecordIdresponse = Path

type EngineFindPathByRecordIdv2response = Path

type EngineFindPathExcludingByEntityIdresponse = Path

type EngineFindPathExcludingByEntityIdv2response = Path

type EngineFindPathExcludingByRecordIdresponse = Path

type EngineFindPathExcludingByRecordIdv2response = Path

type EngineFindPathIncludingSourceByEntityIdresponse = Path

type EngineFindPathIncludingSourceByEntityIdv2response = Path

type EngineFindPathIncludingSourceByRecordIdresponse = Path

type EngineFindPathIncludingSourceByRecordIdv2response = Path

type EngineGetEntityByEntityIdresponse = Entity

type EngineGetEntityByEntityIdv2response = Entity

type EngineGetEntityByRecordIdresponse = Entity

type EngineGetEntityByRecordIdv2response = Entity

type EngineGetRecordResponse = Record

type EngineGetRecordV2response = Record

type EngineGetVirtualEntityByRecordIdresponse = VirtualEntity

type EngineGetVirtualEntityByRecordIdv2response = VirtualEntity

type EngineHowEntityByEntityIdresponse = How

type EngineHowEntityByEntityIdv2response = How

type EngineProcessRedoRecordResponse = interface{}

type EngineProcessRedoRecordWithInfoResponse = WithInfo

type EngineProcessWithInfoResponse = WithInfo

type EngineProcessWithResponseResizeResponse = Process

type EngineProcessWithResponseResponse = Process

type EngineReevaluateEntityWithInfoResponse = WithInfo

type EngineReevaluateRecordWithInfoResponse = WithInfo

type EngineReplaceRecordWithInfoResponse = WithInfo

type EngineSearchByAttributesResponse = Search

type EngineSearchByAttributesV2response = Search

type EngineSearchByAttributesV3response = Search

type EngineStatsResponseDuration struct {
	Pattern string `json:"PATTERN"`

	Type string `json:"TYPE"`
}

type EngineStatsResponseReresolveTriggers struct {
	AbortRetry int64 `json:"abortRetry"`

	MultipleResolvableCandidates int64 `json:"multipleResolvableCandidates"`

	ResolveNewFeatures int64 `json:"resolveNewFeatures"`

	UnresolveMovement int64 `json:"unresolveMovement"`
}

type EngineStatsResponseUnresolveTriggers struct {
	ExtensiveResolve int64 `json:"extensiveResolve"`

	NormalResolve int64 `json:"normalResolve"`
}

type EngineStatsResponseWorkloadExpressedFeatureCall struct {
	EfcallID int64 `json:"EFCALL_ID"`

	EfuncCode string `json:"EFUNC_CODE"`

	NumCalls int64 `json:"numCalls"`
}

type EngineStatsResponseWorkloadReresolveTriggers struct {
	AbortRetry int64 `json:"abortRetry"`

	MultipleResolvableCandidates int64 `json:"multipleResolvableCandidates"`

	NewFeatureFtypes AttributeCounters `json:"newFeatureFTypes"`

	ResolveNewFeatures int64 `json:"resolveNewFeatures"`

	UnresolveMovement int64 `json:"unresolveMovement"`
}

type EngineStatsResponseWorkloadSystemResourcesCurrResourceSystemLoad struct {
	CPUIdle float64 `json:"cpuIdle"`

	CPUSoftIrq float64 `json:"cpuSoftIrq"`

	CPUSystem float64 `json:"cpuSystem"`

	CPUUser float64 `json:"cpuUser"`

	CPUWait float64 `json:"cpuWait"`
}

type EngineStatsResponseWorkloadSystemResourcesCurrResource struct {
	ActiveThreads int64 `json:"activeThreads"`

	AvailableMemory string `json:"availableMemory"`

	SystemLoad []EngineStatsResponseWorkloadSystemResourcesCurrResourceSystemLoad `json:"systemLoad"`

	WorkerThreads int64 `json:"workerThreads"`
}

type EngineStatsResponseWorkloadSystemResourcesInitResource struct {
	AvailableMemory string `json:"availableMemory"`

	LogicalCores int64 `json:"logicalCores"`

	PhysicalCores int64 `json:"physicalCores"`

	TotalMemory string `json:"totalMemory"`
}

type EngineStatsResponseWorkloadSystemResources struct {
	CurrResources []EngineStatsResponseWorkloadSystemResourcesCurrResource `json:"currResources"`

	InitResources []EngineStatsResponseWorkloadSystemResourcesInitResource `json:"initResources"`
}

type EngineStatsResponseWorkloadThreadState struct {
	Active int64 `json:"active"`

	DataLatchContention int64 `json:"dataLatchContention"`

	Idle int64 `json:"idle"`

	Loader int64 `json:"loader"`

	ObsEntContention int64 `json:"obsEntContention"`

	ResEntContention int64 `json:"resEntContention"`

	Resolver int64 `json:"resolver"`

	Scoring int64 `json:"scoring"`

	SQLExecuting int64 `json:"sqlExecuting"`
}

type EngineStatsResponseWorkloadUnresolveTriggers struct {
	AmbiguousMultiResolve int64 `json:"ambiguousMultiResolve"`

	AmbiguousNoResolve int64 `json:"ambiguousNoResolve"`

	ExtensiveResolve int64 `json:"extensiveResolve"`

	NormalResolve int64 `json:"normalResolve"`

	RelLink int64 `json:"relLink"`

	Update int64 `json:"update"`
}

type EngineStatsResponseWorkload struct {
	CorruptEntityTestDiagnosis interface{} `json:"CorruptEntityTestDiagnosis"`

	AbortedUnresolve int64 `json:"abortedUnresolve"`

	ActualAmbiguousTest int64 `json:"actualAmbiguousTest"`

	AddedRecords int64 `json:"addedRecords"`

	APIVersion string `json:"apiVersion"`

	CacheHit AttributeCounters `json:"cacheHit"`

	CacheMiss AttributeCounters `json:"cacheMiss"`

	CachedAmbiguousTest int64 `json:"cachedAmbiguousTest"`

	CandidateBuilders AttributeCounters `json:"candidateBuilders"`

	Candidates int64 `json:"candidates"`

	DeletedRecords int64 `json:"deletedRecords"`

	Duration int64 `json:"duration"`

	ExpressedFeatureCalls []EngineStatsResponseWorkloadExpressedFeatureCall `json:"expressedFeatureCalls"`

	ExpressedFeaturesCreated AttributeCounters `json:"expressedFeaturesCreated"`

	FilteredObsFeat int64 `json:"filteredObsFeat"`

	GenericDetect AttributeCounters `json:"genericDetect"`

	GnrScorersUsed int64 `json:"gnrScorersUsed"`

	HighContentionFeat AttributeCounters `json:"highContentionFeat"`

	HighContentionResEnt AttributeCounters `json:"highContentionResEnt"`

	LatchContention AttributeCounters `json:"latchContention"`

	LibFeatCacheHit int64 `json:"libFeatCacheHit"`

	LibFeatCacheMiss int64 `json:"libFeatCacheMiss"`

	LoadedRecords int64 `json:"loadedRecords"`

	RedoTriggers AttributeCounters `json:"redoTriggers"`

	ReducedScoredFeatureType AttributeCounters `json:"reducedScoredFeatureType"`

	Reevaluations int64 `json:"reevaluations"`

	RepairedEntities int64 `json:"repairedEntities"`

	ReresolveSkipped int64 `json:"reresolveSkipped"`

	ReresolveTriggers EngineStatsResponseWorkloadReresolveTriggers `json:"reresolveTriggers"`

	ResFeatStatCacheHit int64 `json:"resFeatStatCacheHit"`

	ResFeatStatCacheMiss int64 `json:"resFeatStatCacheMiss"`

	ResFeatStatUpdate int64 `json:"resFeatStatUpdate"`

	Retries int64 `json:"retries"`

	ScoredPairs AttributeCounters `json:"scoredPairs"`

	SuppressedCandidateBuilders AttributeCounters `json:"suppressedCandidateBuilders"`

	SuppressedDisclosedRelationshipDomainCount int64 `json:"suppressedDisclosedRelationshipDomainCount"`

	SuppressedScoredFeatureType AttributeCounters `json:"suppressedScoredFeatureType"`

	SystemResources EngineStatsResponseWorkloadSystemResources `json:"systemResources"`

	ThreadState EngineStatsResponseWorkloadThreadState `json:"threadState"`

	UnresolveTest int64 `json:"unresolveTest"`

	UnresolveTriggers EngineStatsResponseWorkloadUnresolveTriggers `json:"unresolveTriggers"`
}

type EngineStatsResponse struct {
	MissingResEnt int64 `json:"MISSING_RES_ENT"`

	MissingResEntAndOkey int64 `json:"MISSING_RES_ENT_AND_OKEY"`

	AbortedUnresolve int64 `json:"abortedUnresolve"`

	ActualAmbiguousTest int64 `json:"actualAmbiguousTest"`

	AddedRecords int64 `json:"addedRecords"`

	CacheHit AttributeCounters `json:"cacheHit"`

	CandidateBuilders AttributeCounters `json:"candidateBuilders"`

	Candidates int64 `json:"candidates"`

	DeletedRecords int64 `json:"deletedRecords"`

	Duration EngineStatsResponseDuration `json:"duration"`

	FilteredObsFeat int64 `json:"filteredObsFeat"`

	GenericDetect AttributeCounters `json:"genericDetect"`

	LatchContention AttributeCounters `json:"latchContention"`

	LoadedRecords int64 `json:"loadedRecords"`

	RedoTriggers AttributeCounters `json:"redoTriggers"`

	ReducedScoredFeatureType AttributeCounters `json:"reducedScoredFeatureType"`

	Reevaluations int64 `json:"reevaluations"`

	RepairedEntities int64 `json:"repairedEntities"`

	ReresolveSkipped int64 `json:"reresolveSkipped"`

	ReresolveTriggers EngineStatsResponseReresolveTriggers `json:"reresolveTriggers"`

	Retries int64 `json:"retries"`

	ScoredPairs AttributeCounters `json:"scoredPairs"`

	SuppressedCandidateBuilders AttributeCounters `json:"suppressedCandidateBuilders"`

	SuppressedScoredFeatureType AttributeCounters `json:"suppressedScoredFeatureType"`

	UnresolveTest int64 `json:"unresolveTest"`

	UnresolveTriggers EngineStatsResponseUnresolveTriggers `json:"unresolveTriggers"`

	Workload EngineStatsResponseWorkload `json:"workload"`
}

type EngineStreamExportJsonentityReportResponse = interface{}

type EngineWhyEntitiesResponse = WhyEntities

type EngineWhyEntitiesV2response = WhyEntities

type EngineWhyEntityByEntityIdresponse = WhyEntity

type EngineWhyEntityByEntityIdv2response = WhyEntity

type EngineWhyEntityByRecordIdresponse = WhyEntity

type EngineWhyEntityByRecordIdv2response = WhyEntity

type EngineWhyRecordsResponse = WhyRecords

type EngineWhyRecordsV2response = WhyRecords

type Entities = []Entity

type EntitiesByFeatureID = []EntityByFeatureID

type Entity struct {
	RelatedEntities RelatedEntities `json:"RELATED_ENTITIES"`

	ResolvedEntity ResolvedEntity `json:"RESOLVED_ENTITY"`
}

type EntityByFeatureID struct {
	LibFeatID int64 `json:"LIB_FEAT_ID"`

	ResEntID int64 `json:"RES_ENT_ID"`

	UsageType string `json:"USAGE_TYPE"`
}

type EntityBySize struct {
	DsrcCode string `json:"DSRC_CODE"`

	EntSrcDesc string `json:"ENT_SRC_DESC"`

	EntSrcKey string `json:"ENT_SRC_KEY"`

	ErruleCode string `json:"ERRULE_CODE"`

	ErID int64 `json:"ER_ID"`

	EtypeCode string `json:"ETYPE_CODE"`

	JSONData JSONData `json:"JSON_DATA"`

	MatchKey string `json:"MATCH_KEY"`

	ObsEntID int64 `json:"OBS_ENT_ID"`

	RecordID string `json:"RECORD_ID"`

	ResEntID int64 `json:"RES_ENT_ID"`
}

type EntityPath struct {
	EndEntityID int64 `json:"END_ENTITY_ID"`

	Entities []int64 `json:"ENTITIES"`

	StartEntityID int64 `json:"START_ENTITY_ID"`
}

type EntityPaths = []EntityPath

type FeatureDescriptionValue struct {
	CandidateCapReached string `json:"CANDIDATE_CAP_REACHED"`

	EntityCount int64 `json:"ENTITY_COUNT"`

	FeatDesc string `json:"FEAT_DESC"`

	LibFeatID int64 `json:"LIB_FEAT_ID"`

	ScoringCapReached string `json:"SCORING_CAP_REACHED"`

	Suppressed string `json:"SUPPRESSED"`

	UsedForCand string `json:"USED_FOR_CAND"`

	UsedForScoring string `json:"USED_FOR_SCORING"`
}

type FeatureDescriptionValues = []FeatureDescriptionValue

type FeatureForAttribute struct {
	FeatDesc string `json:"FEAT_DESC"`

	FeatDescValues FeatureDescriptionValues `json:"FEAT_DESC_VALUES"`

	LibFeatID int64 `json:"LIB_FEAT_ID"`

	UsageType string `json:"USAGE_TYPE"`
}

type FeatureScoreForAttribute struct {
	CandidateFeat string `json:"CANDIDATE_FEAT"`

	CandidateFeatID int64 `json:"CANDIDATE_FEAT_ID"`

	CandidateFeatUsageType string `json:"CANDIDATE_FEAT_USAGE_TYPE"`

	FullScore int64 `json:"FULL_SCORE"`

	GenerationMatch int64 `json:"GENERATION_MATCH"`

	GnrFn int64 `json:"GNR_FN"`

	GnrGn int64 `json:"GNR_GN"`

	GnrOn int64 `json:"GNR_ON"`

	GnrSn int64 `json:"GNR_SN"`

	InboundFeat string `json:"INBOUND_FEAT"`

	InboundFeatID int64 `json:"INBOUND_FEAT_ID"`

	InboundFeatUsageType string `json:"INBOUND_FEAT_USAGE_TYPE"`

	ScoreBehavior string `json:"SCORE_BEHAVIOR"`

	ScoreBucket string `json:"SCORE_BUCKET"`
}

type FeatureScores struct {
	AccountDomain FeatureScoresForAttribute `json:"ACCOUNT_DOMAIN"`

	AccountNumber FeatureScoresForAttribute `json:"ACCOUNT_NUMBER"`

	AcctNum FeatureScoresForAttribute `json:"ACCT_NUM"`

	Address FeatureScoresForAttribute `json:"ADDRESS"`

	AddressList FeatureScoresForAttribute `json:"ADDRESS_LIST"`

	AddrFull FeatureScoresForAttribute `json:"ADDR_FULL"`

	AddrKey FeatureScoresForAttribute `json:"ADDR_KEY"`

	CellPhoneNumber FeatureScoresForAttribute `json:"CELL_PHONE_NUMBER"`

	Citizenship FeatureScoresForAttribute `json:"CITIZENSHIP"`

	CountryOfAssociation FeatureScoresForAttribute `json:"COUNTRY_OF_ASSOCIATION"`

	DataSource FeatureScoresForAttribute `json:"DATA_SOURCE"`

	DateOfBirth FeatureScoresForAttribute `json:"DATE_OF_BIRTH"`

	DateOfDeath FeatureScoresForAttribute `json:"DATE_OF_DEATH"`

	Dob FeatureScoresForAttribute `json:"DOB"`

	Dod FeatureScoresForAttribute `json:"DOD"`

	DriversLicenseNumber FeatureScoresForAttribute `json:"DRIVERS_LICENSE_NUMBER"`

	DriversLicenseState FeatureScoresForAttribute `json:"DRIVERS_LICENSE_STATE"`

	Drlic FeatureScoresForAttribute `json:"DRLIC"`

	DunsNumber FeatureScoresForAttribute `json:"DUNS_NUMBER"`

	Email FeatureScoresForAttribute `json:"EMAIL"`

	EmailAddress FeatureScoresForAttribute `json:"EMAIL_ADDRESS"`

	EmailKey FeatureScoresForAttribute `json:"EMAIL_KEY"`

	EmployerName FeatureScoresForAttribute `json:"EMPLOYER_NAME"`

	EntityType FeatureScoresForAttribute `json:"ENTITY_TYPE"`

	Facebook FeatureScoresForAttribute `json:"FACEBOOK"`

	Gender FeatureScoresForAttribute `json:"GENDER"`

	GroupAssnIDNumber FeatureScoresForAttribute `json:"GROUP_ASSN_ID_NUMBER"`

	GroupAssnIDType FeatureScoresForAttribute `json:"GROUP_ASSN_ID_TYPE"`

	GroupAssociationOrgName FeatureScoresForAttribute `json:"GROUP_ASSOCIATION_ORG_NAME"`

	GroupAssociationType FeatureScoresForAttribute `json:"GROUP_ASSOCIATION_TYPE"`

	IDKey FeatureScoresForAttribute `json:"ID_KEY"`

	Instagram FeatureScoresForAttribute `json:"INSTAGRAM"`

	LeiNumber FeatureScoresForAttribute `json:"LEI_NUMBER"`

	Linkedin FeatureScoresForAttribute `json:"LINKEDIN"`

	LoadID FeatureScoresForAttribute `json:"LOAD_ID"`

	LoginID FeatureScoresForAttribute `json:"LOGIN_ID"`

	Name FeatureScoresForAttribute `json:"NAME"`

	NameFull FeatureScoresForAttribute `json:"NAME_FULL"`

	NameKey FeatureScoresForAttribute `json:"NAME_KEY"`

	NameList FeatureScoresForAttribute `json:"NAME_LIST"`

	Nationality FeatureScoresForAttribute `json:"NATIONALITY"`

	NationalID FeatureScoresForAttribute `json:"NATIONAL_ID"`

	NationalIDCountry FeatureScoresForAttribute `json:"NATIONAL_ID_COUNTRY"`

	NationalIDNumber FeatureScoresForAttribute `json:"NATIONAL_ID_NUMBER"`

	NinCountry FeatureScoresForAttribute `json:"NIN_COUNTRY"`

	NinNumber FeatureScoresForAttribute `json:"NIN_NUMBER"`

	NpiNumber FeatureScoresForAttribute `json:"NPI_NUMBER"`

	OtherIDCountry FeatureScoresForAttribute `json:"OTHER_ID_COUNTRY"`

	OtherIDNumber FeatureScoresForAttribute `json:"OTHER_ID_NUMBER"`

	OtherIDType FeatureScoresForAttribute `json:"OTHER_ID_TYPE"`

	Passport FeatureScoresForAttribute `json:"PASSPORT"`

	Passports FeatureScoresForAttribute `json:"PASSPORTS"`

	PassportCountry FeatureScoresForAttribute `json:"PASSPORT_COUNTRY"`

	PassportNumber FeatureScoresForAttribute `json:"PASSPORT_NUMBER"`

	Phone FeatureScoresForAttribute `json:"PHONE"`

	Phones FeatureScoresForAttribute `json:"PHONES"`

	PhoneKey FeatureScoresForAttribute `json:"PHONE_KEY"`

	PlaceOfBirth FeatureScoresForAttribute `json:"PLACE_OF_BIRTH"`

	PrimaryNameFirst FeatureScoresForAttribute `json:"PRIMARY_NAME_FIRST"`

	PrimaryNameLast FeatureScoresForAttribute `json:"PRIMARY_NAME_LAST"`

	PrimaryNameMiddle FeatureScoresForAttribute `json:"PRIMARY_NAME_MIDDLE"`

	PrimaryNameOrg FeatureScoresForAttribute `json:"PRIMARY_NAME_ORG"`

	PrimaryNamePrefix FeatureScoresForAttribute `json:"PRIMARY_NAME_PREFIX"`

	PrimaryNameSuffix FeatureScoresForAttribute `json:"PRIMARY_NAME_SUFFIX"`

	PrimaryPhoneNumber FeatureScoresForAttribute `json:"PRIMARY_PHONE_NUMBER"`

	RecordType FeatureScoresForAttribute `json:"RECORD_TYPE"`

	RegistrationCountry FeatureScoresForAttribute `json:"REGISTRATION_COUNTRY"`

	RegistrationDate FeatureScoresForAttribute `json:"REGISTRATION_DATE"`

	RelAnchor FeatureScoresForAttribute `json:"REL_ANCHOR"`

	RelAnchorDomain FeatureScoresForAttribute `json:"REL_ANCHOR_DOMAIN"`

	RelAnchorKey FeatureScoresForAttribute `json:"REL_ANCHOR_KEY"`

	RelLink FeatureScoresForAttribute `json:"REL_LINK"`

	RelPointer FeatureScoresForAttribute `json:"REL_POINTER"`

	RelPointerDomain FeatureScoresForAttribute `json:"REL_POINTER_DOMAIN"`

	RelPointerKey FeatureScoresForAttribute `json:"REL_POINTER_KEY"`

	RelPointerRole FeatureScoresForAttribute `json:"REL_POINTER_ROLE"`

	Signal FeatureScoresForAttribute `json:"SIGNAL"`

	Skype FeatureScoresForAttribute `json:"SKYPE"`

	SocialHandle FeatureScoresForAttribute `json:"SOCIAL_HANDLE"`

	SocialNetwork FeatureScoresForAttribute `json:"SOCIAL_NETWORK"`

	SourceID FeatureScoresForAttribute `json:"SOURCE_ID"`

	Ssn FeatureScoresForAttribute `json:"SSN"`

	SsnLast4 FeatureScoresForAttribute `json:"SSN_LAST4"`

	SsnNumber FeatureScoresForAttribute `json:"SSN_NUMBER"`

	Tango FeatureScoresForAttribute `json:"TANGO"`

	TaxIDCountry FeatureScoresForAttribute `json:"TAX_ID_COUNTRY"`

	TaxIDNumber FeatureScoresForAttribute `json:"TAX_ID_NUMBER"`

	TaxIDType FeatureScoresForAttribute `json:"TAX_ID_TYPE"`

	Telegram FeatureScoresForAttribute `json:"TELEGRAM"`

	TrustedIDNumber FeatureScoresForAttribute `json:"TRUSTED_ID_NUMBER"`

	TrustedIDType FeatureScoresForAttribute `json:"TRUSTED_ID_TYPE"`

	Twitter FeatureScoresForAttribute `json:"TWITTER"`

	Viber FeatureScoresForAttribute `json:"VIBER"`

	WebsiteAddress FeatureScoresForAttribute `json:"WEBSITE_ADDRESS"`

	Wechat FeatureScoresForAttribute `json:"WECHAT"`

	Whatsapp FeatureScoresForAttribute `json:"WHATSAPP"`

	WorkPhoneNumber FeatureScoresForAttribute `json:"WORK_PHONE_NUMBER"`

	Zoomroom FeatureScoresForAttribute `json:"ZOOMROOM"`
}

type FeatureScoresForAttribute = []FeatureScoreForAttribute

type Features struct {
	AccountDomain FeaturesForAttribute `json:"ACCOUNT_DOMAIN"`

	AccountNumber FeaturesForAttribute `json:"ACCOUNT_NUMBER"`

	AcctNum FeaturesForAttribute `json:"ACCT_NUM"`

	Address FeaturesForAttribute `json:"ADDRESS"`

	AddressList FeaturesForAttribute `json:"ADDRESS_LIST"`

	AddrFull FeaturesForAttribute `json:"ADDR_FULL"`

	AddrKey FeaturesForAttribute `json:"ADDR_KEY"`

	CellPhoneNumber FeaturesForAttribute `json:"CELL_PHONE_NUMBER"`

	Citizenship FeaturesForAttribute `json:"CITIZENSHIP"`

	CountryOfAssociation FeaturesForAttribute `json:"COUNTRY_OF_ASSOCIATION"`

	DataSource FeaturesForAttribute `json:"DATA_SOURCE"`

	DateOfBirth FeaturesForAttribute `json:"DATE_OF_BIRTH"`

	DateOfDeath FeaturesForAttribute `json:"DATE_OF_DEATH"`

	Dob FeaturesForAttribute `json:"DOB"`

	Dod FeaturesForAttribute `json:"DOD"`

	DriversLicenseNumber FeaturesForAttribute `json:"DRIVERS_LICENSE_NUMBER"`

	DriversLicenseState FeaturesForAttribute `json:"DRIVERS_LICENSE_STATE"`

	Drlic FeaturesForAttribute `json:"DRLIC"`

	DunsNumber FeaturesForAttribute `json:"DUNS_NUMBER"`

	Email FeaturesForAttribute `json:"EMAIL"`

	EmailAddress FeaturesForAttribute `json:"EMAIL_ADDRESS"`

	EmailKey FeaturesForAttribute `json:"EMAIL_KEY"`

	EmployerName FeaturesForAttribute `json:"EMPLOYER_NAME"`

	EntityType FeaturesForAttribute `json:"ENTITY_TYPE"`

	Facebook FeaturesForAttribute `json:"FACEBOOK"`

	Gender FeaturesForAttribute `json:"GENDER"`

	GroupAssnIDNumber FeaturesForAttribute `json:"GROUP_ASSN_ID_NUMBER"`

	GroupAssnIDType FeaturesForAttribute `json:"GROUP_ASSN_ID_TYPE"`

	GroupAssociationOrgName FeaturesForAttribute `json:"GROUP_ASSOCIATION_ORG_NAME"`

	GroupAssociationType FeaturesForAttribute `json:"GROUP_ASSOCIATION_TYPE"`

	IDKey FeaturesForAttribute `json:"ID_KEY"`

	Instagram FeaturesForAttribute `json:"INSTAGRAM"`

	LeiNumber FeaturesForAttribute `json:"LEI_NUMBER"`

	Linkedin FeaturesForAttribute `json:"LINKEDIN"`

	LoadID FeaturesForAttribute `json:"LOAD_ID"`

	LoginID FeaturesForAttribute `json:"LOGIN_ID"`

	Name FeaturesForAttribute `json:"NAME"`

	NameFull FeaturesForAttribute `json:"NAME_FULL"`

	NameKey FeaturesForAttribute `json:"NAME_KEY"`

	NameList FeaturesForAttribute `json:"NAME_LIST"`

	Nationality FeaturesForAttribute `json:"NATIONALITY"`

	NationalID FeaturesForAttribute `json:"NATIONAL_ID"`

	NationalIDCountry FeaturesForAttribute `json:"NATIONAL_ID_COUNTRY"`

	NationalIDNumber FeaturesForAttribute `json:"NATIONAL_ID_NUMBER"`

	NinCountry FeaturesForAttribute `json:"NIN_COUNTRY"`

	NinNumber FeaturesForAttribute `json:"NIN_NUMBER"`

	NpiNumber FeaturesForAttribute `json:"NPI_NUMBER"`

	OtherIDCountry FeaturesForAttribute `json:"OTHER_ID_COUNTRY"`

	OtherIDNumber FeaturesForAttribute `json:"OTHER_ID_NUMBER"`

	OtherIDType FeaturesForAttribute `json:"OTHER_ID_TYPE"`

	Passport FeaturesForAttribute `json:"PASSPORT"`

	Passports FeaturesForAttribute `json:"PASSPORTS"`

	PassportCountry FeaturesForAttribute `json:"PASSPORT_COUNTRY"`

	PassportNumber FeaturesForAttribute `json:"PASSPORT_NUMBER"`

	Phone FeaturesForAttribute `json:"PHONE"`

	Phones FeaturesForAttribute `json:"PHONES"`

	PhoneKey FeaturesForAttribute `json:"PHONE_KEY"`

	PlaceOfBirth FeaturesForAttribute `json:"PLACE_OF_BIRTH"`

	PrimaryNameFirst FeaturesForAttribute `json:"PRIMARY_NAME_FIRST"`

	PrimaryNameLast FeaturesForAttribute `json:"PRIMARY_NAME_LAST"`

	PrimaryNameMiddle FeaturesForAttribute `json:"PRIMARY_NAME_MIDDLE"`

	PrimaryNameOrg FeaturesForAttribute `json:"PRIMARY_NAME_ORG"`

	PrimaryNamePrefix FeaturesForAttribute `json:"PRIMARY_NAME_PREFIX"`

	PrimaryNameSuffix FeaturesForAttribute `json:"PRIMARY_NAME_SUFFIX"`

	PrimaryPhoneNumber FeaturesForAttribute `json:"PRIMARY_PHONE_NUMBER"`

	RecordType FeaturesForAttribute `json:"RECORD_TYPE"`

	RegistrationCountry FeaturesForAttribute `json:"REGISTRATION_COUNTRY"`

	RegistrationDate FeaturesForAttribute `json:"REGISTRATION_DATE"`

	RelAnchor FeaturesForAttribute `json:"REL_ANCHOR"`

	RelAnchorDomain FeaturesForAttribute `json:"REL_ANCHOR_DOMAIN"`

	RelAnchorKey FeaturesForAttribute `json:"REL_ANCHOR_KEY"`

	RelLink FeaturesForAttribute `json:"REL_LINK"`

	RelPointer FeaturesForAttribute `json:"REL_POINTER"`

	RelPointerDomain FeaturesForAttribute `json:"REL_POINTER_DOMAIN"`

	RelPointerKey FeaturesForAttribute `json:"REL_POINTER_KEY"`

	RelPointerRole FeaturesForAttribute `json:"REL_POINTER_ROLE"`

	Signal FeaturesForAttribute `json:"SIGNAL"`

	Skype FeaturesForAttribute `json:"SKYPE"`

	SocialHandle FeaturesForAttribute `json:"SOCIAL_HANDLE"`

	SocialNetwork FeaturesForAttribute `json:"SOCIAL_NETWORK"`

	SourceID FeaturesForAttribute `json:"SOURCE_ID"`

	Ssn FeaturesForAttribute `json:"SSN"`

	SsnLast4 FeaturesForAttribute `json:"SSN_LAST4"`

	SsnNumber FeaturesForAttribute `json:"SSN_NUMBER"`

	Tango FeaturesForAttribute `json:"TANGO"`

	TaxIDCountry FeaturesForAttribute `json:"TAX_ID_COUNTRY"`

	TaxIDNumber FeaturesForAttribute `json:"TAX_ID_NUMBER"`

	TaxIDType FeaturesForAttribute `json:"TAX_ID_TYPE"`

	Telegram FeaturesForAttribute `json:"TELEGRAM"`

	TrustedIDNumber FeaturesForAttribute `json:"TRUSTED_ID_NUMBER"`

	TrustedIDType FeaturesForAttribute `json:"TRUSTED_ID_TYPE"`

	Twitter FeaturesForAttribute `json:"TWITTER"`

	Viber FeaturesForAttribute `json:"VIBER"`

	WebsiteAddress FeaturesForAttribute `json:"WEBSITE_ADDRESS"`

	Wechat FeaturesForAttribute `json:"WECHAT"`

	Whatsapp FeaturesForAttribute `json:"WHATSAPP"`

	WorkPhoneNumber FeaturesForAttribute `json:"WORK_PHONE_NUMBER"`

	Zoomroom FeaturesForAttribute `json:"ZOOMROOM"`
}

type FeaturesForAttribute = []FeatureForAttribute

type FinalState struct {
	NeedReevaluation int64 `json:"NEED_REEVALUATION"`

	VirtualEntities []VirtualEntitySynopsis `json:"VIRTUAL_ENTITIES"`
}

type FocusRecord struct {
	DataSource string `json:"DATA_SOURCE"`

	RecordID string `json:"RECORD_ID"`
}

type FocusRecords = []FocusRecord

type G2config struct {
	CfgAttr []CfgAttr `json:"CFG_ATTR"`

	CfgCfbom []CfgCfbom `json:"CFG_CFBOM"`

	CfgCfcall []CfgCfcall `json:"CFG_CFCALL"`

	CfgCfrtn []CfgCfrtn `json:"CFG_CFRTN"`

	CfgCfunc []CfgCfunc `json:"CFG_CFUNC"`

	CfgDfbom []CfgDfbom `json:"CFG_DFBOM"`

	CfgDfcall []CfgDfcall `json:"CFG_DFCALL"`

	CfgDfunc []CfgDfunc `json:"CFG_DFUNC"`

	CfgDsrc []CfgDsrc `json:"CFG_DSRC"`

	CfgDsrcInterest []CfgDsrcInterest `json:"CFG_DSRC_INTEREST"`

	CfgEbom []CfgEbom `json:"CFG_EBOM"`

	CfgEclass []CfgEclass `json:"CFG_ECLASS"`

	CfgEfbom []CfgEfbom `json:"CFG_EFBOM"`

	CfgEfcall []CfgEfcall `json:"CFG_EFCALL"`

	CfgEfunc []CfgEfunc `json:"CFG_EFUNC"`

	CfgErfrag []CfgErfrag `json:"CFG_ERFRAG"`

	CfgErrule []CfgErrule `json:"CFG_ERRULE"`

	CfgEtype []CfgEtype `json:"CFG_ETYPE"`

	CfgFbom []CfgFbom `json:"CFG_FBOM"`

	CfgFbovr []CfgFbovr `json:"CFG_FBOVR"`

	CfgFclass []CfgFclass `json:"CFG_FCLASS"`

	CfgFelem []CfgFelem `json:"CFG_FELEM"`

	CfgFtype []CfgFtype `json:"CFG_FTYPE"`

	CfgGenericThreshold []CfgGenericThreshold `json:"CFG_GENERIC_THRESHOLD"`

	CfgGplan []CfgGplan `json:"CFG_GPLAN"`

	CfgLens []CfgLens `json:"CFG_LENS"`

	CfgLensrl []CfgLensrl `json:"CFG_LENSRL"`

	CfgRclass []CfgRclass `json:"CFG_RCLASS"`

	CfgRtype []CfgRtype `json:"CFG_RTYPE"`

	CfgSfcall []CfgSfcall `json:"CFG_SFCALL"`

	CfgSfunc []CfgSfunc `json:"CFG_SFUNC"`

	ConfigBaseVersion ConfigBaseVersion `json:"CONFIG_BASE_VERSION"`

	SysOom []SysOom `json:"SYS_OOM"`
}

type G2configAddDataSourceResponse struct {
	DsrcID int64 `json:"DSRC_ID"`
}

type G2configListDataSourcesResponse struct {
	DataSources DataSources `json:"DATA_SOURCES"`
}

type G2configSaveResponse struct {
	G2Config G2config `json:"G2_CONFIG"`
}

type G2configmgrGetConfigListResponse struct {
	Configs Configs `json:"CONFIGS"`
}

type G2configmgrGetConfigResponse struct {
	G2Config G2config `json:"G2_CONFIG"`
}

type G2diagnosticCheckDbperfResponse struct {
	InsertTime int64 `json:"insertTime"`

	NumRecordsInserted int64 `json:"numRecordsInserted"`
}

type G2diagnosticFetchNextEntityBySizeResponse = []EntityBySize

type G2diagnosticFindEntitiesByFeatureIdsResponseXxx0 struct {
	LibFeatID int64 `json:"LIB_FEAT_ID"`

	ResEntID int64 `json:"RES_ENT_ID"`

	UsageType string `json:"USAGE_TYPE"`
}

type G2diagnosticFindEntitiesByFeatureIdsResponseXxx = []G2diagnosticFindEntitiesByFeatureIdsResponseXxx0

type G2diagnosticGetDbinfoResponseDetail struct {
	Name string `json:"Name"`

	Type string `json:"Type"`
}

type G2diagnosticGetDbinfoResponse struct {
	DatabaseDetails []G2diagnosticGetDbinfoResponseDetail `json:"Database Details"`

	HybridMode bool `json:"Hybrid Mode"`
}

type G2diagnosticGetDataSourceCountsResponse0 struct {
	DsrcCode string `json:"DSRC_CODE"`

	DsrcID int64 `json:"DSRC_ID"`

	DsrcRecordCount int64 `json:"DSRC_RECORD_COUNT"`

	EtypeCode string `json:"ETYPE_CODE"`

	EtypeID int64 `json:"ETYPE_ID"`

	ObsEntCount int64 `json:"OBS_ENT_COUNT"`
}

type G2diagnosticGetDataSourceCountsResponse = []G2diagnosticGetDataSourceCountsResponse0

type G2diagnosticGetEntityDetailsResponse0 struct {
	Derived string `json:"DERIVED"`

	DsrcCode string `json:"DSRC_CODE"`

	ErruleCode string `json:"ERRULE_CODE"`

	EtypeCode string `json:"ETYPE_CODE"`

	FeatDesc string `json:"FEAT_DESC"`

	FtypeCode string `json:"FTYPE_CODE"`

	MatchKey string `json:"MATCH_KEY"`

	ObsEntID int64 `json:"OBS_ENT_ID"`

	RecordID int64 `json:"RECORD_ID"`

	ResEntID int64 `json:"RES_ENT_ID"`

	UsageType string `json:"USAGE_TYPE"`
}

type G2diagnosticGetEntityDetailsResponse = []G2diagnosticGetEntityDetailsResponse0

type G2diagnosticGetEntityResumeResponse0 struct {
	DsrcCode string `json:"DSRC_CODE"`

	EntSrcDesc string `json:"ENT_SRC_DESC"`

	ErruleCode string `json:"ERRULE_CODE"`

	EtypeCode string `json:"ETYPE_CODE"`

	JSONData JSONData `json:"JSON_DATA"`

	MatchKey string `json:"MATCH_KEY"`

	RecordID string `json:"RECORD_ID"`

	RelEntID int64 `json:"REL_ENT_ID"`

	ResEntID int64 `json:"RES_ENT_ID"`
}

type G2diagnosticGetEntityResumeResponse = []G2diagnosticGetEntityResumeResponse0

type G2diagnosticGetEntitySizeBreakdownResponse = AttributeCounters

type G2diagnosticGetFeatureResponseElements struct {
	FelemCode string `json:"FELEM_CODE"`

	FelemValue string `json:"FELEM_VALUE"`
}

type G2diagnosticGetFeatureResponse struct {
	Elements []G2diagnosticGetFeatureResponseElements `json:"ELEMENTS"`

	FtypeCode string `json:"FTYPE_CODE"`

	LibFeatID int64 `json:"LIB_FEAT_ID"`
}

type G2diagnosticGetGenericFeaturesResponse0 struct {
	CandidateCapReached string `json:"CANDIDATE_CAP_REACHED"`

	EstimatedCount int64 `json:"ESTIMATED_COUNT"`

	FeatDesc string `json:"FEAT_DESC"`

	FtypeCode string `json:"FTYPE_CODE"`

	LibFeatID int64 `json:"LIB_FEAT_ID"`

	ScoringCapReached string `json:"SCORING_CAP_REACHED"`
}

type G2diagnosticGetGenericFeaturesResponse = []G2diagnosticGetGenericFeaturesResponse0

type G2diagnosticGetMappingStatisticsResponse0 struct {
	Derived string `json:"DERIVED"`

	DsrcCode string `json:"DSRC_CODE"`

	EtypeCode string `json:"ETYPE_CODE"`

	FtypeCode string `json:"FTYPE_CODE"`

	MaxFeatDesc string `json:"MAX_FEAT_DESC"`

	MinFeatDesc string `json:"MIN_FEAT_DESC"`

	RecCount int64 `json:"REC_COUNT"`

	RecPct float64 `json:"REC_PCT"`

	UniqCount int64 `json:"UNIQ_COUNT"`

	UniqPct float64 `json:"UNIQ_PCT"`

	UsageType string `json:"USAGE_TYPE"`
}

type G2diagnosticGetMappingStatisticsResponse = []G2diagnosticGetMappingStatisticsResponse0

type G2diagnosticGetRelationshipDetailsResponse0 struct {
	ErruleCode string `json:"ERRULE_CODE"`

	FeatDesc string `json:"FEAT_DESC"`

	FtypeCode string `json:"FTYPE_CODE"`

	MatchKey string `json:"MATCH_KEY"`

	ResEntID int64 `json:"RES_ENT_ID"`
}

type G2diagnosticGetRelationshipDetailsResponse = []G2diagnosticGetRelationshipDetailsResponse0

type G2diagnosticGetResolutionStatisticsResponseRawMatchKeys struct {
	MatchKey string `json:"MATCH_KEY"`
}

type G2diagnosticGetResolutionStatisticsResponse0 struct {
	ErruleCode string `json:"ERRULE_CODE"`

	ErruleID int64 `json:"ERRULE_ID"`

	IsAmbiguous string `json:"IS_AMBIGUOUS"`

	MatchKey string `json:"MATCH_KEY"`

	MatchLevel int64 `json:"MATCH_LEVEL"`

	MaxResEntID int64 `json:"MAX_RES_ENT_ID"`

	MaxResRelID int64 `json:"MAX_RES_REL_ID"`

	MinResEntID int64 `json:"MIN_RES_ENT_ID"`

	MinResRelID int64 `json:"MIN_RES_REL_ID"`

	RawMatchKeys []G2diagnosticGetResolutionStatisticsResponseRawMatchKeys `json:"RAW_MATCH_KEYS"`

	RecordCount int64 `json:"RECORD_COUNT"`
}

type G2diagnosticGetResolutionStatisticsResponse = []G2diagnosticGetResolutionStatisticsResponse0

type G2diagnosticStreamEntityListBySizeResponse = interface{}

type G2engineAddRecordWithInfoResponse = WithInfo

type G2engineAddRecordWithInfoWithReturnedRecordIDResponse = WithInfo

type G2engineCheckRecordResponseCheckRecordResponse struct {
	CandidateMatch string `json:"CANDIDATE_MATCH"`

	DsrcCode string `json:"DSRC_CODE"`

	ErruleCode string `json:"ERRULE_CODE"`

	ErruleID int64 `json:"ERRULE_ID"`

	MatchKey string `json:"MATCH_KEY"`

	MatchLevel int64 `json:"MATCH_LEVEL"`

	MatchLevelCode string `json:"MATCH_LEVEL_CODE"`

	NonGenericCandidateMatch string `json:"NON_GENERIC_CANDIDATE_MATCH"`

	RecordID string `json:"RECORD_ID"`
}

type G2engineCheckRecordResponse struct {
	CheckRecordResponse []G2engineCheckRecordResponseCheckRecordResponse `json:"CHECK_RECORD_RESPONSE"`
}

type G2engineDeleteRecordWithInfoResponse = WithInfo

type G2engineExportConfigAndConfigIDResponse struct {
	G2Config G2config `json:"G2_CONFIG"`
}

type G2engineExportConfigResponse struct {
	G2Config G2config `json:"G2_CONFIG"`
}

type G2engineFetchNextResponse = interface{}

type G2engineFindInterestingEntitiesByEntityIDResponse = Interesting

type G2engineFindInterestingEntitiesByRecordIDResponse = Interesting

type G2engineFindNetworkByEntityIdv2response = Network

type G2engineFindNetworkByEntityIDResponse = Network

type G2engineFindNetworkByRecordIdv2response = Network

type G2engineFindNetworkByRecordIDResponse = Network

type G2engineFindPathByEntityIdv2response = Path

type G2engineFindPathByEntityIDResponse = Path

type G2engineFindPathByRecordIdv2response = Path

type G2engineFindPathByRecordIDResponse = Path

type G2engineFindPathExcludingByEntityIdv2response = Path

type G2engineFindPathExcludingByEntityIDResponse = Path

type G2engineFindPathExcludingByRecordIdv2response = Path

type G2engineFindPathExcludingByRecordIDResponse = Path

type G2engineFindPathIncludingSourceByEntityIdv2response = Path

type G2engineFindPathIncludingSourceByEntityIDResponse = Path

type G2engineFindPathIncludingSourceByRecordIdv2response = Path

type G2engineFindPathIncludingSourceByRecordIDResponse = Path

type G2engineGetEntityByEntityIdv2response = Entity

type G2engineGetEntityByEntityIDResponse = Entity

type G2engineGetEntityByRecordIdv2response = Entity

type G2engineGetEntityByRecordIDResponse = Entity

type G2engineGetRecordResponse = Record

type G2engineGetRecordV2response = Record

type G2engineGetVirtualEntityByRecordIdv2response = VirtualEntity

type G2engineGetVirtualEntityByRecordIDResponse = VirtualEntity

type G2engineHowEntityByEntityIdv2response = How

type G2engineHowEntityByEntityIDResponse = How

type G2engineProcessRedoRecordResponse = interface{}

type G2engineProcessRedoRecordWithInfoResponse = WithInfo

type G2engineProcessWithInfoResponse = WithInfo

type G2engineProcessWithResponseResizeResponse = Process

type G2engineProcessWithResponseResponse = Process

type G2engineReevaluateEntityWithInfoResponse = WithInfo

type G2engineReevaluateRecordWithInfoResponse = WithInfo

type G2engineReplaceRecordWithInfoResponse = WithInfo

type G2engineSearchByAttributesResponse = Search

type G2engineSearchByAttributesResponseXxx = EntitiesByFeatureID

type G2engineSearchByAttributesV2response = Search

type G2engineSearchByAttributesV3response = Search

type G2engineStatsResponseDuration struct {
	Pattern string `json:"PATTERN"`

	Type string `json:"TYPE"`
}

type G2engineStatsResponseReresolveTriggers struct {
	AbortRetry int64 `json:"abortRetry"`

	MultipleResolvableCandidates int64 `json:"multipleResolvableCandidates"`

	ResolveNewFeatures int64 `json:"resolveNewFeatures"`

	UnresolveMovement int64 `json:"unresolveMovement"`
}

type G2engineStatsResponseUnresolveTriggers struct {
	ExtensiveResolve int64 `json:"extensiveResolve"`

	NormalResolve int64 `json:"normalResolve"`
}

type G2engineStatsResponseWorkloadExpressedFeatureCall struct {
	EfcallID int64 `json:"EFCALL_ID"`

	EfuncCode string `json:"EFUNC_CODE"`

	NumCalls int64 `json:"numCalls"`
}

type G2engineStatsResponseWorkloadReresolveTriggers struct {
	AbortRetry int64 `json:"abortRetry"`

	MultipleResolvableCandidates int64 `json:"multipleResolvableCandidates"`

	NewFeatureFtypes AttributeCounters `json:"newFeatureFTypes"`

	ResolveNewFeatures int64 `json:"resolveNewFeatures"`

	UnresolveMovement int64 `json:"unresolveMovement"`
}

type G2engineStatsResponseWorkloadSystemResourcesCurrResourceSystemLoad struct {
	CPUIdle float64 `json:"cpuIdle"`

	CPUSoftIrq float64 `json:"cpuSoftIrq"`

	CPUSystem float64 `json:"cpuSystem"`

	CPUUser float64 `json:"cpuUser"`

	CPUWait float64 `json:"cpuWait"`
}

type G2engineStatsResponseWorkloadSystemResourcesCurrResource struct {
	ActiveThreads int64 `json:"activeThreads"`

	AvailableMemory string `json:"availableMemory"`

	SystemLoad []G2engineStatsResponseWorkloadSystemResourcesCurrResourceSystemLoad `json:"systemLoad"`

	WorkerThreads int64 `json:"workerThreads"`
}

type G2engineStatsResponseWorkloadSystemResourcesInitResource struct {
	AvailableMemory string `json:"availableMemory"`

	LogicalCores int64 `json:"logicalCores"`

	PhysicalCores int64 `json:"physicalCores"`

	TotalMemory string `json:"totalMemory"`
}

type G2engineStatsResponseWorkloadSystemResources struct {
	CurrResources []G2engineStatsResponseWorkloadSystemResourcesCurrResource `json:"currResources"`

	InitResources []G2engineStatsResponseWorkloadSystemResourcesInitResource `json:"initResources"`
}

type G2engineStatsResponseWorkloadThreadState struct {
	Active int64 `json:"active"`

	DataLatchContention int64 `json:"dataLatchContention"`

	Idle int64 `json:"idle"`

	Loader int64 `json:"loader"`

	ObsEntContention int64 `json:"obsEntContention"`

	ResEntContention int64 `json:"resEntContention"`

	Resolver int64 `json:"resolver"`

	Scoring int64 `json:"scoring"`

	SQLExecuting int64 `json:"sqlExecuting"`
}

type G2engineStatsResponseWorkloadUnresolveTriggers struct {
	AmbiguousMultiResolve int64 `json:"ambiguousMultiResolve"`

	AmbiguousNoResolve int64 `json:"ambiguousNoResolve"`

	ExtensiveResolve int64 `json:"extensiveResolve"`

	NormalResolve int64 `json:"normalResolve"`

	RelLink int64 `json:"relLink"`

	Update int64 `json:"update"`
}

type G2engineStatsResponseWorkload struct {
	CorruptEntityTestDiagnosis interface{} `json:"CorruptEntityTestDiagnosis"`

	AbortedUnresolve int64 `json:"abortedUnresolve"`

	ActualAmbiguousTest int64 `json:"actualAmbiguousTest"`

	AddedRecords int64 `json:"addedRecords"`

	APIVersion string `json:"apiVersion"`

	CacheHit AttributeCounters `json:"cacheHit"`

	CacheMiss AttributeCounters `json:"cacheMiss"`

	CachedAmbiguousTest int64 `json:"cachedAmbiguousTest"`

	CandidateBuilders AttributeCounters `json:"candidateBuilders"`

	Candidates int64 `json:"candidates"`

	DeletedRecords int64 `json:"deletedRecords"`

	Duration int64 `json:"duration"`

	ExpressedFeatureCalls []G2engineStatsResponseWorkloadExpressedFeatureCall `json:"expressedFeatureCalls"`

	ExpressedFeaturesCreated AttributeCounters `json:"expressedFeaturesCreated"`

	FilteredObsFeat int64 `json:"filteredObsFeat"`

	GenericDetect AttributeCounters `json:"genericDetect"`

	GnrScorersUsed int64 `json:"gnrScorersUsed"`

	HighContentionFeat AttributeCounters `json:"highContentionFeat"`

	HighContentionResEnt AttributeCounters `json:"highContentionResEnt"`

	LatchContention AttributeCounters `json:"latchContention"`

	LibFeatCacheHit int64 `json:"libFeatCacheHit"`

	LibFeatCacheMiss int64 `json:"libFeatCacheMiss"`

	LoadedRecords int64 `json:"loadedRecords"`

	RedoTriggers AttributeCounters `json:"redoTriggers"`

	ReducedScoredFeatureType AttributeCounters `json:"reducedScoredFeatureType"`

	Reevaluations int64 `json:"reevaluations"`

	RepairedEntities int64 `json:"repairedEntities"`

	ReresolveSkipped int64 `json:"reresolveSkipped"`

	ReresolveTriggers G2engineStatsResponseWorkloadReresolveTriggers `json:"reresolveTriggers"`

	ResFeatStatCacheHit int64 `json:"resFeatStatCacheHit"`

	ResFeatStatCacheMiss int64 `json:"resFeatStatCacheMiss"`

	ResFeatStatUpdate int64 `json:"resFeatStatUpdate"`

	Retries int64 `json:"retries"`

	ScoredPairs AttributeCounters `json:"scoredPairs"`

	SuppressedCandidateBuilders AttributeCounters `json:"suppressedCandidateBuilders"`

	SuppressedDisclosedRelationshipDomainCount int64 `json:"suppressedDisclosedRelationshipDomainCount"`

	SuppressedScoredFeatureType AttributeCounters `json:"suppressedScoredFeatureType"`

	SystemResources G2engineStatsResponseWorkloadSystemResources `json:"systemResources"`

	ThreadState G2engineStatsResponseWorkloadThreadState `json:"threadState"`

	UnresolveTest int64 `json:"unresolveTest"`

	UnresolveTriggers G2engineStatsResponseWorkloadUnresolveTriggers `json:"unresolveTriggers"`
}

type G2engineStatsResponse struct {
	MissingResEnt int64 `json:"MISSING_RES_ENT"`

	MissingResEntAndOkey int64 `json:"MISSING_RES_ENT_AND_OKEY"`

	AbortedUnresolve int64 `json:"abortedUnresolve"`

	ActualAmbiguousTest int64 `json:"actualAmbiguousTest"`

	AddedRecords int64 `json:"addedRecords"`

	CacheHit AttributeCounters `json:"cacheHit"`

	CandidateBuilders AttributeCounters `json:"candidateBuilders"`

	Candidates int64 `json:"candidates"`

	DeletedRecords int64 `json:"deletedRecords"`

	Duration G2engineStatsResponseDuration `json:"duration"`

	FilteredObsFeat int64 `json:"filteredObsFeat"`

	GenericDetect AttributeCounters `json:"genericDetect"`

	LatchContention AttributeCounters `json:"latchContention"`

	LoadedRecords int64 `json:"loadedRecords"`

	RedoTriggers AttributeCounters `json:"redoTriggers"`

	ReducedScoredFeatureType AttributeCounters `json:"reducedScoredFeatureType"`

	Reevaluations int64 `json:"reevaluations"`

	RepairedEntities int64 `json:"repairedEntities"`

	ReresolveSkipped int64 `json:"reresolveSkipped"`

	ReresolveTriggers G2engineStatsResponseReresolveTriggers `json:"reresolveTriggers"`

	Retries int64 `json:"retries"`

	ScoredPairs AttributeCounters `json:"scoredPairs"`

	SuppressedCandidateBuilders AttributeCounters `json:"suppressedCandidateBuilders"`

	SuppressedScoredFeatureType AttributeCounters `json:"suppressedScoredFeatureType"`

	UnresolveTest int64 `json:"unresolveTest"`

	UnresolveTriggers G2engineStatsResponseUnresolveTriggers `json:"unresolveTriggers"`

	Workload G2engineStatsResponseWorkload `json:"workload"`
}

type G2engineStreamExportJsonentityReportResponse = interface{}

type G2engineWhyEntitiesResponse = WhyEntities

type G2engineWhyEntitiesV2response = WhyEntities

type G2engineWhyEntityByEntityIdv2response = WhyEntity

type G2engineWhyEntityByEntityIDResponse = WhyEntity

type G2engineWhyEntityByRecordIdv2response = WhyEntity

type G2engineWhyEntityByRecordIDResponse = WhyEntity

type G2engineWhyRecordsResponse = WhyRecords

type G2engineWhyRecordsV2response = WhyRecords

type G2productLicenseResponse struct {
	Billing string `json:"billing"`

	Contract string `json:"contract"`

	Customer string `json:"customer"`

	ExpireDate string `json:"expireDate"`

	IssueDate string `json:"issueDate"`

	LicenseLevel string `json:"licenseLevel"`

	LicenseType string `json:"licenseType"`

	RecordLimit int64 `json:"recordLimit"`
}

type G2productVersionResponse struct {
	BuildDate string `json:"BUILD_DATE"`

	BuildNumber string `json:"BUILD_NUMBER"`

	BuildVersion string `json:"BUILD_VERSION"`

	CompatibilityVersion CompatibilityVersion `json:"COMPATIBILITY_VERSION"`

	ProductName string `json:"PRODUCT_NAME"`

	SchemaVersion SchemaVersion `json:"SCHEMA_VERSION"`

	Version string `json:"VERSION"`
}

type How struct {
	HowResults HowResults `json:"HOW_RESULTS"`
}

type HowResults struct {
	FinalState FinalState `json:"FINAL_STATE"`

	ResolutionSteps ResolutionSteps `json:"RESOLUTION_STEPS"`
}

type Interesting struct {
	InterestingEntities InterestingEntities `json:"INTERESTING_ENTITIES"`
}

type InterestingEntities struct {
	Entities []InterestingEntity `json:"ENTITIES"`

	Notices Notices `json:"NOTICES"`
}

type InterestingEntitySampleRecords struct {
	DataSource string `json:"DATA_SOURCE"`

	Flags []string `json:"FLAGS"`

	RecordID string `json:"RECORD_ID"`
}

type InterestingEntity struct {
	Degrees int64 `json:"DEGREES"`

	EntityID int64 `json:"ENTITY_ID"`

	Flags []string `json:"FLAGS"`

	SampleRecords []InterestingEntitySampleRecords `json:"SAMPLE_RECORDS"`
}

type JSONDataAcctNum struct {
	AccountDomain string `json:"ACCOUNT_DOMAIN"`

	AccountNumber string `json:"ACCOUNT_NUMBER"`
}

type JSONDataSsn struct {
	PassportNumber string `json:"PASSPORT_NUMBER"`

	SsnNumber string `json:"SSN_NUMBER"`
}

type JSONDataSsnLast4 struct {
	SsnLast4 int64 `json:"SSN_LAST4"`
}

type JSONData struct {
	AccountDomain string `json:"ACCOUNT_DOMAIN"`

	AccountNumber string `json:"ACCOUNT_NUMBER"`

	AcctNum []JSONDataAcctNum `json:"ACCT_NUM"`

	Address string `json:"ADDRESS"`

	AddressList Addresses `json:"ADDRESS_LIST"`

	AddrFull string `json:"ADDR_FULL"`

	AddrKey string `json:"ADDR_KEY"`

	CellPhoneNumber string `json:"CELL_PHONE_NUMBER"`

	Citizenship string `json:"CITIZENSHIP"`

	CountryOfAssociation string `json:"COUNTRY_OF_ASSOCIATION"`

	DataSource string `json:"DATA_SOURCE"`

	DateOfBirth string `json:"DATE_OF_BIRTH"`

	DateOfDeath string `json:"DATE_OF_DEATH"`

	Dob string `json:"DOB"`

	Dod string `json:"DOD"`

	DriversLicenseNumber string `json:"DRIVERS_LICENSE_NUMBER"`

	DriversLicenseState string `json:"DRIVERS_LICENSE_STATE"`

	Drlic string `json:"DRLIC"`

	DsrcAction string `json:"DSRC_ACTION"`

	DsrcCode string `json:"DSRC_CODE"`

	DunsNumber string `json:"DUNS_NUMBER"`

	Email string `json:"EMAIL"`

	EmailAddress string `json:"EMAIL_ADDRESS"`

	EmailKey string `json:"EMAIL_KEY"`

	EmployerName string `json:"EMPLOYER_NAME"`

	EntityType string `json:"ENTITY_TYPE"`

	EntSrcDesc string `json:"ENT_SRC_DESC"`

	EntSrcKey string `json:"ENT_SRC_KEY"`

	EtypeCode string `json:"ETYPE_CODE"`

	Facebook string `json:"FACEBOOK"`

	Gender string `json:"GENDER"`

	GroupAssnIDNumber string `json:"GROUP_ASSN_ID_NUMBER"`

	GroupAssnIDType string `json:"GROUP_ASSN_ID_TYPE"`

	GroupAssociationOrgName string `json:"GROUP_ASSOCIATION_ORG_NAME"`

	GroupAssociationType string `json:"GROUP_ASSOCIATION_TYPE"`

	IDKey string `json:"ID_KEY"`

	Instagram string `json:"INSTAGRAM"`

	LeiNumber string `json:"LEI_NUMBER"`

	Linkedin string `json:"LINKEDIN"`

	LoadID string `json:"LOAD_ID"`

	LoginID string `json:"LOGIN_ID"`

	Name Names `json:"NAME"`

	NameFull string `json:"NAME_FULL"`

	NameKey string `json:"NAME_KEY"`

	NameList Names `json:"NAME_LIST"`

	Nationality string `json:"NATIONALITY"`

	NationalID string `json:"NATIONAL_ID"`

	NationalIDCountry string `json:"NATIONAL_ID_COUNTRY"`

	NationalIDNumber string `json:"NATIONAL_ID_NUMBER"`

	NinCountry string `json:"NIN_COUNTRY"`

	NinNumber string `json:"NIN_NUMBER"`

	NpiNumber string `json:"NPI_NUMBER"`

	ObsSrcKey string `json:"OBS_SRC_KEY"`

	OtherIDCountry string `json:"OTHER_ID_COUNTRY"`

	OtherIDNumber string `json:"OTHER_ID_NUMBER"`

	OtherIDType string `json:"OTHER_ID_TYPE"`

	Passport string `json:"PASSPORT"`

	Passports Passports `json:"PASSPORTS"`

	PassportCountry string `json:"PASSPORT_COUNTRY"`

	PassportNumber string `json:"PASSPORT_NUMBER"`

	Phone string `json:"PHONE"`

	Phones Phones `json:"PHONES"`

	PhoneKey string `json:"PHONE_KEY"`

	PlaceOfBirth string `json:"PLACE_OF_BIRTH"`

	PrimaryNameFirst string `json:"PRIMARY_NAME_FIRST"`

	PrimaryNameLast string `json:"PRIMARY_NAME_LAST"`

	PrimaryNameMiddle string `json:"PRIMARY_NAME_MIDDLE"`

	PrimaryNameOrg string `json:"PRIMARY_NAME_ORG"`

	PrimaryNamePrefix string `json:"PRIMARY_NAME_PREFIX"`

	PrimaryNameSuffix string `json:"PRIMARY_NAME_SUFFIX"`

	PrimaryPhoneNumber string `json:"PRIMARY_PHONE_NUMBER"`

	RecordID string `json:"RECORD_ID"`

	RecordType string `json:"RECORD_TYPE"`

	RegistrationCountry string `json:"REGISTRATION_COUNTRY"`

	RegistrationDate string `json:"REGISTRATION_DATE"`

	Relationships Relationships `json:"RELATIONSHIPS"`

	RelAnchor string `json:"REL_ANCHOR"`

	RelAnchorDomain string `json:"REL_ANCHOR_DOMAIN"`

	RelAnchorKey string `json:"REL_ANCHOR_KEY"`

	RelLink string `json:"REL_LINK"`

	RelPointer string `json:"REL_POINTER"`

	RelPointerDomain string `json:"REL_POINTER_DOMAIN"`

	RelPointerKey string `json:"REL_POINTER_KEY"`

	RelPointerRole string `json:"REL_POINTER_ROLE"`

	Signal string `json:"SIGNAL"`

	Skype string `json:"SKYPE"`

	SocialHandle string `json:"SOCIAL_HANDLE"`

	SocialNetwork string `json:"SOCIAL_NETWORK"`

	SourceID string `json:"SOURCE_ID"`

	Ssn []JSONDataSsn `json:"SSN"`

	SsnLast4 []JSONDataSsnLast4 `json:"SSN_LAST4"`

	SsnNumber string `json:"SSN_NUMBER"`

	Tango string `json:"TANGO"`

	TaxIDCountry string `json:"TAX_ID_COUNTRY"`

	TaxIDNumber string `json:"TAX_ID_NUMBER"`

	TaxIDType string `json:"TAX_ID_TYPE"`

	Telegram string `json:"TELEGRAM"`

	TrustedIDNumber string `json:"TRUSTED_ID_NUMBER"`

	TrustedIDType string `json:"TRUSTED_ID_TYPE"`

	Twitter string `json:"TWITTER"`

	Viber string `json:"VIBER"`

	WebsiteAddress string `json:"WEBSITE_ADDRESS"`

	Wechat string `json:"WECHAT"`

	Whatsapp string `json:"WHATSAPP"`

	WorkPhoneNumber string `json:"WORK_PHONE_NUMBER"`

	Zoomroom string `json:"ZOOMROOM"`

	Name0 Names `json:"name"`
}

type MatchInfoDisclosedRelationsRelAnchor struct {
	Domain string `json:"DOMAIN"`

	FeatDesc string `json:"FEAT_DESC"`

	FeatID int64 `json:"FEAT_ID"`

	LinkedFeatDesc string `json:"LINKED_FEAT_DESC"`

	LinkedFeatID int64 `json:"LINKED_FEAT_ID"`

	LinkedFeatType string `json:"LINKED_FEAT_TYPE"`

	LinkedFeatUsageType string `json:"LINKED_FEAT_USAGE_TYPE"`
}

type MatchInfoDisclosedRelationsRelLink struct {
	Domain string `json:"DOMAIN"`

	FeatDesc string `json:"FEAT_DESC"`

	FeatID int64 `json:"FEAT_ID"`

	FeatUsageType string `json:"FEAT_USAGE_TYPE"`

	LinkedFeatDesc string `json:"LINKED_FEAT_DESC"`

	LinkedFeatID int64 `json:"LINKED_FEAT_ID"`

	LinkedFeatType string `json:"LINKED_FEAT_TYPE"`

	LinkedFeatUsageType string `json:"LINKED_FEAT_USAGE_TYPE"`
}

type MatchInfoDisclosedRelationsRelPointer struct {
	Domain string `json:"DOMAIN"`

	FeatDesc string `json:"FEAT_DESC"`

	FeatID int64 `json:"FEAT_ID"`

	FeatUsageType string `json:"FEAT_USAGE_TYPE"`

	LinkedFeatDesc string `json:"LINKED_FEAT_DESC"`

	LinkedFeatID int64 `json:"LINKED_FEAT_ID"`

	LinkedFeatType string `json:"LINKED_FEAT_TYPE"`
}

type MatchInfoDisclosedRelations struct {
	RelAnchor []MatchInfoDisclosedRelationsRelAnchor `json:"REL_ANCHOR"`

	RelLink []MatchInfoDisclosedRelationsRelLink `json:"REL_LINK"`

	RelPointer []MatchInfoDisclosedRelationsRelPointer `json:"REL_POINTER"`
}

type MatchInfo struct {
	CandidateKeys MatchInfoCandidateKeys `json:"CANDIDATE_KEYS"`

	DisclosedRelations MatchInfoDisclosedRelations `json:"DISCLOSED_RELATIONS"`

	ErruleCode string `json:"ERRULE_CODE"`

	FeatureScores FeatureScores `json:"FEATURE_SCORES"`

	MatchKey string `json:"MATCH_KEY"`

	MatchLevel int64 `json:"MATCH_LEVEL"`

	MatchLevelCode string `json:"MATCH_LEVEL_CODE"`

	WhyErruleCode string `json:"WHY_ERRULE_CODE"`

	WhyKey string `json:"WHY_KEY"`
}

type MatchInfoCandidateKeys struct {
	AccountDomain MatchInfosForAttribute `json:"ACCOUNT_DOMAIN"`

	AccountNumber MatchInfosForAttribute `json:"ACCOUNT_NUMBER"`

	AcctNum MatchInfosForAttribute `json:"ACCT_NUM"`

	Address MatchInfosForAttribute `json:"ADDRESS"`

	AddressList MatchInfosForAttribute `json:"ADDRESS_LIST"`

	AddrFull MatchInfosForAttribute `json:"ADDR_FULL"`

	AddrKey MatchInfosForAttribute `json:"ADDR_KEY"`

	CellPhoneNumber MatchInfosForAttribute `json:"CELL_PHONE_NUMBER"`

	Citizenship MatchInfosForAttribute `json:"CITIZENSHIP"`

	CountryOfAssociation MatchInfosForAttribute `json:"COUNTRY_OF_ASSOCIATION"`

	DataSource MatchInfosForAttribute `json:"DATA_SOURCE"`

	DateOfBirth MatchInfosForAttribute `json:"DATE_OF_BIRTH"`

	DateOfDeath MatchInfosForAttribute `json:"DATE_OF_DEATH"`

	Dob MatchInfosForAttribute `json:"DOB"`

	Dod MatchInfosForAttribute `json:"DOD"`

	DriversLicenseNumber MatchInfosForAttribute `json:"DRIVERS_LICENSE_NUMBER"`

	DriversLicenseState MatchInfosForAttribute `json:"DRIVERS_LICENSE_STATE"`

	Drlic MatchInfosForAttribute `json:"DRLIC"`

	DunsNumber MatchInfosForAttribute `json:"DUNS_NUMBER"`

	Email MatchInfosForAttribute `json:"EMAIL"`

	EmailAddress MatchInfosForAttribute `json:"EMAIL_ADDRESS"`

	EmailKey MatchInfosForAttribute `json:"EMAIL_KEY"`

	EmployerName MatchInfosForAttribute `json:"EMPLOYER_NAME"`

	EntityType MatchInfosForAttribute `json:"ENTITY_TYPE"`

	Facebook MatchInfosForAttribute `json:"FACEBOOK"`

	Gender MatchInfosForAttribute `json:"GENDER"`

	GroupAssnIDNumber MatchInfosForAttribute `json:"GROUP_ASSN_ID_NUMBER"`

	GroupAssnIDType MatchInfosForAttribute `json:"GROUP_ASSN_ID_TYPE"`

	GroupAssociationOrgName MatchInfosForAttribute `json:"GROUP_ASSOCIATION_ORG_NAME"`

	GroupAssociationType MatchInfosForAttribute `json:"GROUP_ASSOCIATION_TYPE"`

	IDKey MatchInfosForAttribute `json:"ID_KEY"`

	Instagram MatchInfosForAttribute `json:"INSTAGRAM"`

	LeiNumber MatchInfosForAttribute `json:"LEI_NUMBER"`

	Linkedin MatchInfosForAttribute `json:"LINKEDIN"`

	LoadID MatchInfosForAttribute `json:"LOAD_ID"`

	LoginID MatchInfosForAttribute `json:"LOGIN_ID"`

	Name MatchInfosForAttribute `json:"NAME"`

	NameFull MatchInfosForAttribute `json:"NAME_FULL"`

	NameKey MatchInfosForAttribute `json:"NAME_KEY"`

	NameList MatchInfosForAttribute `json:"NAME_LIST"`

	Nationality MatchInfosForAttribute `json:"NATIONALITY"`

	NationalID MatchInfosForAttribute `json:"NATIONAL_ID"`

	NationalIDCountry MatchInfosForAttribute `json:"NATIONAL_ID_COUNTRY"`

	NationalIDNumber MatchInfosForAttribute `json:"NATIONAL_ID_NUMBER"`

	NinCountry MatchInfosForAttribute `json:"NIN_COUNTRY"`

	NinNumber MatchInfosForAttribute `json:"NIN_NUMBER"`

	NpiNumber MatchInfosForAttribute `json:"NPI_NUMBER"`

	OtherIDCountry MatchInfosForAttribute `json:"OTHER_ID_COUNTRY"`

	OtherIDNumber MatchInfosForAttribute `json:"OTHER_ID_NUMBER"`

	OtherIDType MatchInfosForAttribute `json:"OTHER_ID_TYPE"`

	Passport MatchInfosForAttribute `json:"PASSPORT"`

	Passports MatchInfosForAttribute `json:"PASSPORTS"`

	PassportCountry MatchInfosForAttribute `json:"PASSPORT_COUNTRY"`

	PassportNumber MatchInfosForAttribute `json:"PASSPORT_NUMBER"`

	Phone MatchInfosForAttribute `json:"PHONE"`

	Phones MatchInfosForAttribute `json:"PHONES"`

	PhoneKey MatchInfosForAttribute `json:"PHONE_KEY"`

	PlaceOfBirth MatchInfosForAttribute `json:"PLACE_OF_BIRTH"`

	PrimaryNameFirst MatchInfosForAttribute `json:"PRIMARY_NAME_FIRST"`

	PrimaryNameLast MatchInfosForAttribute `json:"PRIMARY_NAME_LAST"`

	PrimaryNameMiddle MatchInfosForAttribute `json:"PRIMARY_NAME_MIDDLE"`

	PrimaryNameOrg MatchInfosForAttribute `json:"PRIMARY_NAME_ORG"`

	PrimaryNamePrefix MatchInfosForAttribute `json:"PRIMARY_NAME_PREFIX"`

	PrimaryNameSuffix MatchInfosForAttribute `json:"PRIMARY_NAME_SUFFIX"`

	PrimaryPhoneNumber MatchInfosForAttribute `json:"PRIMARY_PHONE_NUMBER"`

	RecordType MatchInfosForAttribute `json:"RECORD_TYPE"`

	RegistrationCountry MatchInfosForAttribute `json:"REGISTRATION_COUNTRY"`

	RegistrationDate MatchInfosForAttribute `json:"REGISTRATION_DATE"`

	RelAnchor MatchInfosForAttribute `json:"REL_ANCHOR"`

	RelAnchorDomain MatchInfosForAttribute `json:"REL_ANCHOR_DOMAIN"`

	RelAnchorKey MatchInfosForAttribute `json:"REL_ANCHOR_KEY"`

	RelLink MatchInfosForAttribute `json:"REL_LINK"`

	RelPointer MatchInfosForAttribute `json:"REL_POINTER"`

	RelPointerDomain MatchInfosForAttribute `json:"REL_POINTER_DOMAIN"`

	RelPointerKey MatchInfosForAttribute `json:"REL_POINTER_KEY"`

	RelPointerRole MatchInfosForAttribute `json:"REL_POINTER_ROLE"`

	Signal MatchInfosForAttribute `json:"SIGNAL"`

	Skype MatchInfosForAttribute `json:"SKYPE"`

	SocialHandle MatchInfosForAttribute `json:"SOCIAL_HANDLE"`

	SocialNetwork MatchInfosForAttribute `json:"SOCIAL_NETWORK"`

	SourceID MatchInfosForAttribute `json:"SOURCE_ID"`

	Ssn MatchInfosForAttribute `json:"SSN"`

	SsnLast4 MatchInfosForAttribute `json:"SSN_LAST4"`

	SsnNumber MatchInfosForAttribute `json:"SSN_NUMBER"`

	Tango MatchInfosForAttribute `json:"TANGO"`

	TaxIDCountry MatchInfosForAttribute `json:"TAX_ID_COUNTRY"`

	TaxIDNumber MatchInfosForAttribute `json:"TAX_ID_NUMBER"`

	TaxIDType MatchInfosForAttribute `json:"TAX_ID_TYPE"`

	Telegram MatchInfosForAttribute `json:"TELEGRAM"`

	TrustedIDNumber MatchInfosForAttribute `json:"TRUSTED_ID_NUMBER"`

	TrustedIDType MatchInfosForAttribute `json:"TRUSTED_ID_TYPE"`

	Twitter MatchInfosForAttribute `json:"TWITTER"`

	Viber MatchInfosForAttribute `json:"VIBER"`

	WebsiteAddress MatchInfosForAttribute `json:"WEBSITE_ADDRESS"`

	Wechat MatchInfosForAttribute `json:"WECHAT"`

	Whatsapp MatchInfosForAttribute `json:"WHATSAPP"`

	WorkPhoneNumber MatchInfosForAttribute `json:"WORK_PHONE_NUMBER"`

	Zoomroom MatchInfosForAttribute `json:"ZOOMROOM"`
}

type MatchInfoForAttribute struct {
	FeatDesc string `json:"FEAT_DESC"`

	FeatID int64 `json:"FEAT_ID"`
}

type MatchInfosForAttribute = []MatchInfoForAttribute

type MatchScoreForAttribute struct {
	CandidateFeat string `json:"CANDIDATE_FEAT"`

	FullScore int64 `json:"FULL_SCORE"`

	GenerationMatch int64 `json:"GENERATION_MATCH"`

	GnrFn int64 `json:"GNR_FN"`

	GnrGn int64 `json:"GNR_GN"`

	GnrOn int64 `json:"GNR_ON"`

	GnrSn int64 `json:"GNR_SN"`

	InboundFeat string `json:"INBOUND_FEAT"`
}

type MatchScores struct {
	AccountDomain MatchScoresForAttribute `json:"ACCOUNT_DOMAIN"`

	AccountNumber MatchScoresForAttribute `json:"ACCOUNT_NUMBER"`

	AcctNum MatchScoresForAttribute `json:"ACCT_NUM"`

	Address MatchScoresForAttribute `json:"ADDRESS"`

	AddressList MatchScoresForAttribute `json:"ADDRESS_LIST"`

	AddrFull MatchScoresForAttribute `json:"ADDR_FULL"`

	AddrKey MatchScoresForAttribute `json:"ADDR_KEY"`

	CellPhoneNumber MatchScoresForAttribute `json:"CELL_PHONE_NUMBER"`

	Citizenship MatchScoresForAttribute `json:"CITIZENSHIP"`

	CountryOfAssociation MatchScoresForAttribute `json:"COUNTRY_OF_ASSOCIATION"`

	DataSource MatchScoresForAttribute `json:"DATA_SOURCE"`

	DateOfBirth MatchScoresForAttribute `json:"DATE_OF_BIRTH"`

	DateOfDeath MatchScoresForAttribute `json:"DATE_OF_DEATH"`

	Dob MatchScoresForAttribute `json:"DOB"`

	Dod MatchScoresForAttribute `json:"DOD"`

	DriversLicenseNumber MatchScoresForAttribute `json:"DRIVERS_LICENSE_NUMBER"`

	DriversLicenseState MatchScoresForAttribute `json:"DRIVERS_LICENSE_STATE"`

	Drlic MatchScoresForAttribute `json:"DRLIC"`

	DunsNumber MatchScoresForAttribute `json:"DUNS_NUMBER"`

	Email MatchScoresForAttribute `json:"EMAIL"`

	EmailAddress MatchScoresForAttribute `json:"EMAIL_ADDRESS"`

	EmailKey MatchScoresForAttribute `json:"EMAIL_KEY"`

	EmployerName MatchScoresForAttribute `json:"EMPLOYER_NAME"`

	EntityType MatchScoresForAttribute `json:"ENTITY_TYPE"`

	Facebook MatchScoresForAttribute `json:"FACEBOOK"`

	Gender MatchScoresForAttribute `json:"GENDER"`

	GroupAssnIDNumber MatchScoresForAttribute `json:"GROUP_ASSN_ID_NUMBER"`

	GroupAssnIDType MatchScoresForAttribute `json:"GROUP_ASSN_ID_TYPE"`

	GroupAssociationOrgName MatchScoresForAttribute `json:"GROUP_ASSOCIATION_ORG_NAME"`

	GroupAssociationType MatchScoresForAttribute `json:"GROUP_ASSOCIATION_TYPE"`

	IDKey MatchScoresForAttribute `json:"ID_KEY"`

	Instagram MatchScoresForAttribute `json:"INSTAGRAM"`

	LeiNumber MatchScoresForAttribute `json:"LEI_NUMBER"`

	Linkedin MatchScoresForAttribute `json:"LINKEDIN"`

	LoadID MatchScoresForAttribute `json:"LOAD_ID"`

	LoginID MatchScoresForAttribute `json:"LOGIN_ID"`

	Name MatchScoresForAttribute `json:"NAME"`

	NameFull MatchScoresForAttribute `json:"NAME_FULL"`

	NameKey MatchScoresForAttribute `json:"NAME_KEY"`

	NameList MatchScoresForAttribute `json:"NAME_LIST"`

	Nationality MatchScoresForAttribute `json:"NATIONALITY"`

	NationalID MatchScoresForAttribute `json:"NATIONAL_ID"`

	NationalIDCountry MatchScoresForAttribute `json:"NATIONAL_ID_COUNTRY"`

	NationalIDNumber MatchScoresForAttribute `json:"NATIONAL_ID_NUMBER"`

	NinCountry MatchScoresForAttribute `json:"NIN_COUNTRY"`

	NinNumber MatchScoresForAttribute `json:"NIN_NUMBER"`

	NpiNumber MatchScoresForAttribute `json:"NPI_NUMBER"`

	OtherIDCountry MatchScoresForAttribute `json:"OTHER_ID_COUNTRY"`

	OtherIDNumber MatchScoresForAttribute `json:"OTHER_ID_NUMBER"`

	OtherIDType MatchScoresForAttribute `json:"OTHER_ID_TYPE"`

	Passport MatchScoresForAttribute `json:"PASSPORT"`

	Passports MatchScoresForAttribute `json:"PASSPORTS"`

	PassportCountry MatchScoresForAttribute `json:"PASSPORT_COUNTRY"`

	PassportNumber MatchScoresForAttribute `json:"PASSPORT_NUMBER"`

	Phone MatchScoresForAttribute `json:"PHONE"`

	Phones MatchScoresForAttribute `json:"PHONES"`

	PhoneKey MatchScoresForAttribute `json:"PHONE_KEY"`

	PlaceOfBirth MatchScoresForAttribute `json:"PLACE_OF_BIRTH"`

	PrimaryNameFirst MatchScoresForAttribute `json:"PRIMARY_NAME_FIRST"`

	PrimaryNameLast MatchScoresForAttribute `json:"PRIMARY_NAME_LAST"`

	PrimaryNameMiddle MatchScoresForAttribute `json:"PRIMARY_NAME_MIDDLE"`

	PrimaryNameOrg MatchScoresForAttribute `json:"PRIMARY_NAME_ORG"`

	PrimaryNamePrefix MatchScoresForAttribute `json:"PRIMARY_NAME_PREFIX"`

	PrimaryNameSuffix MatchScoresForAttribute `json:"PRIMARY_NAME_SUFFIX"`

	PrimaryPhoneNumber MatchScoresForAttribute `json:"PRIMARY_PHONE_NUMBER"`

	RecordType MatchScoresForAttribute `json:"RECORD_TYPE"`

	RegistrationCountry MatchScoresForAttribute `json:"REGISTRATION_COUNTRY"`

	RegistrationDate MatchScoresForAttribute `json:"REGISTRATION_DATE"`

	RelAnchor MatchScoresForAttribute `json:"REL_ANCHOR"`

	RelAnchorDomain MatchScoresForAttribute `json:"REL_ANCHOR_DOMAIN"`

	RelAnchorKey MatchScoresForAttribute `json:"REL_ANCHOR_KEY"`

	RelLink MatchScoresForAttribute `json:"REL_LINK"`

	RelPointer MatchScoresForAttribute `json:"REL_POINTER"`

	RelPointerDomain MatchScoresForAttribute `json:"REL_POINTER_DOMAIN"`

	RelPointerKey MatchScoresForAttribute `json:"REL_POINTER_KEY"`

	RelPointerRole MatchScoresForAttribute `json:"REL_POINTER_ROLE"`

	Signal MatchScoresForAttribute `json:"SIGNAL"`

	Skype MatchScoresForAttribute `json:"SKYPE"`

	SocialHandle MatchScoresForAttribute `json:"SOCIAL_HANDLE"`

	SocialNetwork MatchScoresForAttribute `json:"SOCIAL_NETWORK"`

	SourceID MatchScoresForAttribute `json:"SOURCE_ID"`

	Ssn MatchScoresForAttribute `json:"SSN"`

	SsnLast4 MatchScoresForAttribute `json:"SSN_LAST4"`

	SsnNumber MatchScoresForAttribute `json:"SSN_NUMBER"`

	Tango MatchScoresForAttribute `json:"TANGO"`

	TaxIDCountry MatchScoresForAttribute `json:"TAX_ID_COUNTRY"`

	TaxIDNumber MatchScoresForAttribute `json:"TAX_ID_NUMBER"`

	TaxIDType MatchScoresForAttribute `json:"TAX_ID_TYPE"`

	Telegram MatchScoresForAttribute `json:"TELEGRAM"`

	TrustedIDNumber MatchScoresForAttribute `json:"TRUSTED_ID_NUMBER"`

	TrustedIDType MatchScoresForAttribute `json:"TRUSTED_ID_TYPE"`

	Twitter MatchScoresForAttribute `json:"TWITTER"`

	Viber MatchScoresForAttribute `json:"VIBER"`

	WebsiteAddress MatchScoresForAttribute `json:"WEBSITE_ADDRESS"`

	Wechat MatchScoresForAttribute `json:"WECHAT"`

	Whatsapp MatchScoresForAttribute `json:"WHATSAPP"`

	WorkPhoneNumber MatchScoresForAttribute `json:"WORK_PHONE_NUMBER"`

	Zoomroom MatchScoresForAttribute `json:"ZOOMROOM"`
}

type MatchScoresForAttribute = []MatchScoreForAttribute

type MemberRecord struct {
	InternalID int64 `json:"INTERNAL_ID"`

	Records Records `json:"RECORDS"`
}

type MemberRecords = []MemberRecord

type Name struct {
	NameFirst string `json:"NAME_FIRST"`

	NameFull string `json:"NAME_FULL"`

	NameLast string `json:"NAME_LAST"`

	NameMiddle string `json:"NAME_MIDDLE"`

	NameOrg string `json:"NAME_ORG"`

	NamePrefix string `json:"NAME_PREFIX"`

	NameSuffix string `json:"NAME_SUFFIX"`

	NameType string `json:"NAME_TYPE"`
}

type Names = []Name

type Network struct {
	Entities Entities `json:"ENTITIES"`

	EntityPaths EntityPaths `json:"ENTITY_PATHS"`

	MaxEntityLimitReached string `json:"MAX_ENTITY_LIMIT_REACHED"`
}

type Notice struct {
	Code string `json:"CODE"`

	Description string `json:"DESCRIPTION"`
}

type Notices = []Notice

type Passport struct {
	PassportCountry string `json:"PASSPORT_COUNTRY"`

	PassportNumber string `json:"PASSPORT_NUMBER"`
}

type Passports = []Passport

type Path struct {
	Entities Entities `json:"ENTITIES"`

	EntityPaths EntityPaths `json:"ENTITY_PATHS"`
}

type Phone struct {
	PhoneFromDate string `json:"PHONE_FROM_DATE"`

	PhoneNumber string `json:"PHONE_NUMBER"`

	PhoneThruDate string `json:"PHONE_THRU_DATE"`

	PhoneType string `json:"PHONE_TYPE"`
}

type Phones = []Phone

type ProcessUmfProc struct {
	Name string `json:"NAME"`

	Result string `json:"RESULT"`
}

type Process struct {
	AffectedEntities AffectedEntities `json:"AFFECTED_ENTITIES"`

	InterestingEntities InterestingEntities `json:"INTERESTING_ENTITIES"`

	ProcessResult ProcessResult `json:"PROCESS_RESULT"`

	UmfProc ProcessUmfProc `json:"UMF_PROC"`
}

type ProcessResultResolvedEntities struct {
	EntityID int64 `json:"ENTITY_ID"`

	EntityName string `json:"ENTITY_NAME"`

	ErruleCode string `json:"ERRULE_CODE"`

	Features Features `json:"FEATURES"`

	LastSeenDt string `json:"LAST_SEEN_DT"`

	MatchKey string `json:"MATCH_KEY"`

	MatchLevel int64 `json:"MATCH_LEVEL"`

	MatchLevelCode string `json:"MATCH_LEVEL_CODE"`

	MatchScores MatchScores `json:"MATCH_SCORES"`

	Records Records `json:"RECORDS"`

	RecordSummary RecordSummary `json:"RECORD_SUMMARY"`
}

type ProcessResult struct {
	ResolvedEntities []ProcessResultResolvedEntities `json:"RESOLVED_ENTITIES"`
}

type ProductLicenseResponse struct {
	Billing string `json:"billing"`

	Contract string `json:"contract"`

	Customer string `json:"customer"`

	ExpireDate string `json:"expireDate"`

	IssueDate string `json:"issueDate"`

	LicenseLevel string `json:"licenseLevel"`

	LicenseType string `json:"licenseType"`

	RecordLimit int64 `json:"recordLimit"`
}

type ProductVersionResponse struct {
	BuildDate string `json:"BUILD_DATE"`

	BuildNumber string `json:"BUILD_NUMBER"`

	BuildVersion string `json:"BUILD_VERSION"`

	CompatibilityVersion CompatibilityVersion `json:"COMPATIBILITY_VERSION"`

	ProductName string `json:"PRODUCT_NAME"`

	SchemaVersion SchemaVersion `json:"SCHEMA_VERSION"`

	Version string `json:"VERSION"`
}

type RecordFeatures struct {
	LibFeatID int64 `json:"LIB_FEAT_ID"`

	UsageType string `json:"USAGE_TYPE"`
}

type Record struct {
	AddressData []string `json:"ADDRESS_DATA"`

	AttributeData []string `json:"ATTRIBUTE_DATA"`

	DataSource string `json:"DATA_SOURCE"`

	EntityData []string `json:"ENTITY_DATA"`

	EntityDesc string `json:"ENTITY_DESC"`

	EntityKey string `json:"ENTITY_KEY"`

	EntityType string `json:"ENTITY_TYPE"`

	ErruleCode string `json:"ERRULE_CODE"`

	Features []RecordFeatures `json:"FEATURES"`

	IdentifierData []string `json:"IDENTIFIER_DATA"`

	InternalID int64 `json:"INTERNAL_ID"`

	JSONData JSONData `json:"JSON_DATA"`

	LastSeenDt string `json:"LAST_SEEN_DT"`

	MatchKey string `json:"MATCH_KEY"`

	MatchLevel int64 `json:"MATCH_LEVEL"`

	MatchLevelCode string `json:"MATCH_LEVEL_CODE"`

	NameData []string `json:"NAME_DATA"`

	OtherData []string `json:"OTHER_DATA"`

	PhoneData []string `json:"PHONE_DATA"`

	RecordID string `json:"RECORD_ID"`

	RelationshipData []string `json:"RELATIONSHIP_DATA"`
}

type RecordSummary = []RecordSummaryElement

type RecordSummaryElement struct {
	DataSource string `json:"DATA_SOURCE"`

	FirstSeenDt string `json:"FIRST_SEEN_DT"`

	LastSeenDt string `json:"LAST_SEEN_DT"`

	RecordCount int64 `json:"RECORD_COUNT"`
}

type Records = []Record

type RelatedEntities = []RelatedEntity

type RelatedEntity struct {
	EntityID int64 `json:"ENTITY_ID"`

	EntityName string `json:"ENTITY_NAME"`

	ErruleCode string `json:"ERRULE_CODE"`

	IsAmbiguous int64 `json:"IS_AMBIGUOUS"`

	IsDisclosed int64 `json:"IS_DISCLOSED"`

	LastSeenDt string `json:"LAST_SEEN_DT"`

	MatchKey string `json:"MATCH_KEY"`

	MatchLevel int64 `json:"MATCH_LEVEL"`

	MatchLevelCode string `json:"MATCH_LEVEL_CODE"`

	Records Records `json:"RECORDS"`

	RecordSummary RecordSummary `json:"RECORD_SUMMARY"`
}

type Relationship struct {
	RelationshipKey string `json:"RELATIONSHIP_KEY"`

	RelationshipType string `json:"RELATIONSHIP_TYPE"`

	RelAnchorDomain string `json:"REL_ANCHOR_DOMAIN"`

	RelAnchorKey string `json:"REL_ANCHOR_KEY"`

	RelPointerDomain string `json:"REL_POINTER_DOMAIN"`

	RelPointerKey string `json:"REL_POINTER_KEY"`

	RelPointerRole string `json:"REL_POINTER_ROLE"`
}

type Relationships = []Relationship

type ResolutionStep struct {
	InboundVirtualEntityID string `json:"INBOUND_VIRTUAL_ENTITY_ID"`

	MatchInfo MatchInfo `json:"MATCH_INFO"`

	ResultVirtualEntityID string `json:"RESULT_VIRTUAL_ENTITY_ID"`

	Step int64 `json:"STEP"`

	VirtualEntity VirtualEntitySynopsis `json:"VIRTUAL_ENTITY_1"`

	VirtualEntity0 VirtualEntitySynopsis `json:"VIRTUAL_ENTITY_2"`
}

type ResolutionSteps = []ResolutionStep

type ResolvedEntities = []ResolvedEntityAndMatchInfo

type ResolvedEntity struct {
	EntityID int64 `json:"ENTITY_ID"`

	EntityName string `json:"ENTITY_NAME"`

	ErruleCode string `json:"ERRULE_CODE"`

	Features Features `json:"FEATURES"`

	IsAmbiguous int64 `json:"IS_AMBIGUOUS"`

	IsDisclosed int64 `json:"IS_DISCLOSED"`

	LastSeenDt string `json:"LAST_SEEN_DT"`

	MatchKey string `json:"MATCH_KEY"`

	MatchLevel int64 `json:"MATCH_LEVEL"`

	MatchLevelCode string `json:"MATCH_LEVEL_CODE"`

	Records Records `json:"RECORDS"`

	RecordSummary RecordSummary `json:"RECORD_SUMMARY"`
}

type ResolvedEntityAndMatchInfoEntity struct {
	ResolvedEntity ResolvedEntity `json:"RESOLVED_ENTITY"`
}

type ResolvedEntityAndMatchInfo struct {
	Entity ResolvedEntityAndMatchInfoEntity `json:"ENTITY"`

	MatchInfo MatchInfo `json:"MATCH_INFO"`
}

type SysOom struct {
	FelemID int64 `json:"FELEM_ID"`

	FtypeID int64 `json:"FTYPE_ID"`

	LensID int64 `json:"LENS_ID"`

	LibFeatID int64 `json:"LIB_FEAT_ID"`

	LibFelemID int64 `json:"LIB_FELEM_ID"`

	NextThresh int64 `json:"NEXT_THRESH"`

	OomLevel string `json:"OOM_LEVEL"`

	OomType string `json:"OOM_TYPE"`

	Thresh1Cnt int64 `json:"THRESH1_CNT"`

	Thresh1Oom int64 `json:"THRESH1_OOM"`
}

type SchemaVersion struct {
	EngineSchemaVersion string `json:"ENGINE_SCHEMA_VERSION"`

	MaximumRequiredSchemaVersion string `json:"MAXIMUM_REQUIRED_SCHEMA_VERSION"`

	MinimumRequiredSchemaVersion string `json:"MINIMUM_REQUIRED_SCHEMA_VERSION"`
}

type Search struct {
	ResolvedEntities []ResolvedEntityAndMatchInfo `json:"RESOLVED_ENTITIES"`

	SearchStatistics SearchStatistics `json:"SEARCH_STATISTICS"`
}

type SearchStatisticCandidateKeysFeatureTypes struct {
	Found int64 `json:"FOUND"`

	FtypeCode string `json:"FTYPE_CODE"`

	Generic int64 `json:"GENERIC"`

	NotFound int64 `json:"NOT_FOUND"`
}

type SearchStatisticCandidateKeysSummary struct {
	Found int64 `json:"FOUND"`

	Generic int64 `json:"GENERIC"`

	NotFound int64 `json:"NOT_FOUND"`
}

type SearchStatisticCandidateKeys struct {
	FeatureTypes []SearchStatisticCandidateKeysFeatureTypes `json:"FEATURE_TYPES"`

	Summary SearchStatisticCandidateKeysSummary `json:"SUMMARY"`
}

type SearchStatistic struct {
	CandidateKeys SearchStatisticCandidateKeys `json:"CANDIDATE_KEYS"`
}

type SearchStatistics = []SearchStatistic

type VirtualEntity struct {
	ResolvedEntity ResolvedEntity `json:"RESOLVED_ENTITY"`
}

type VirtualEntitySynopsis struct {
	MemberRecords MemberRecords `json:"MEMBER_RECORDS"`

	VirtualEntityID string `json:"VIRTUAL_ENTITY_ID"`
}

type WhyEntities struct {
	Entities Entities `json:"ENTITIES"`

	WhyResults WhyResults `json:"WHY_RESULTS"`
}

type WhyEntity struct {
	Entities Entities `json:"ENTITIES"`

	WhyResults WhyResults `json:"WHY_RESULTS"`
}

type WhyRecords struct {
	Entities Entities `json:"ENTITIES"`

	WhyResults WhyResults `json:"WHY_RESULTS"`
}

type WhyResult struct {
	EntityID int64 `json:"ENTITY_ID"`

	EntityID0 int64 `json:"ENTITY_ID_2"`

	FocusRecords FocusRecords `json:"FOCUS_RECORDS"`

	FocusRecords0 FocusRecords `json:"FOCUS_RECORDS_2"`

	InternalID int64 `json:"INTERNAL_ID"`

	InternalID0 int64 `json:"INTERNAL_ID_2"`

	MatchInfo MatchInfo `json:"MATCH_INFO"`
}

type WhyResults = []WhyResult

type WithInfo struct {
	AffectedEntities AffectedEntities `json:"AFFECTED_ENTITIES"`

	DataSource string `json:"DATA_SOURCE"`

	InterestingEntities InterestingEntities `json:"INTERESTING_ENTITIES"`

	RecordID string `json:"RECORD_ID"`
}
