// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1
#pragma warning disable CS8601, CS8618

using System.Text.Json.Serialization;

namespace Senzing.Typedef
{
    public class CfgEtype
    {
        [JsonPropertyName("XXX_ECLASS_ID")]
        public int XxxEclassId { get; set; }

        [JsonPropertyName("XXX_ETYPE_CODE")]
        public string XxxEtypeCode { get; set; }

        [JsonPropertyName("XXX_ETYPE_DESC")]
        public string XxxEtypeDesc { get; set; }

        [JsonPropertyName("XXX_ETYPE_ID")]
        public int XxxEtypeId { get; set; }
    }
}
