// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1
#pragma warning disable CS8601, CS8618

using System.Text.Json.Serialization;

namespace Senzing.Typedef
{
    public class CfgSfunc
    {
        [JsonPropertyName("CONNECT_STR")]
        public string ConnectStr { get; set; }

        [JsonPropertyName("SFUNC_CODE")]
        public string SfuncCode { get; set; }

        [JsonPropertyName("SFUNC_DESC")]
        public string SfuncDesc { get; set; }

        [JsonPropertyName("SFUNC_ID")]
        public int SfuncId { get; set; }

        [JsonPropertyName("XXX_FUNC_LIB")]
        public string XxxFuncLib { get; set; }

        [JsonPropertyName("XXX_FUNC_VER")]
        public string XxxFuncVer { get; set; }

        [JsonPropertyName("XXX_JAVA_CLASS_NAME")]
        public string XxxJavaClassName { get; set; }

        [JsonPropertyName("XXX_LANGUAGE")]
        public string XxxLanguage { get; set; }
    }
}
