// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1
#pragma warning disable CS8601, CS8618

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Senzing.Typedef
{
    public class DisclosedRelationsForMatchInfo
    {
        [JsonPropertyName("XXX_REL_ANCHOR")]
        public IList<RelAnchor> XxxRelAnchor { get; set; }

        [JsonPropertyName("XXX_REL_LINK")]
        public IList<RelLink> XxxRelLink { get; set; }

        [JsonPropertyName("XXX_REL_POINTER")]
        public IList<RelPointer> XxxRelPointer { get; set; }
    }
}
