// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1
#pragma warning disable CS8601, CS8618

using System.Text.Json.Serialization;

namespace Senzing.Typedef
{
    /// <summary>
    /// FIXME: ...
    /// </summary>
    public class EntityPathLink
    {
        /// <summary>
        /// Identifier of the entity resolution principle that was triggered.
        /// </summary>
        [JsonPropertyName("ERRULE_CODE")]
        public string ErruleCode { get; set; }

        /// <summary>
        /// Indicates if this is an ambiguous relationship.
        /// </summary>
        [JsonPropertyName("IS_AMBIGUOUS")]
        public int IsAmbiguous { get; set; }

        /// <summary>
        /// Indicates if this is a disclosed relationship.
        /// </summary>
        [JsonPropertyName("IS_DISCLOSED")]
        public int IsDisclosed { get; set; }

        /// <summary>
        /// Representation of matched source record features.
        /// </summary>
        [JsonPropertyName("MATCH_KEY")]
        public string MatchKey { get; set; }

        [JsonPropertyName("MATCH_KEY_DETAILS")]
        public MatchKeyDetails MatchKeyDetails { get; set; }

        /// <summary>
        /// The type of match that occurred for the record.
        /// </summary>
        [JsonPropertyName("MATCH_LEVEL_CODE")]
        public string MatchLevelCode { get; set; }

        [JsonPropertyName("MAX_ENTITY_ID")]
        public int MaxEntityId { get; set; }

        [JsonPropertyName("MIN_ENTITY_ID")]
        public int MinEntityId { get; set; }
    }
}
