// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1
#pragma warning disable CS8601, CS8618

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Senzing.Typedef
{
    public class MatchKeyDetails
    {
        [JsonPropertyName("CONFIRMATIONS")]
        public IList<Confirmation> Confirmations { get; set; }

        [JsonPropertyName("DENIALS")]
        public IList<Confirmation> Denials { get; set; }

        /// <summary>
        /// Identifier of the entity resolution rule that was triggered.
        /// </summary>
        [JsonPropertyName("XXX_ERRULE_CODE")]
        public string XxxErruleCode { get; set; }
    }
}
