// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1
#pragma warning disable CS8601, CS8618

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Senzing.Typedef
{
    public class SearchEntity
    {
        [JsonPropertyName("FEATURES")]
        public IDictionary<string, IList<FeatureDescriptionValue>> Features { get; set; }

        [JsonPropertyName("SUMMARY")]
        public SearchEntitySummary Summary { get; set; }
    }
}
