// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1
#pragma warning disable CS8601, CS8618

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Senzing.Typedef
{
    public class SzEngineSearchByAttributesResponse
    {
        /// <summary>
        /// A list of ...
        /// </summary>
        [JsonPropertyName("RELATED_ENTITIES_MJD")]
        public IList<RelatedEntity> RelatedEntitiesMjd { get; set; }

        /// <summary>
        /// A list of ...
        /// </summary>
        [JsonPropertyName("RESOLVED_ENTITIES")]
        public IList<ResolvedEntityAndMatchInfo> ResolvedEntities { get; set; }

        [JsonPropertyName("SEARCH_ENTITY")]
        public SearchEntity SearchEntity { get; set; }

        [JsonPropertyName("SEARCH_REQUEST")]
        public SearchRequest SearchRequest { get; set; }

        /// <summary>
        /// A list of ...
        /// </summary>
        [JsonPropertyName("SEARCH_STATISTICS")]
        public IList<SearchStatistic> SearchStatistics { get; set; }
    }
}
