// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1
#pragma warning disable CS8601, CS8618

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Senzing.Typedef
{
    /// <summary>
    /// FIXME: WorkloadExpressedFeatures
    /// </summary>
    public class WorkloadExpressedFeatures
    {
        /// <summary>
        /// FIXME: A list of ...
        /// </summary>
        [JsonPropertyName("calls")]
        public IList<WorkloadExpressedFeaturesCall> Calls { get; set; }

        /// <summary>
        /// FIXME: A map from ... to ...
        /// </summary>
        [JsonPropertyName("created")]
        public IDictionary<string, int> Created { get; set; }
    }
}
