// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1
#pragma warning disable CS8601, CS8618

using System.Text.Json.Serialization;

namespace Senzing.Schema
{
    public class CfgDsrc
    {
        [JsonPropertyName("CONVERSATIONAL")]
        public string Conversational { get; set; }

        [JsonPropertyName("DSRC_CODE")]
        public string DsrcCode { get; set; }

        [JsonPropertyName("DSRC_DESC")]
        public string DsrcDesc { get; set; }

        [JsonPropertyName("DSRC_ID")]
        public int DsrcId { get; set; }

        [JsonPropertyName("DSRC_RELY")]
        public int DsrcRely { get; set; }

        [JsonPropertyName("RETENTION_LEVEL")]
        public string RetentionLevel { get; set; }
    }
}
