// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1
#pragma warning disable CS8601, CS8618

using System.Text.Json.Serialization;

namespace Senzing.Schema
{
    public class CfgSfcall
    {
        [JsonPropertyName("EXEC_ORDER")]
        public int ExecOrder { get; set; }

        [JsonPropertyName("FELEM_ID")]
        public int FelemId { get; set; }

        [JsonPropertyName("FTYPE_ID")]
        public int FtypeId { get; set; }

        [JsonPropertyName("SFCALL_ID")]
        public int SfcallId { get; set; }

        [JsonPropertyName("SFUNC_ID")]
        public int SfuncId { get; set; }
    }
}
