// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Text.Json.Serialization;

namespace Senzing.Schema
{
    public class Config
    {
        [JsonPropertyName("CONFIG_COMMENTS")]
        public string ConfigComments { get; set; }

        [JsonPropertyName("CONFIG_ID")]
        public int ConfigId { get; set; }

        [JsonPropertyName("SYS_CREATE_DT")]
        public string SysCreateDt { get; set; }
    }
}
