// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1
#pragma warning disable CS8601, CS8618

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Senzing.Schema
{
    public class ExpressedFeatures
    {
        [JsonPropertyName("calls")]
        public IList<ExpressedFeaturesCall> Calls { get; set; }

        [JsonPropertyName("created")]
        public IDictionary<string, int> Created { get; set; }
    }
}
