// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Senzing.Schema
{
    public class InterestingEntity
    {
        [JsonPropertyName("DEGREES")]
        public int Degrees { get; set; }

        /// <summary>
        /// The ENTITY_ID is the Senzing-generated identifier for the discovered
        /// entity. It may change when new information is added.
        /// </summary>
        [JsonPropertyName("ENTITY_ID")]
        public int EntityId { get; set; }

        [JsonPropertyName("FLAGS")]
        public IList<string> Flags { get; set; }

        [JsonPropertyName("SAMPLE_RECORDS")]
        public IList<InterestingEntitySampleRecords> SampleRecords { get; set; }
    }
}
