// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1
#pragma warning disable CS8601, CS8618

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Senzing.Schema
{
    public class InterestingEntitySampleRecords
    {
        [JsonPropertyName("DATA_SOURCE")]
        public string DataSource { get; set; }

        [JsonPropertyName("FLAGS")]
        public IList<string> Flags { get; set; }

        [JsonPropertyName("RECORD_ID")]
        public string RecordId { get; set; }
    }
}
