// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1
#pragma warning disable CS8601, CS8618

using System.Text.Json.Serialization;

namespace Senzing.Schema
{
    public class Reresolve
    {
        [JsonPropertyName("newFeatureFTypes")]
        public string NewFeatureFtypes { get; set; }

        [JsonPropertyName("suppressedCandidateBuildersForReresolve")]
        public Fixme SuppressedCandidateBuildersForReresolve { get; set; }

        [JsonPropertyName("suppressedScoredFeatureTypeForReresolve")]
        public Fixme SuppressedScoredFeatureTypeForReresolve { get; set; }

        [JsonPropertyName("triggers")]
        public ReresolveTriggers Triggers { get; set; }
    }
}
