// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1
#pragma warning disable CS8601, CS8618

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Senzing.Schema
{
    [JsonConverter(typeof(StreamExportJsonEntityJsonConverter))]
    public class StreamExportJsonEntity
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public FixmeUnknown Value { get; set; }
    }

    public class StreamExportJsonEntityJsonConverter : JsonConverter<StreamExportJsonEntity>
    {
        public override StreamExportJsonEntity Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new StreamExportJsonEntity { Value = JsonSerializer.Deserialize<FixmeUnknown>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, StreamExportJsonEntity value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<FixmeUnknown>(writer, value.Value, options);
        }
    }
}
