// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1
#pragma warning disable CS8601, CS8618

using System.Text.Json.Serialization;

namespace Senzing.Schema
{
    public class SystemLoad
    {
        [JsonPropertyName("cpuIdle")]
        public float CpuIdle { get; set; }

        [JsonPropertyName("cpuSystem")]
        public float CpuSystem { get; set; }

        [JsonPropertyName("cpuUser")]
        public float CpuUser { get; set; }

        [JsonPropertyName("cpuWait")]
        public float CpuWait { get; set; }
    }
}
