// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1
#pragma warning disable CS8601, CS8618

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Senzing.Schema
{
    [JsonConverter(typeof(SzConfigRegisterDataSourceResponseJsonConverter))]
    public class SzConfigRegisterDataSourceResponse
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public RegisterDataSource Value { get; set; }
    }

    public class SzConfigRegisterDataSourceResponseJsonConverter : JsonConverter<SzConfigRegisterDataSourceResponse>
    {
        public override SzConfigRegisterDataSourceResponse Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new SzConfigRegisterDataSourceResponse { Value = JsonSerializer.Deserialize<RegisterDataSource>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, SzConfigRegisterDataSourceResponse value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<RegisterDataSource>(writer, value.Value, options);
        }
    }
}
