// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1
#pragma warning disable CS8601, CS8618

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Senzing.Schema
{
    public class SzEngineWhySearchResponse
    {
        [JsonPropertyName("ENTITIES")]
        public IList<EntityForWhySearch> Entities { get; set; }

        [JsonPropertyName("SEARCH_REQUEST")]
        public SearchRequest SearchRequest { get; set; }

        [JsonPropertyName("SEARCH_STATISTICS")]
        public IList<SearchStatistic> SearchStatistics { get; set; }

        [JsonPropertyName("WHY_RESULTS")]
        public IList<WhyResult> WhyResults { get; set; }
    }
}
