// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1
#pragma warning disable CS8601, CS8618

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Senzing.Schema
{
    public class SzEngineSearchByAttributesResponse
    {
        [JsonPropertyName("RESOLVED_ENTITIES")]
        public IList<ResolvedEntityAndMatchInfo> ResolvedEntities { get; set; }

        [JsonPropertyName("SEARCH_REQUEST")]
        public SearchRequest SearchRequest { get; set; }

        [JsonPropertyName("SEARCH_STATISTICS")]
        public SearchStatistics SearchStatistics { get; set; }
    }
}
