// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1
#pragma warning disable CS8601, CS8618

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Senzing.Schema
{
    public class SzEngineFindNetworkByEntityIdResponse
    {
        [JsonPropertyName("ENTITIES")]
        public IList<Entity> Entities { get; set; }

        [JsonPropertyName("ENTITY_NETWORK_LINKS")]
        public IList<EntityNetworkLink> EntityNetworkLinks { get; set; }

        [JsonPropertyName("ENTITY_PATHS")]
        public IList<EntityPath> EntityPaths { get; set; }

        [JsonPropertyName("ENTITY_PATH_LINKS")]
        public IList<EntityPathLink> EntityPathLinks { get; set; }

        [JsonPropertyName("MAX_ENTITY_LIMIT_REACHED")]
        public string MaxEntityLimitReached { get; set; }
    }
}
