// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.schema;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.util.Map;

@JsonSerialize
public class Candidates {
    @JsonProperty("candidateBuilders")
    private Map<String, Integer> candidateBuilders;

    @JsonProperty("suppressedCandidateBuilders")
    private Map<String, Integer> suppressedCandidateBuilders;

    public Candidates() {
    }

    /**
     * Getter for candidateBuilders.<p>
     */
    public Map<String, Integer> getCandidateBuilders() {
        return candidateBuilders;
    }

    /**
     * Setter for candidateBuilders.<p>
     */
    public void setCandidateBuilders(Map<String, Integer> candidateBuilders) {
        this.candidateBuilders = candidateBuilders;
    }

    /**
     * Getter for suppressedCandidateBuilders.<p>
     */
    public Map<String, Integer> getSuppressedCandidateBuilders() {
        return suppressedCandidateBuilders;
    }

    /**
     * Setter for suppressedCandidateBuilders.<p>
     */
    public void setSuppressedCandidateBuilders(Map<String, Integer> suppressedCandidateBuilders) {
        this.suppressedCandidateBuilders = suppressedCandidateBuilders;
    }
}
