// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.schema;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

@JsonSerialize
public class Contention {
    @JsonProperty("feature")
    private Fixme feature;

    @JsonProperty("resEnt")
    private Fixme resEnt;

    @JsonProperty("valuelatch")
    private Fixme valuelatch;

    public Contention() {
    }

    /**
     * Getter for feature.<p>
     */
    public Fixme getFeature() {
        return feature;
    }

    /**
     * Setter for feature.<p>
     */
    public void setFeature(Fixme feature) {
        this.feature = feature;
    }

    /**
     * Getter for resEnt.<p>
     */
    public Fixme getResEnt() {
        return resEnt;
    }

    /**
     * Setter for resEnt.<p>
     */
    public void setResEnt(Fixme resEnt) {
        this.resEnt = resEnt;
    }

    /**
     * Getter for valuelatch.<p>
     */
    public Fixme getValuelatch() {
        return valuelatch;
    }

    /**
     * Setter for valuelatch.<p>
     */
    public void setValuelatch(Fixme valuelatch) {
        this.valuelatch = valuelatch;
    }
}
