// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.schema;

import java.util.Map;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

@JsonSerialize
public class FeatureDescriptionValue {
    @JsonProperty("ATTRIBUTES")
    private Map<String, String> attributes;

    @JsonProperty("CANDIDATE_CAP_REACHED")
    private String candidateCapReached;

    @JsonProperty("ENTITY_COUNT")
    private Integer entityCount;

    @JsonProperty("FEAT_DESC")
    private String featDesc;

    @JsonProperty("LIB_FEAT_ID")
    private Integer libFeatId;

    @JsonProperty("SCORING_CAP_REACHED")
    private String scoringCapReached;

    @JsonProperty("SUPPRESSED")
    private String suppressed;

    @JsonProperty("USED_FOR_CAND")
    private String usedForCand;

    @JsonProperty("USED_FOR_SCORING")
    private String usedForScoring;

    public FeatureDescriptionValue() {
    }

    /**
     * Getter for attributes.<p>
     */
    public Map<String, String> getAttributes() {
        return attributes;
    }

    /**
     * Setter for attributes.<p>
     */
    public void setAttributes(Map<String, String> attributes) {
        this.attributes = attributes;
    }

    /**
     * Getter for candidateCapReached.<p>
     */
    public String getCandidateCapReached() {
        return candidateCapReached;
    }

    /**
     * Setter for candidateCapReached.<p>
     */
    public void setCandidateCapReached(String candidateCapReached) {
        this.candidateCapReached = candidateCapReached;
    }

    /**
     * Getter for entityCount.<p>
     */
    public Integer getEntityCount() {
        return entityCount;
    }

    /**
     * Setter for entityCount.<p>
     */
    public void setEntityCount(Integer entityCount) {
        this.entityCount = entityCount;
    }

    /**
     * Getter for featDesc.<p>
     * Describes the attributes that make up the feature.
     */
    public String getFeatDesc() {
        return featDesc;
    }

    /**
     * Setter for featDesc.<p>
     * Describes the attributes that make up the feature.
     */
    public void setFeatDesc(String featDesc) {
        this.featDesc = featDesc;
    }

    /**
     * Getter for libFeatId.<p>
     */
    public Integer getLibFeatId() {
        return libFeatId;
    }

    /**
     * Setter for libFeatId.<p>
     */
    public void setLibFeatId(Integer libFeatId) {
        this.libFeatId = libFeatId;
    }

    /**
     * Getter for scoringCapReached.<p>
     */
    public String getScoringCapReached() {
        return scoringCapReached;
    }

    /**
     * Setter for scoringCapReached.<p>
     */
    public void setScoringCapReached(String scoringCapReached) {
        this.scoringCapReached = scoringCapReached;
    }

    /**
     * Getter for suppressed.<p>
     */
    public String getSuppressed() {
        return suppressed;
    }

    /**
     * Setter for suppressed.<p>
     */
    public void setSuppressed(String suppressed) {
        this.suppressed = suppressed;
    }

    /**
     * Getter for usedForCand.<p>
     */
    public String getUsedForCand() {
        return usedForCand;
    }

    /**
     * Setter for usedForCand.<p>
     */
    public void setUsedForCand(String usedForCand) {
        this.usedForCand = usedForCand;
    }

    /**
     * Getter for usedForScoring.<p>
     */
    public String getUsedForScoring() {
        return usedForScoring;
    }

    /**
     * Setter for usedForScoring.<p>
     */
    public void setUsedForScoring(String usedForScoring) {
        this.usedForScoring = usedForScoring;
    }
}
