// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.schema;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

@JsonSerialize
public class Fixme {
    @JsonProperty("FIXME")
    private String fixme;

    public Fixme() {
    }

    /**
     * Getter for fixme.<p>
     */
    public String getFixme() {
        return fixme;
    }

    /**
     * Setter for fixme.<p>
     */
    public void setFixme(String fixme) {
        this.fixme = fixme;
    }
}
