// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.schema;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.util.List;

@JsonSerialize
public class InterestingEntities {
    @JsonProperty("ENTITIES")
    private List<InterestingEntity> entities;

    @JsonProperty("NOTICES")
    private List<InterestingEntitiesNotices> notices;

    public InterestingEntities() {
    }

    /**
     * Getter for entities.<p>
     */
    public List<InterestingEntity> getEntities() {
        return entities;
    }

    /**
     * Setter for entities.<p>
     */
    public void setEntities(List<InterestingEntity> entities) {
        this.entities = entities;
    }

    /**
     * Getter for notices.<p>
     */
    public List<InterestingEntitiesNotices> getNotices() {
        return notices;
    }

    /**
     * Setter for notices.<p>
     */
    public void setNotices(List<InterestingEntitiesNotices> notices) {
        this.notices = notices;
    }
}
