// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.schema;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.util.List;

@JsonSerialize
public class MemberRecord {
    @JsonProperty("INTERNAL_ID")
    private Integer internalId;

    @JsonProperty("RECORDS")
    private List<Record> records;

    public MemberRecord() {
    }

    /**
     * Getter for internalId.<p>
     * Internal identifier for the record.
     */
    public Integer getInternalId() {
        return internalId;
    }

    /**
     * Setter for internalId.<p>
     * Internal identifier for the record.
     */
    public void setInternalId(Integer internalId) {
        this.internalId = internalId;
    }

    /**
     * Getter for records.<p>
     */
    public List<Record> getRecords() {
        return records;
    }

    /**
     * Setter for records.<p>
     */
    public void setRecords(List<Record> records) {
        this.records = records;
    }
}
