// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.schema;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.List;

public class MemberRecords {
    @JsonValue
    private List<MemberRecord> value;

    public MemberRecords() {
    }

    @JsonCreator
    public MemberRecords(List<MemberRecord> value) {
        this.value = value;
    }

    public List<MemberRecord> getValue() {
        return value;
    }

    public void setValue(List<MemberRecord> value) {
        this.value = value;
    }
}
