// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.schema;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.List;

public class RecordsForGetEntity {
    @JsonValue
    private List<RecordForGetEntity> value;

    public RecordsForGetEntity() {
    }

    @JsonCreator
    public RecordsForGetEntity(List<RecordForGetEntity> value) {
        this.value = value;
    }

    public List<RecordForGetEntity> getValue() {
        return value;
    }

    public void setValue(List<RecordForGetEntity> value) {
        this.value = value;
    }
}
