// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.schema;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

@JsonSerialize
public class ResolvedEntityAndMatchInfoEntity {
    @JsonProperty("RESOLVED_ENTITY")
    private ResolvedEntity resolvedEntity;

    public ResolvedEntityAndMatchInfoEntity() {
    }

    /**
     * Getter for resolvedEntity.<p>
     */
    public ResolvedEntity getResolvedEntity() {
        return resolvedEntity;
    }

    /**
     * Setter for resolvedEntity.<p>
     */
    public void setResolvedEntity(ResolvedEntity resolvedEntity) {
        this.resolvedEntity = resolvedEntity;
    }
}
