// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.schema;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

@JsonSerialize
public class SystemLoad {
    @JsonProperty("cpuIdle")
    private Float cpuIdle;

    @JsonProperty("cpuSystem")
    private Float cpuSystem;

    @JsonProperty("cpuUser")
    private Float cpuUser;

    @JsonProperty("cpuWait")
    private Float cpuWait;

    public SystemLoad() {
    }

    /**
     * Getter for cpuIdle.<p>
     */
    public Float getCpuIdle() {
        return cpuIdle;
    }

    /**
     * Setter for cpuIdle.<p>
     */
    public void setCpuIdle(Float cpuIdle) {
        this.cpuIdle = cpuIdle;
    }

    /**
     * Getter for cpuSystem.<p>
     */
    public Float getCpuSystem() {
        return cpuSystem;
    }

    /**
     * Setter for cpuSystem.<p>
     */
    public void setCpuSystem(Float cpuSystem) {
        this.cpuSystem = cpuSystem;
    }

    /**
     * Getter for cpuUser.<p>
     */
    public Float getCpuUser() {
        return cpuUser;
    }

    /**
     * Setter for cpuUser.<p>
     */
    public void setCpuUser(Float cpuUser) {
        this.cpuUser = cpuUser;
    }

    /**
     * Getter for cpuWait.<p>
     */
    public Float getCpuWait() {
        return cpuWait;
    }

    /**
     * Setter for cpuWait.<p>
     */
    public void setCpuWait(Float cpuWait) {
        this.cpuWait = cpuWait;
    }
}
