// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.schema;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.util.List;

@JsonSerialize
public class SzEngineGetRecordPreviewResponse {
    @JsonProperty("FEATURES")
    private MapStringToListOfFeatureForAttributeWithAttributes features;

    @JsonProperty("FEATURE_IDS")
    private List<FeatureId> featureIds;

    @JsonProperty("JSON_DATA")
    private MapStringToObject jsonData;

    @JsonProperty("UNMAPPED_DATA")
    private MapStringToObject unmappedData;

    public SzEngineGetRecordPreviewResponse() {
    }

    /**
     * Getter for features.<p>
     */
    public MapStringToListOfFeatureForAttributeWithAttributes getFeatures() {
        return features;
    }

    /**
     * Setter for features.<p>
     */
    public void setFeatures(MapStringToListOfFeatureForAttributeWithAttributes features) {
        this.features = features;
    }

    /**
     * Getter for featureIds.<p>
     */
    public List<FeatureId> getFeatureIds() {
        return featureIds;
    }

    /**
     * Setter for featureIds.<p>
     */
    public void setFeatureIds(List<FeatureId> featureIds) {
        this.featureIds = featureIds;
    }

    /**
     * Getter for jsonData.<p>
     */
    public MapStringToObject getJsonData() {
        return jsonData;
    }

    /**
     * Setter for jsonData.<p>
     */
    public void setJsonData(MapStringToObject jsonData) {
        this.jsonData = jsonData;
    }

    /**
     * Getter for unmappedData.<p>
     */
    public MapStringToObject getUnmappedData() {
        return unmappedData;
    }

    /**
     * Setter for unmappedData.<p>
     */
    public void setUnmappedData(MapStringToObject unmappedData) {
        this.unmappedData = unmappedData;
    }
}
