// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.schema;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.util.List;

@JsonSerialize
public class SzEngineSearchByAttributesResponse {
    @JsonProperty("RESOLVED_ENTITIES")
    private List<ResolvedEntityAndMatchInfo> resolvedEntities;

    @JsonProperty("SEARCH_REQUEST")
    private SearchRequest searchRequest;

    @JsonProperty("SEARCH_STATISTICS")
    private List<SearchStatistic> searchStatistics;

    public SzEngineSearchByAttributesResponse() {
    }

    /**
     * Getter for resolvedEntities.<p>
     */
    public List<ResolvedEntityAndMatchInfo> getResolvedEntities() {
        return resolvedEntities;
    }

    /**
     * Setter for resolvedEntities.<p>
     */
    public void setResolvedEntities(List<ResolvedEntityAndMatchInfo> resolvedEntities) {
        this.resolvedEntities = resolvedEntities;
    }

    /**
     * Getter for searchRequest.<p>
     */
    public SearchRequest getSearchRequest() {
        return searchRequest;
    }

    /**
     * Setter for searchRequest.<p>
     */
    public void setSearchRequest(SearchRequest searchRequest) {
        this.searchRequest = searchRequest;
    }

    /**
     * Getter for searchStatistics.<p>
     */
    public List<SearchStatistic> getSearchStatistics() {
        return searchStatistics;
    }

    /**
     * Setter for searchStatistics.<p>
     */
    public void setSearchStatistics(List<SearchStatistic> searchStatistics) {
        this.searchStatistics = searchStatistics;
    }
}
